### ISSUE TITLE
Best way to backup the drupal vm?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#1017]
### Issue Type

 - Support Request

### Your Environment

Vagrant 1.8.5 for Windows
VirtualBox 5.1.12 (Oracle) 

### Your OS
 - Windows 10

### Summary

What is the best way to backup my Drupal VM?
Backup all at once,  backup important parts.
If there is a problem in the future, how can I then restore some of the working backups?

Thank you.

**Comment by geerlingguy** [comment]
One of the main reasons for using Drupal VM is to have more-or-less ephemeral development environments. I often destroy and rebuild my VMs at least on a weekly basis, sometimes more frequently if I'm testing new infrastructure changes.

Because of that, there's no official/simple backup procedure. However, if you do need to be able to recover a VM, you'd back it up like any other VirtualBox VM—you can do snapshots through VirtualBox (or even triggered through a Vagrant plugin), and you can backup the VM files wherever you have VirtualBox set to store them.

**Comment by webprogrammierer** [comment]
Thank you.
I made a snapshot in Orvacle VM VirtualBox.

**Comment by geerlingguy** [comment]
Perfect! See also: https://www.vagrantup.com/docs/cli/snapshot.html
