### ISSUE TITLE
Drush not working on d7 sites

### ISSUE THREAD

**Issue by danharper83** [geerlingguy/drupal-vm#1020]
Bug Report / Support Request
```
Vagrant 1.8.7
VirtualBox 5.0.28r111378
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```
 - **macOS** Sierra 10.12.1

### Full console output

```
[error]  WD php: Error: Class 'Drupal\user\Entity\User' not found in Drush\Boot\DrupalBoot->bootstrap_drupal_login() (line 571 of /usr/local/share/drush/lib/Drush/Boot/DrupalBoot.php). 
Error: Class &#039;Drupal\user\Entity\User&#039; not found in Drush\Boot\DrupalBoot->bootstrap_drupal_login() (line 571 of /usr/local/share/drush/lib/Drush/Boot/DrupalBoot.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error. 
 [error]  Drush was not able to start (bootstrap) Drupal.
Hint: This error can only occur once the database connection has already been successfully initiated, therefore this error generally points to a site configuration issue, and not a problem connecting to the database.
```

### Summary

When trying to use drush on D7 sites I get the above error, I'm using the VM to run a mixture of d7 and d8 sites.

**Comment by chumkui** [comment]
Getting the same, all of a sudden none of my D7 boxes will run:

TASK [Install configured modules with drush.] **********************************
fatal: [symdsvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "pm-enable", "-y", "devel"], "delta": "0:00:01.812695", "end": "2016-11-28 12:16:48.489920", "failed": true, "rc": 255, "start": "2016-11-28 12:16:46.677225", "stderr": "PHP Fatal error:  Class
'Drupal\\user\\Entity\\User' not found in /usr/local/share/drush/lib/Drush/Boot/DrupalBoot.php on line 571\n [error]  Drush command terminated abnormally due to an unrecoverable error.\nError: Class 'Drupal\\user\\Entity\\User' not found in /usr/local/share/drush/lib/Drush
/Boot/DrupalBoot.php, line 571 \n [error]  Drush was not able to start (bootstrap) Drupal.\nHint: This error can only occur once the database connection has already been successfully initiated, therefore this error generally points to a site configuration issue, and not a
problem connecting to the database.\n\nDrush was attempting to connect to: \n drupal-version         :  7.53-dev                         \n drupal-settings-file   :  sites/default/settings.php       \n uri                    :  http://default                   \n db-driver
              :  mysql                            \n db-hostname            :  localhost                        \n db-username            :  drupal                           \n db-password            :  drupal                           \n db-name                :  drupal
                         \n db-port                :                                   \n install-profile        :  standard                         \n db-status              :  Connected                        \n theme                  :  bartik
\n admin-theme            :  seven                            \n php-bin                :  /usr/bin/php                     \n php-os                 :  Linux                            \n php-conf               :  /etc/php/5.6/cli/php.ini         \n drush-script
 :  /usr/local/share/drush/drush.php \n drush-version          :  9.0-dev-g1c91f8b                 \n drush-temp             :  /tmp                             \n drush-conf             :                                   \n drush-alias-files      :
            \n root                   :  /var/www/drupalvm                \n site                   :  sites/default                    \n modules                :  sites/all/modules                \n themes                 :  sites/all/themes                 \n files
             :  sites/default/files              \n temp                   :  /tmp                             \n %paths                 :  /var/www/drupalvm                \n                           sites/default                    \n                           sites/all
/modules                \n                           sites/all/themes                 \n                           sites/default/files              \n                           /tmp                             \n\n ", "stdout": "\nFatal error: Class 'Drupal\\user\\Entity\\
User' not found in /usr/local/share/drush/lib/Drush/Boot/DrupalBoot.php on line 571", "stdout_lines": ["", "Fatal error: Class 'Drupal\\user\\Entity\\User' not found in /usr/local/share/drush/lib/Drush/Boot/DrupalBoot.php on line 571"], "warnings": []}

**Comment by geerlingguy** [comment]
Hmm... this sounds like an upstream Drush issue with 9.x dev—can you try setting `drush_version` to `8.1.7` in your config file and then run `vagrant provision` again? Sometimes using the `master` branch means older Drupal releases get buggy.

**Comment by danharper83** [comment]
It fails to provision with that in the drush version but this may be because I have run composer update inside the drush folder with sudo.

Manually switching to that branch and updating composer worked for me but I had to ssh in and it manually.

Cheers Dan

**Comment by chumkui** [comment]
Hi - all confirmed as a work around for me for Drush v8.1.7.  Works first time.  Many thanks!

**Comment by ryanschmidt** [comment]
I'm having this same issue.

@geerlingguy can you explain "Sometimes using the master branch means older Drupal releases get buggy." I'd prefer to not hardcode the version but if that is indeed the proper way to fix that I'm ok with it. Just wanting to confirm first.

**Comment by geerlingguy** [comment]
@ryanschmidt - For stability, it's best to pick a version and stick to it until you intend to update—e.g. 8.1.7, etc. But you could also stick to the `8.x` branch (instead of a particular release). It would be more stable than 9.x (the dev branch, so to speak), but slightly less stable than an actual release.

Typically, unless you have pretty esoteric needs, any drush version should work for a long time—just update the drush version (within the same major version) any time you do other kinds of updates (core, modules, etc.).

I still have a few Drupal VM instances installing Drush 6.x for various reasons :)

**Comment by ryanschmidt** [comment]
@geerlingguy thanks for the explanation. I was able to get past this with `drush_version: "8.x"`. Would you recommend changing `drush_keep_updated` to false also?

**Comment by geerlingguy** [comment]
@ryanschmidt - You can leave it if you want the latest 8.x branch fixes, otherwise it would be similar to setting a specific tag.

**Comment by jamesan** [comment]
It appears to be due to this commit to drush-ops/drush@f05f484309ba6c8d1b6e689ea9da113a56394c4d. Looks like the Drush 9.x branch is dropping support for Drupal 7.x as the new code requires OOP Drupal (namely the Drupal namespace).

**Comment by geerlingguy** [comment]
@jamesan - Hmm... in that case I might switch Drupal VM to `8.x` instead of `master`, so people on D7 don't have to run through all this.

**Comment by geerlingguy** [comment]
Adding issue reference, too: https://github.com/drush-ops/drush/pull/2458

> The master branch will drop D7 testing with this PR. Someone had to do it :). This opens the way for PRs which remove D7 handling.
