### ISSUE TITLE
Always pass the --working-copy option to drush make

### ISSUE THREAD

**Issue by phenaproxima** [geerlingguy/drupal-vm#104]
The drupal.yml provisioning task is kind of useless if I want drush make to clone working copies of various modules into my site, because it requires the --working-copy argument in order to obey ```working_copy``` flags in the make file. A quick solution to this would be to always support working copies by changing line 16 of provisioning/tasks/drupal.yml from:

```
drush make -y {{ drush_makefile_path }} --no-gitinfofile
```
to
```
drush make -y {{ drush_makefile_path }} --no-gitinfofile --working-copy
```

**Comment by JorisVanEijden** [comment]
This is not my experience.
The example makefile has a `download: working-copy: true` and that is definitely respected.
Worse: it makes drush make always use HEAD, regardless of version.
So changing core: 8.x to 7.x and drupal version 8.0.x to 7.x or 7.37 will still get you a drupal 8.0.x build  :laughing:

**Comment by geerlingguy** [comment]
@phenaproxima - The included example drush makefile demonstrates how you can set the `working-copy` option per-project, and I prefer to keep those kind of options in the make file, rather than as a global for all projects via command line.

If you want a working copy, set the parameter per project in the makefile—otherwise, if you want it for all projects, I think you can even set the option at the root of your makefile.

See, for more specifics, http://drupal.stackexchange.com/a/157844/26

**Comment by JorisVanEijden** [comment]
To be fair, in drush < 7.0.0-rc2 you did need to specify that option on the commandline to have it respected in the makefile. See https://github.com/drush-ops/drush/pull/540

I also filed an issue against drush for the wrong version download with that option: https://github.com/drush-ops/drush/issues/1396
