### ISSUE TITLE
Why remi?

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/drupal-vm#1048]
This is just a generic question, not an issue, but not sure where I should ask, so here we go. Just curious as to why the remi repos are used for CentOS configurations over others (webtatic, EPEL, etc). I've been struggling with which repo should be used in a production environment to upgrade and replace CentOS 7's terribly old PHP 5.4 it ships with. Thanks for any input.

**Comment by geerlingguy** [comment]
@cdmo - Great question!

For starters, when you choose a repo over the built-in version that's supported by Red Hat, you effectively put your trust in that repo's maintainers and their own build toolchains. It's not a decision to take lightly by any means!

I've used EPEL for almost anything under the sun, but EPEL is, like Red Hat itself, a little slower to adopt the latest versions of certain software. And sometimes you can't even get at things like PHP 7 or certain extensions.

[Remi's RPM Repo](https://rpms.remirepo.net) has not only been stable, involved in every major PHP release for years, and works great on multiple Red Hat/CentOS releases... it also has a cute monkey mascot 🐒 !

Plus @remicollet is incredibly active on GitHub, Twitter, etc.

I haven't had as much familiarity with Webtatic, though I would generally trust the people behind that repo as well. I just haven't ever had a problem with Remi's repos, other than the (rare) downtime that goes away after a minute or two.

**Comment by geerlingguy** [comment]
Similar arguments for using @oerdnj's excellent apt repos on the Ubuntu side of things... Though he doesn't have a cute monkey mascot.

**Comment by remicollet** [comment]
@geerlingguy   :)

It looks like @oerdnj needs a mascot ;)

> CentOS 7's terribly old PHP 5.4 

FYI, official Red Hat aswer about this is Software Collections, in which you can find PHP 5.6 and 7.0, so nothing too old ;)  See [Red Hat Software Collections 2.3](https://www.redhat.com/en/about/press-releases/red-hat-software-collections-23-and-red-hat-developer-toolset-6-now-generally-available). This is also avaiable for CentOS in the centos-scl repository (see [SCLo SIG](https://wiki.centos.org/SpecialInterestGroup/SCLo)

BTW, of course my repository will always be faster (have 7.1 for ~6 months when  other only to start to work on it), mostly because it is used as upstream for Fedora / RHEL / CentOS / RHSCL (and lot of 3rd party repo which simply pull my work from Fedora repo)

And you can also compare the list of [available extensions](https://blog.remirepo.net/pages/PECL-extensions-RPM-status) with other 3rd party repository.

**Comment by cdmo** [comment]
Thanks a ton for the quick and thorough answer to noob-ish question! I didn't even know about Red Hat Software Collections.

**Comment by oerdnj** [comment]
Do I? I'll consult my kids then for the logo tips ;).

**Comment by geerlingguy** [comment]
Closing this out as we've had a wonderful side conversation but it's not an issue that needs to remain open :D
