### ISSUE TITLE
PIP install ansible permissions should be validated before recommending using it

### ISSUE THREAD

**Issue by kieranacquia** [geerlingguy/drupal-vm#1082]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

### Summary

I tried installing Vagrant but unfortunately I my Python directory was owned by root so I kept errors with some of the Vagrant dependencies. I even used a new vagrant 1.9.1 dmg to upgrade vagrant but that was insufficient for ensuring PIP could install. Ideally there would some kind of validation step about PIP install permissions so that users could avoid getting trapped like I did. 

This fixed it. 
https://github.com/sindresorhus/weechat-notification-center/issues/1
sudo chown -R $USER /Library/Python/2.7/site-packages/pync did the trick.

This probably seems out of scope but I am big fan of guard rails.

**Comment by geerlingguy** [comment]
@kieranacquia - For the Vagrant install, it should either be done through Homebrew (e.g. `brew cask install vagrant`), or via the DMG download. I haven't seen permissions issues installing Vagrant before.

For pip, if using macOS with nothing else installed, you can install Ansible via Pip with:

```
$ sudo easy_install pip
$ sudo pip install ansible
```

It's not ideal to use sudo in this case, so you can use the above change to install under your regular user account instead... but this discussion seems out of scope for Drupal VM itself, since there are at least four or five different ways you can install Ansible (depending on your system setup)—or you can just leave it off altogether and let it run inside the VM.
