### ISSUE TITLE
How to deploy with from local to remote server with git

### ISSUE THREAD

**Issue by Avalanchaa** [geerlingguy/drupal-vm#1084]
### Issue Type
Support Request

### Your Environment
Vagrant 1.9.1
VirtualBox 5.1.12r112440
-bash: ansible: command not found
```

```

### Your OS

macOS 10.11.6

### Summary
I have deployed D7 to servers without any issue, now with D8, I am receiving autoload.php error when deploying the code.

I also noticed that D8 is installed on drupal/web folder. Whereas in remote server I have a public_html folder. Where should I create the git repository?
/drupal
/drupal/web

As I only have access on remote to /public_html,  I will do a clone. Any suggestion is more than welcome. I am using cloudways with Digital Ocean.

**Comment by oxyc** [comment]
For a simple `git` deploy without any automated steps you should probably use `build_composer` rather than the default `build_composer_project`. http://docs.drupalvm.com/en/latest/deployment/composer/#using-composerjson

This way you can create the git repository in `drupal/` and everything should be contained within that directory (I think, haven't tested this though).

This is definitely not an ideal deployment as it requires you to track `vendor/` in git. Might be worth looking into other options (capistrano, ansistrano).

**Comment by geerlingguy** [comment]
Yeah, this is a much larger question than something strictly Drupal VM-related—there are now at least five or six different strategies you can use to track Drupal 8 projects in git and deploy them.

For simpler sites, I literally download drupal as a tarball (includes the vendor dir), commit everything to git, and deploy that git repo to a server in the docroot (this was what a lot of people did pre-Drupal-8 anyways).

For most sites, I prefer to not track the vendor directory, and have a build system build a 'deployment artifact' then deploy that to the server (this is what Acquia's [BLT](https://github.com/acquia/blt) does).

Another option is to build the site on the live server and cut over to the updated codebase (this is similar to what Capistrano/similar solutions do).

I'm going to close the issue here since it's not something that Drupal VM cares about too much (it's more about running code for your projects and not structuring/deploying them). I would suggest posting questions on Drupal Answers or other more general Drupal forums as you'd likely get a lot more detail in those places.
