### ISSUE TITLE
include xhprof-kit

### ISSUE THREAD

**Issue by YesCT** [geerlingguy/drupal-vm#113]
include https://github.com/LionsAd/xhprof-kit 
and maybe do some of the set up

**Comment by YesCT** [comment]
I have set this up locally, but am a bit stumped on the best way to do it with the vm.

**Comment by geerlingguy** [comment]
@YesCT - I'll take a crack of getting it configured with an Ansible role; a couple bits might be a bit icky (because it looks like there's a lot of "hack this shell script here, and that shell script there"), but I might be able to fork the kit, make things more configurable, then submit a PR to LionsAd's repo so it's more of a "deployable xhprof-kit".

**Comment by geerlingguy** [comment]
I've decided at this time to not add this into the VM directly, but I'd be open to adding documentation for how to add this, maybe in a new 'Drupal contributors guides' section in the Docs.
