### ISSUE TITLE
Add pimpmylog and xhprof to hostsupdater

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#120]
Currently, when you specify a hostname, like _project.dev_, this host is automatically added to /etc/hosts

I would like the same for:

* pimpmylog.hostname
* xhprof.hostname

**Comment by geerlingguy** [comment]
This is likely at odds with #117 - unfortunately, I'm not sure if it will be easy to have it both ways; Ruby can't do the host substitution in any simple way, I don't think. But I'll take a look.

Otherwise, you'll need to manually add the hosts entries to /etc/hosts.

**Comment by geerlingguy** [comment]
I've decided to go back to hardcoding `.drupalvm.dev` in the names; if you need to, you can override those paths by hand in config.yml... otherwise, the common pattern will be to use your normal URLs for all the normal docroots, but `[utility].drupalvm.dev` for all the utilities (Pimp my logs and XHProf for now).

If you run multiple copies of Drupal VM, you'll have to either live with those aliases being switched between the instances whenever your bring up a new one and bring down another, or change them by hand in config.yml.
