### ISSUE TITLE
Error on vagrant up following quickstart directions if old version of ansible is installed

### ISSUE THREAD

**Issue by mlncn** [geerlingguy/drupal-vm#1209]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.0.34r113845
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```

### Your OS

 - **GNU/Linux** Debian Mint — LMDE 2 Cinnamon 64-bit (Cinnamon 3.2.7) — Linux Kernel 3.16.0-4-amd64 — 15.6 GiB RAM

### Summary

Downloaded zip of geerlingguy-drupal-vm-efefdb4, extracted and renamed the folder dvm-portside.

Ran vagrant up.  Got the error "You must update Ansible to at least 2.2 to use this version of Drupal VM."  Full error output below.  As the quickstart instructions don't mention Ansible as a requirement at all, i expect this would work if i didn't have any Ansible installed on my system.  If that's true, i recommend that vagrant up be allowed with an incompatible Ansible if possible, and save this error for when globally installed Ansible must be used.  If Ansible _is_ required, we should add that to the Quickstart instructions.

### Full console output

```
vagrant up
/home/mlncn/Code/dvm-portside/Vagrantfile:137:in `block in <top (required)>': You must update Ansible to at least 2.2 to use this version of Drupal VM. (RuntimeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:107:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:107:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:104:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.rb:104:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:746:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:746:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:492:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:479:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:728:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `<main>'
```

**Comment by geerlingguy** [comment]
@mlncn - Unfortunately, the way Drupal VM is architected, it is opinionated thusly:

  1. If Ansible is installed on the host, then Drupal VM assumes you'd like to use Ansible on the host as this is slightly faster, easier to manage (if you're a power user), and gives a little better control (especially if you consider using Drupal VM for prod or other environments).
  2. If Ansible is not installed on the host, Drupal VM uses the `ansible_local` provisioner.

It's _preferred_ that you install Ansible (and have a reasonably up-to-date version) if at all possible. But there are certain environments where it's tricky, if not impossible (e.g. Windows), so it's just an option.

But Drupal VM does enforce a minimum Ansible version (in this case, 2.2.0 or later)—and the reason for that is there are many small features that are only in 2.2 to power features like more flexible directory and config file scanning.

Luckily, though, there's also an optional variable you can put in `config.yml` to force using Ansible Local (instead of using your host Ansible):

```yaml
force_ansible_local: true
```

If you set that, then Drupal VM will run Ansible inside the VM guest and use whatever is the latest stable version.

I'd only use that option (instead of upgrading your host Ansible version) if it's absolutely essential that you run an older Ansible release on your host, though—otherwise, please upgrade... Ansible is still growing quite a bit, and each point release squashes a _ton_ of bugs!

**Comment by mlncn** [comment]
Thanks for the thorough reply!  I figured i'd have documented the recommended workaround (of course, upgrading Ansible) long before you got to this.

For folks on Debian like me, the way to get, and stay, up-to-date with Ansible is:

http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-debian
