### ISSUE TITLE
Executing Drupal Console commands using vagrant-exec plugin

### ISSUE THREAD

**Issue by heddn** [geerlingguy/drupal-vm#1232]
### Issue Type

 - Feature Idea

### Summary
Executing Drupal Console commands on a project with DrupalVM using vagrant-exec plugin. Not sure how this would effect/break folks that are already doing this type of thing in their Vagrantfile.local, and pointing to a different location. But for all the rest of us, this would be a nice feature.

Inspired by http://jmolivas.com/executing-drupal-console-commands-on-a-project-drupalvm-using-vagrant-exec-plugin

add this type of logic to the Vagrantfile:

```
if Vagrant.has_plugin?('vagrant-exec')
  config.exec.commands '*', directory: '/var/www/drupalvm'
end
```

**Comment by oxyc** [comment]
@geerlingguy actually added this as a doc entry a few days ago https://github.com/geerlingguy/drupal-vm/issues/1215

**Comment by geerlingguy** [comment]
@heddn - Yeah, for now, I'd rather just leave it as a documented capability, and not include inline—my hope is that Drupal Console will fix its `--target` mode so you can still run commands on the host directly on a site in the VM (as well as on any other SSH target), just like you can with Drush—instead of relying on (imo) a hack like this.

See: [Drupal Console remote aliases not working](https://github.com/hechoendrupal/drupal-console/issues/3202).

**Comment by jmolivas** [comment]
I also added a new page to the DC docs about Connecting to a virtual environment => https://docs.drupalconsole.com/en/alias/connecting-to-a-virtual-environment.html
