### ISSUE TITLE
How to restrart PHP

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#1246]
to get working new setting from ```php.ini```.
I use php 5.6. fpm.
```/etc/php/5.6/fpm/php.ini```

**Comment by thom8** [comment]
@ArtuGit you shouldn't edit these files directly and use ansible to provision the change.

`vagrant provision`

**Comment by geerlingguy** [comment]
@ArtuGit Also, if you just want to run a command to restart PHP-FPM, we'd need to know what box you're using (it's different on CentOS vs Ubuntu/Debian). But if using defaults, it would be something like `sudo service php5.6-fpm restart` or `systemctl restart php5.6-fpm` on Ubuntu 16.04.

But as @thom8 suggested, it's best if you let Drupal VM / Ansible manage your ini files; because on the next provision, your hand-made customizations to the file may be overwritten. And when you rebuild the VM from scratch, they would no longer be present.

It's best to configure things through `config.yml` or `local.config.yml` then run `vagrant provision`. You can also specify tags like `php` to only run the PHP-related tasks (so the provision only takes a few seconds instead of minutes).

**Comment by ArtuGit** [comment]
ok.
So if I want to setup `xdebug.profiler_enable_trigger_value = 1` I should add `php_xdebug.profiler_enable_trigger_value = 1`into `local.config.yml`?
How can I add that tag?

**Comment by geerlingguy** [comment]
@ArtuGit - For now, that's not a supported configurable variable, so you would need to manually add/change that variable and restart PHP within the VM.

See: https://github.com/geerlingguy/ansible-role-php-xdebug for a list of all the currently-configurable variables.

It might be best to open an issue upstream if there are some common settings that many people would use that aren't currently configurable.

**Comment by geerlingguy** [comment]
Closing this ticket since it's more related to the upstream role configuration. The original question of how to restart PHP should be resolved (basically `sudo systemctl restart php[version]-fpm` if you're on Ubuntu 16.04 LTS).
