### ISSUE TITLE
Drupal-VM vagrant up hangs on composer create-project

### ISSUE THREAD

**Issue by zetnet** [geerlingguy/drupal-vm#1262]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.2
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** 10 with virtualbox

### Full console output

https://gist.github.com/zetnet/9939a4e31a1e312f47b902570caa51c8

### Summary

The console just hangs on the last line from the gist above
 ( TASK [geerlingguy.drupal : Generate Drupal project with composer package.] ***** )
At this point  the webserver is displaying  in the browser at the drupalvm.dev or dashboard.drupalvm.dev addresses just the  "Apache2 Ubuntu Default Page"

**Comment by zetnet** [comment]
After hitting Ctrl+C this is what happened: 
https://gist.github.com/zetnet/459a208e44e3088acdc3fd2dd656f4ef

**Comment by geerlingguy** [comment]
@zetnet - The extra console output means that Vagrant kept going even after you hit Ctrl-C, and completed the rest of the provisioning.

That particular task (`Generate Drupal project`) will take a super-long time the first time you run it on Windows if you're using all the defaults, because not only is it just a long process in general (it takes a couple minutes on my Mac, in the best of times), but it's also going to take way longer in a VirtualBox synced folder.

If you set the synced folder type to `smb`, it may be a little faster. `rsync` would be faster still, but then the files for the Drupal project would get wiped out next time you boot the VM!

Also, please see all the notes on https://github.com/geerlingguy/drupal-vm/issues/1242 — that's the same issue as this, so closing in favor of the other issue.

**Comment by zetnet** [comment]
Jeff, when I said I was AFK that means more than about half hour.  I came and watched the cmder console doing nothing for about 10 more minutes before hitting CTRL+C and playing in PHPStorm. I have no idea when vagrant  finished provisioning in the console.
Next time I'll try rsync.

**Comment by Razunter** [comment]
It's going for more than 2 hours now. And generating project is disabled in settings. Something is bugged.

**Comment by geerlingguy** [comment]
@Razunter - Can you open a new issue? If there's a new bug, it would be helpful to see all your details (config file, OS, how you have things set up, what is stuck, etc.).

If Ansible is stalling at a particular task, then the playbook is not skipping it. Often that just means there's a variable that's not set correctly.

**Comment by Razunter** [comment]
@geerlingguy I will recheck it later and if it's still same, I'll open new issue. For now, I have all composer-related stuff disabled in config, but it hangs on this task anyway. Latest DrupalVM installed over previous versions. VirtualBox, Windows x64, everything updated. Not SMB/rsync/nfs (they all suck).
