### ISSUE TITLE
DrupalVM seems pretty slow by default

### ISSUE THREAD

**Issue by laurencefass** [geerlingguy/drupal-vm#1264]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
VBox 5
Ansible 2.2
vagrant 1.9.3
```

### Your OS

windows 10

### Summary

after vagrant up/provision the drupalvm.dev seems sluggish. is it optimised with cacheing/memcache/opcode etc by default or do i need to enable all of that? is there a set of recommended optimisations?

comparing this against a drupal docker container installed today which seems to run 5-10 times faster on the same machine running from an Ubuntu docker host...

**Comment by geerlingguy** [comment]
@laurencefass - On Windows, the primary reason is because the default (and safe, but terribly slow) synced folder type is `vboxsf`. See http://docs.drupalvm.com/en/latest/getting-started/installation-windows/#troubleshooting-vagrant-synced-folders (especially the performance section) for more info.

Closing this in favor of more centralized discussion in https://github.com/geerlingguy/drupal-vm/issues/1242
