### ISSUE TITLE
Installation fails, Ansible failed to complete successfully

### ISSUE THREAD

**Issue by vouza** [geerlingguy/drupal-vm#1310]
When "vagrant up" a fresh version of drupalvm I get the following error.

`
Ansible failed to complete successfully
fatal: [www8]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:03.884467", "end": "2017-04-20 13:11:50.284289", "failed": true, "rc": 1, "start": "2017-04-20 13:11:46.399822", "stderr": "Installing drupal-composer/drupal-project (8.x-dev c3cc32161adba046eda1f81fbb19be4390301d53)\n\n                                                             \n  [InvalidArgumentException]                                 \n  Project directory /var/www/drupalvm/drupal/ is not empty.  \n                                                             \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/Volumes/DATA/WORK/MONOKI/WORKSPACE/VAGRANT/vagrant.www8/provisioning/playbook.retry
`

The folder is empty. I have no idea what I should do. 

Thanks
Morris

**Comment by thom8** [comment]
@vouza try deleting the `drupal` directory and running `vagrant provision`

**Comment by vouza** [comment]
i started over ... worked this time.. Thank you

**Comment by sunnyyadav304** [comment]
Hi,

I am facing the below error on vagrant up --provision

![ansible error](https://user-images.githubusercontent.com/71537435/93657900-2436f600-fa54-11ea-9fe3-960652ebc91d.PNG)


TASK [geerlingguy.apache : Check whether certificates defined in vhosts exist.] ***
ok: [drupalvm] => (item={u'extra_parameters': u'ProxyPassMatch ^/(.*\\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/maxxia/docroot"\n', u'servername': u'maxxia.local', u'certificate_file': u'/var/www/drupalvm/d8sslcerts/sslnew.crt', u'certificate_key_file': u'/var/www/drupalvm/d8sslcerts/sslnew.key', u'documentroot': u'/var/www/maxxia/docroot'})
ok: [drupalvm] => (item={u'extra_parameters': u'ProxyPassMatch ^/(.*\\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/maxxia/docroot"\n', u'servername': u'nsw.maxxia.local', u'certificate_file': u'/var/www/drupalvm/d8sslcerts/sslnew.crt', u'certificate_key_file': u'/var/www/drupalvm/d8sslcerts/sslnew.key', u'documentroot': u'/var/www/maxxia/docroot'})
ok: [drupalvm] => (item={u'extra_parameters': u'ProxyPassMatch ^/(.*\\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/maxxia/docroot"\n', u'servername': u'sa.maxxia.local', u'certificate_file': u'/var/www/drupalvm/d8sslcerts/sslnew.crt', u'certificate_key_file': u'/var/www/drupalvm/d8sslcerts/sslnew.key', u'documentroot': u'/var/www/maxxia/docroot'})
ok: [drupalvm] => (item={u'extra_parameters': u'ProxyPassMatch ^/(.*\\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/remserv/docroot"', u'servername': u'remserv.local', u'certificate_file': u'/var/www/drupalvm/d8sslcerts/sslnew.crt', u'certificate_key_file': u'/var/www/drupalvm/d8sslcerts/sslnew.key', u'documentroot': u'/var/www/remserv/docroot'})

TASK [geerlingguy.apache : Add apache vhosts configuration.] *******************
ok: [drupalvm]

TASK [geerlingguy.apache : Add vhost symlink in sites-enabled.] ****************
ok: [drupalvm]

TASK [geerlingguy.apache : Remove default vhost in sites-enabled.] *************
ok: [drupalvm]

TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "Unable to start service apache2: Job for apache2.service failed because the control process exited with error code.\nSee \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\n"}

PLAY RECAP *********************************************************************
drupalvm                   : ok=40   changed=1    unreachable=0    failed=1    skipped=32   rescued=0    ignored=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.


Any help would be highly appreciated. Thank you 👍 
 
Vagrant Version : 2.2.10
virtualbox version : 6.1.12
