### ISSUE TITLE
Provision fails if memcached is not to be installed.

### ISSUE THREAD

**Issue by pbuyle** [geerlingguy/drupal-vm#135]
If memcached is not to be installed, provisioning fail with the following error message:
```
TASK: [geerlingguy.memcached | Install Memcached.] **************************** 
fatal: [drupaldev] => Failed to template {% if "memcached" in installed_extras %} True {% else %} False {% endif %}: an unexpected type error occurred. Error was argument of type 'NoneType' is not iterable

FATAL: all hosts have already failed -- aborting
```

**Comment by geerlingguy** [comment]
@pbuyle - Is you're `installed_extras` variable empty/blank? If you need to remove all the extras, you need to set the variable to:

```yaml
installed_extras: []
```

Otherwise, if you set it to something like `''`, then Ansible won't see it as an array, and since the `memcached` role is the first to use the conditional, Ansible will bail out when it hits that step in the playbook.
