### ISSUE TITLE
Drush 8.x url gives a 404

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#1369]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.12.4

### Full console output

[Full console output](https://gist.github.com/frob/93f3a62db1320f9c3bfe5e65db13b4ed)

TLDR;

```
TASK [geerlingguy.drush : Install Drush.] **************************************
fatal: [oen-ode.local]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drush", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://github.com/drush-ops/drush/releases/download/8.x/drush.phar"}
	to retry, use: --limit @/Users/fanderson/repos/clarity/client/ode/oen/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
oen-ode.local              : ok=128  changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary

My provisioning is hanging when installing drush.

https://github.com/drush-ops/drush/releases/download/8.x/drush.phar is not a valid url.

**Comment by frob** [comment]
I was able to get past this by putting an specific version in the drush_version key in the config.yml

was 8.x
now 8.1.10

**Comment by geerlingguy** [comment]
Was going to mention that, but just noticed you found it on your own; thanks for posting!

**Comment by frob** [comment]
Few things annoy me more than seeing, "Disregard, I fixed it" with no further information.

**Comment by geerlingguy** [comment]
@frob - Also, for the reasoning behind this change, see: https://github.com/geerlingguy/ansible-role-drush/issues/30

Basically, a lot of sites are now installing Drush as a composer dependency, so don't even need Drush as part of Drupal VM (since it's part of their codebase)... and for those who do want Drush installed globally, it's about 1 minute faster (20s total instead of about 00:01:20s) to install the `.phar` instead of 'building from source' from GitHub.

Though you can still switch back to the old technique if required using `drush_install_from_source`.

**Comment by heddn** [comment]
For D6, you *must* `drush_install_from_source: yes`. There isn't a phar file of drush 7.x.

**Comment by ronezone** [comment]
Perhaps adding a comment to the `default.config.yml` would save a lot of people time and angst:

`# Pre 8.x.x versions of drush must install from source because no .phar file`
`drush_install_from_source: yes`
`#drush_version: "8.1.10"`
`drush_version: "6.2.0"`

--
ALSO, installing Drush-6.2.0 required me to manually download the following library in order to function:   `http://download.pear.php.net/package/Console_Table-1.1.3.tgz`

I had to `vagrant ssh` in order to see the `/usr/local/share/drush/lib/` directory.  I also had to prepend `sudo` to all commands due to need for root permissions:

`vagrant@`_mydomain_`:/var/www/drupalvm/drupal/web$ `**`sudo mv Console_Table-1.1.3.tar /usr/local/share/drush/lib/.`**
`vagrant@`_mydomain_`:/usr/local/share/drush/lib$ `**`sudo tar xvf Console_Table-1.1.3.tar`**
`package.xml`
`Console_Table-1.1.3/tests/assoziative_arrays.phpt`
`Console_Table-1.1.3/tests/colors.phpt`
`Console_Table-1.1.3/tests/filters.phpt`
`Console_Table-1.1.3/tests/multibyte.phpt`
`Console_Table-1.1.3/tests/multiline.phpt`
`Console_Table-1.1.3/tests/no_header.phpt`
`Console_Table-1.1.3/tests/no_rows.phpt`
`Console_Table-1.1.3/tests/rules.phpt`
`Console_Table-1.1.3/Table.php`
