### ISSUE TITLE
Does a snapshot backup the database files/tables?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#1397]
### Issue Type

Support Request

### Your OS
Windows 10

### Summary
Does a snapshot backup my mysql database and the tables within it?
If my database crashes can I restore it by doing a rollback (snapshot pop)? Is there any other way?

**Comment by geerlingguy** [comment]
Snapshots using `vagrant snapshot` (docs: https://www.vagrantup.com/docs/cli/snapshot.html) would back up the entire state of a machine at some point in time. I don't particularly use this feature, but did in the past and it seemed to work as expected.

It _should_ roll back to whatever the state of the database was when you took the snapshot, but as with any feature, I'd test once to verify that's happening. Take a snapshot, then add a node or something, then roll back to that snapshot and verify the node is no longer present in the database.

Note that snapshots don't change the contents of any shared folders (since those are on the host system).
