### ISSUE TITLE
Using a template for sites/default/settings.php

### ISSUE THREAD

**Issue by gheydon** [geerlingguy/drupal-vm#1417]
### Issue Type

 - Bug Report / Support Request
 - Feature Idea

### Your OS

 - **macOS** 10.11

### Summary

Is there a way of adding a template for sites/default/settings.php.

I am using composer to attach the development environment to an existing project and it runs very well. We do not have the sites/default/settings.php in the repository and would like it if I could add something like

```
drupal_settings_php_template: settings/settings.php.js
drupal_settings_php_path: sites/default
```

This will then use this as a template and copy it the path required. For the path you could even do something like "sites/{{ vagrant_hostname }}" and the directory will get created and populated.

Thanks
Gordon.

**Comment by geerlingguy** [comment]
@gheydon - Thanks for posting the issue!

I'd rather defer settings.php management to either Drush/Drupal (as is the case when installing a new site), or to your own deployment/provisioning setup. Since settings.php can be used in a dizzying array of different ways, I'd rather not try to make Drupal VM be able to work with a templated version.

I've done this in the past for very specific Drupal configurations in other projects (e.g. https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/playbooks/drupal/templates/settings.php.j2)—but it's a bear to maintain, and hard to generalize.

For most projects, I recommend having a general `settings.php` that includes either a secrets/credentials include file on production/other environments, and a `local.settings.php` when developing locally. The `local.settings.php` should be gitignored, and each member of the development team would then control their own `local.settings.php` file (so they could, if they wanted, change connection details or other settings to have a different environment altogether).

This is also the pattern that [Acquia's BLT](https://github.com/acquia/blt) uses—though in BLT's case, it's fully automated.
