### ISSUE TITLE
Subdomain ALL THE THINGS!

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#143]
Use subdomains conventions instead of paths.

A couple come to mind:

- [ ] Solr
- [x] Adminer
- [ ] Mailhog

**Comment by nerdstein** [comment]
Add mailhog to the list :)

**Comment by geerlingguy** [comment]
Currently, to access these services, respectively, you visit:

Service | Access URL
----- | -----
Adminer | `http://{{ vagrant_hostname }}/adminer`
MailHog | `http://{{ vagrant_hostname }}:8025/`
PimpMyLog | `http://pimpmylog.{{ vagrant_hostname }}/`
Solr | `http://{{ vagrant_hostname }}:8983/solr/`
XHProf | `http://xhprof.{{ vagrant_hostname }}/`

**Comment by geerlingguy** [comment]
Closing this and redirecting all effort towards PR #184 :)

**Comment by geerlingguy** [comment]
Reopening, because scope of this issue is a little wider—subdomaining ALL the things, not just some.

**Comment by geerlingguy** [comment]
Just fixed another—Adminer is now at `adminer.drupalvm.dev`, per #251

**Comment by frob** [comment]
Would it make more sense to have this defined more globally? So instead of having a bunch of duplication for all these additional sub-domains we could just define a couple of things that the rest would be inferred?

For example. Every project should have a baseline of things defined. In my experience this is normally:

 - client (or group)
 - project name
 - extra vhosts

So for a simple Drupal REST project with an extra html app front-end, we would define it like this:

```yaml
group: client-name
project: rest-api
extra-vhosts:
 - app
```

This would give use the things

 - rest-api.client-name.dev -> Drupal
 - app.rest-api.client-name.dev -> html app
 - *.rest-api.client-name.dev -> All the things.

More information would be required for directory name info and such, but this would remove much of the complexity that Drupal-vm currently has when creating projects.

**Comment by geerlingguy** [comment]
I think that now that we have #320 in place, I'm happy with how that works in terms of exposing the service URLs to the VM end-user.

No need to overcomplicate the subdomainification of things like mailhog or solr, which would require yet more vhosts to be added in.
