### ISSUE TITLE
Stuck at task "Install configured modules with drush."

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1461]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
```

### Your OS
 - **macOS** (el capitan)

### Full console output
https://gist.github.com/betz/4dff0025fc7e4db3800b8baa232b8cb2

### Summary
A provision always gets stuck at the task "Install configured modules with drush".
This for local provisioning thru vagrant, as to a production env with ansible-playbook.
It just waits for X hours without any reaction.
What could be wrong here?

**Comment by betz** [comment]
I got a response from one local environment, this is one of the errors:
https://gist.github.com/betz/270616d42d2076b3eae127429cf40426

**Comment by geerlingguy** [comment]
Hmm... that task uses `drush pm-enable`, not download or update, so what I'm guessing is happening is you have a module in the `drupal_enable_modules` list that isn't already part of your Drupal codebase, and Drush is bailing out because it realizes you _don't_ have the module, but you should be downloading the missing module using Composer.

The best fix would be to add all modules that you want to enable to the `drupal_composer_dependencies` list so that Composer downloads all the code and dependencies _prior_ to the site installation.

Let me know if that doesn't help—test builds seem to be working fine with a few of my own modules for testing.

**Comment by betz** [comment]
This was indeed a fix. Thanks.
