### ISSUE TITLE
Composer require as make replacement question 

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1465]
### Issue Type
 - Bug Report / Support Request

### Summary
As I would want to use composer instead of make, I have some reqs I still have no solution for:

- custom location: as an example, custom modules should go in /modules/custom.
I could achieve this by updating the type to drupal-custom-module in composer.json file in that module. But this should be nice to override in the projects drupal.composer.json. A possible different path in each project.

- leave .git folder within module. I tried setting "preferred-install": "source" in the config in drupal.composer.json, but does not seem to work. Would be handy for development.

**Comment by geerlingguy** [comment]
These both seem to be very Composer-specific, and besides allowing _all_ custom modules to be in a place like `modules/custom`, I'm not sure how you'd do it any other way.

For the .git folders... that sounds like it might be a bug in Composer or a misconfiguration somewhere. I'd recommend asking on Drupal Answers, or maybe even in the Composer issue queue (or Drupal Composer Project template). But I'll leave this issue open for now in case anyone else has hit these things directly and has a better answer.

**Comment by oxyc** [comment]
You can use https://github.com/Koodimonni/Composer-Dropin-Installer for moving some packages to other locations.

**Comment by betz** [comment]
> besides allowing all custom modules to be in a place like modules/custom, I'm not sure how you'd do it any other way.
My custom might be your contrib. If we publish to packagist, someone else will would a module to be winhin contrib, not custom.

**Comment by oxyc** [comment]
I would classify a module as `contrib` as soon as it's moved to it's own repo and _contributed_ to the public, regardless if it's packagist, d.o., or just github. `custom/` are modules I edit directly, without pushing to any other repo.

I do get your point about semantics though :) But then the problem becomes, where do you draw the line? Should Jeff place Honeypot in `custom/` because he built it? etc.

Anyways, I'll close this as your questions were partly answered and it's been 2 weeks without input. If you're still looking for support, I bet people on Drupal Answers have more ideas.
