### ISSUE TITLE
feature request - add option for database gui

### ISSUE THREAD

**Issue by John-B** [geerlingguy/drupal-vm#148]
The whole install is painless for the inexperienced user on Windows, so thanks for that. The only glitches were that the Quick Start Guide does not mention the need to edit the values of sh.path and sh.args in the Vagrant file; and that vagrant-hostsupdater does not work for me on Windows 7.

Getting phpmyadmin working from within the VM using https://github.com/geerlingguy/ansible-role-phpmyadmin on Windows is not so simple for someone new to Ansible, and I gave up and installed it manually. Including optional setup of phpmyadmin or some similar db visualisation tool in the main playbook may help new users.

**Comment by kevinquillen** [comment]
Why not just use something like HeidiSQL client?

**Comment by geerlingguy** [comment]
@John-B @kevinquillen - I tossed out phpMyAdmin in favor of [Adminer](http://www.adminer.org/), a much nicer/simpler/easier to use MySQL GUI.

Just make sure `adminer` is in the list of `installed_extras`, and you can access it at `http://drupalvm.dev/adminer` (assuming you have default URL configured—otherwise replace `drupalvm.dev` with the URL for your VM instance.

**Comment by John-B** [comment]
Thanks.
