### ISSUE TITLE
Uninstall completely Drupal VM

### ISSUE THREAD

**Issue by dademiller** [geerlingguy/drupal-vm#1486]
Complete uninstall of Drupal VM

 - Documentation Report

Vagrant 1.9.7
V-Box 5.1.22r115126
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

MacOS - 10.12.5 (16F73)

I am trying different things and I would like to know exactly where and what is modified in my system to let drupal VM work, for example:
Ubuntu where is downloaded and keeped?
Drupal where is downloaded and keeped?

are there any files in my system modified?

I'm asking it also because I can't completely reset my machine, when I do `vagrant destroy` and I rebuild my machine with `vagrant up`,  if I connect to it (by virtualbox or directly from ssh) the folders that I created in the precedent session are still there. 

Thanks

**Comment by geerlingguy** [comment]
@dademiller - Since Drupal VM only operates inside VMs, everything is managed by Vagrant and VirtualBox (or Docker, or some other VM provider if you're using one).

If you run `vagrant destroy`, it tears down/removes any and all Drupal VM instance files (usually stored in a hidden directory in your user home folder).

However, `destroy` does not delete any files or folders on your host machine that are shared inside Drupal VM.

By default, the Drupal VM directory itself is shared into Drupal VM, and then Drupal is installed inside the Drupal VM directory. To clear that out, you can delete the contents of the `drupal` directory inside the Drupal VM directory on your host (after running `vagrant destroy`).

Outside of whatever you have configured inside the shared folders in your `config.yml`, Drupal VM doesn't put any files anywhere outside the VM itself.

Hopefully that's helpful!
