### ISSUE TITLE
[feature] Drupal site installs with Drupal Console

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#1502]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 1.9.6
VirtualBox 5.1.22r115126
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### Your OS

 - **macOS** (10.12.6)

### Full console output

n/a

### Summary

Seeing as there is support here for composer installs and drush installs, it makes sense to me to offer site-install from the drupal-console application. Because I'm not fully supportive of composer due to all the dependency hell cases I keep hearing about I'm rather likely going to adopt Drupal Console for building, managing and maintaining sites - but I feel I may not be the only one...

See more:
https://drupalconsole.com/articles/how-to-download-and-install-drupal-8-using-drupal-console

**Comment by geerlingguy** [comment]
> Because I'm not fully supportive of composer due to all the dependency hell cases I keep hearing about I'm rather likely going to adopt Drupal Console for building, managing and maintaining sites

Note that the dependency hell is pretty much unavoidable for a large (and growing) number of contributed modules. Basically, any module that has dependencies will need a _lot_ of handholding and code wrangling to try to get it to work with your site if you _don't_ use Composer :)

I'm going to close this as 'wontfix' for now, just because if you want to use Console to install a Drupal site, you may do so manually. Most of the time when I've grown to rely on something in Console, it requires a bit of extra maintenance vs. say Drush, which has used the same `site-install` command args and structure for at least 5+ years now...

If it seems more and more people start using Console for site installs, I'll reconsider, but at this time it's not a pattern I've noticed much.

**Comment by oxyc** [comment]
I'm guessing maintenance will be easier now that Drupal Console hit the first stable release.
