### ISSUE TITLE
Apache2 error: "Premature end of script headers: index.php"

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1517]
On one project, I've been getting this error on a stock DrupalVM instance (using the config file from BLT):
"Premature end of script headers: index.php"

The "fix" was to switch to mod_php. I have no idea what the root cause is here. My guess based on Googling is that it's something related to mod_deflate and/or empty buffers.

**Comment by leewbutler** [comment]
Hi @danepowell, I had a similar issue with a very large node form that causes the same error -
 using DrupalVM within BLT. 

In case anyone else stumbles upon this issue + post, here's the relevant configs I add to BLT's "box/config.yml" file. Potential gotcha note: at the time of this writing PHP 5.6 is still being used in the BLT + DrupalVM setup so the follow  "drupalvm configs fix" contain "libapache2-mod-php5.6" as opposed to "libapache2-mod-php7.x".

# ---
# FIX: Switch from use of "Apache php_fpm" to "Apache mod_php".
# ---
# Note this fix is for a "dev environment" issue only. The issue is unclear as log
# files are sparse on related output but likely relates to "php_fpm" and "mod_deflate"
# having "empty buffers". Disabling mod_deflate does not fix it. Switching from "php_fpm"
# to "mod_php" has proven to be the only thing that fixes it. To do this, the following two
# fix configs override some DrupalVM defaults established in the default VM config file at:
#      FILE: vendor/geerlingguy/drupalvm/default.config
# and are made per these instructions:
#      URL: http://docs.drupalvm.com/en/latest/other/bigpipe/#apache-configuration

# FIX - PART 1) Override "extra_packages" in order to add the package "libapache2-mod-php5.6"
extra_packages:
  - sqlite
  - libapache2-mod-php5.6

# FIX - PART 2) Override "apache_vhosts" config in order to remove default "extra_parameters" for "php_fpm"
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
