### ISSUE TITLE
Failed to download key at http://repo.varnish-cache.org/debian/GPG-key.txt

### ISSUE THREAD

**Issue by stephencross** [geerlingguy/drupal-vm#1542]
### Issue Type
 - Bug Report / Support Request
### Your Environment

Vagrant 1.9.1
VirtualBox 5.1.18r114002
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides

### Your OS

Max OSX 10.12.6

### Full console output

https://gist.github.com/stephencross/eff34647cf478b99fc23b1509555a4c4

### Summary

When provisioning, getting error:

fatal: [atfweb]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at http://repo.varnish-cache.org/debian/GPG-key.txt: HTTP Error 410: repo"}
	to retry, use: --limit @/Users/stephencross/Documents/dev/atfweb/box/provisioning/playbook.retry

**Comment by geerlingguy** [comment]
@stephencross - It looks like you may be running an older version of Drupal VM; the recent versions have been using Varnish's new packagecloud repositories; see: https://github.com/geerlingguy/ansible-role-varnish/blob/master/tasks/setup-Debian.yml#L7-L10

This was fixed in https://github.com/geerlingguy/drupal-vm/issues/1455 a few months ago.

It should start working correctly if you update your version of Drupal VM.

**Comment by stephencross** [comment]
@geerlingguy Thanks.  I successfully upgrade to the latest version.
