### ISSUE TITLE
update deployed URL in doc

### ISSUE THREAD

**Issue by alpapan** [geerlingguy/drupal-vm#1569]
The URL in the README is drupalvm.test but the current version now serves at drupalvn.dev (as correctly notified by the vagrant file)

thanks!

**Comment by oxyc** [comment]
It's a bit unfortunate but the current README on GitHub always points the the development branch rather than the current stable release. I think I read @geerlingguy comment on this somewhere and back then he wasn't really into switching the git workflow model as even if the current model has it's shortcomings, it's far simpler to maintain.

**Comment by geerlingguy** [comment]
Yeah, sorry about that! I'll be creating a release very soon: https://github.com/geerlingguy/drupal-vm/issues/1573
