### ISSUE TITLE
Autoload.php error in server environment

### ISSUE THREAD

**Issue by kwlester** [geerlingguy/drupal-vm#1578]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.20r114629
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### Your OS

 - **macOS** (10.12.6)

### Summary

I'm getting the following error in my server environment:
```

Warning: require(/nfs/c11/h04/mnt/###/domains/sitename.org/html/../vendor/autoload.php): failed to open stream: No such file or directory in /nfs/c11/h04/mnt/###/domains/sitename.org/html/autoload.php on line 17

Fatal error: require(): Failed opening required '/nfs/c11/h04/mnt/###/domains/sitename.org/html/../vendor/autoload.php' (include_path='.:/usr/local/php-5.6.21/share/pear') in /nfs/c11/h04/mnt/numbers/###/sitename.org/html/autoload.php on line 17
```

I understand that the autoload.php file inside of the web directory is trying to call the autoload.php file a level above the web directory, but the web directory is my git repo. I had this issue after a fresh drupalvm install. I solved it by deleting the web directory installed by drupalvm and downloading a fresh install from drupal.org. 

Everything worked perfectly until I ran `composer update`. Now it's looking for that same file. Are the files outside of the web directory necessary in my sever environment? Should my git repo encompass the entire drupal directory rather than the web directory?

**Comment by tommym9** [comment]
I bumped into the same issue, but I am keeping my vendor directory inside my repo for these reasons: https://www.codeenigma.com/build/blog/do-you-really-need-composer-production

As such I amended the autoload.php to look for the vendor directory in the doc root (same level as core, sites, modules, etc) instead of above it.

Looking at the Drupal autoload.php that comes with the Drupal core download from d.o it is expecting the vendor directory to be in the doc root so I'm assuming this is a Drupal VM thing?

Cheers

Tom

**Comment by joestewart** [comment]
@tommym9 It's using Option A - https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies

https://github.com/drupal-composer/drupal-project

**Comment by tommym9** [comment]
@joestewart Thanks for that Joe. Makes sense to me now.

@kwlester If you use: https://github.com/drupal-composer/drupal-project to create your project and then sync that to the /var/www/drupalvm/ folder so that there is the following directory structure:

/var/www/drupalvm/
/var/www/drupalvm/drupal
/var/www/drupalvm/drupal/web

Then the autoload issue will be resolved.  

Cheers

Tom

**Comment by oxyc** [comment]
As there's been no response and @tommym9 solved his issue I'm going to assume you both had the same cause. @kwlester if you're still having issues, please let us know and we'll reopen the issue.
