### ISSUE TITLE
NFS error on WSL

### ISSUE THREAD

**Issue by skippednote** [geerlingguy/drupal-vm#1611]
Hi. I'm trying out DrupalVM on Windows 10 WSL. Whenever I run `blt vm` or `vagrant up` I get the following error:

```
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

I installed `nfs-server` but that doesn't help. Is there anything else I can do to remedy this?

**Comment by FinBoWa** [comment]
Maybe review these http://docs.drupalvm.com/en/latest/getting-started/installation-windows/ ?

**Comment by skippednote** [comment]
@FinBoWa I did review the documentation but this isn't covered anywhere.

Something to note, I've vagrant installed inside WSL not on windows as suggested by https://www.vagrantup.com/docs/other/wsl.html.

**Comment by FinBoWa** [comment]
Personally haven't had the need to run nfs on windows (yay) afaik it has issues. 

With this https://www.jeffgeerling.com/blog/2017/use-drupal-8-blt-project-drupal-vm-on-windows-7-or-windows-8 seems not to use nfs rather the default share.

But this might have some tips: https://www.youtube.com/watch?v=VBvPw-b9pe8

**Comment by FinBoWa** [comment]
As you are using it with BLT it has this https://github.com/acquia/blt/blob/9.1.x/readme/windows-install.md#using-drupal-vm

And that points out "The Windows Subsystem for Linux isn't a full-fledged Linux operating system, rather an environment for running Linux apps that would normally run on Ubuntu 14.04. Therefore, VirtualBox can't be installed in the WSL, and it's unlikely Vagrant usage will be supported—though you can install Vagrant in the WSL, using dpkg -i to install the latest Vagrant .deb package download."

**Comment by geerlingguy** [comment]
@skippednote - I haven't yet spent the time to find a way to get everything working/bootable directly through WSL, so still recommend using Cmder or some other terminal emulator with Vagrant / Windows directly rather than through the WSL bridge.

That is, unless you'd like to spend the time figuring out all the little weird bits and documenting them in a blog post :)

If you can live with it, setting the share type to `''` instead of `'nfs'` should _probably_ make things work. NFS in Windows 10 can be difficult to get working correctly, and is often a source of weird bugs. And remember that even if vagrant can be called from WSL, it's running under Windows, but there can be strange things that happen with `vagrant.exe` when using the WSL cli instead of a more native Windows cli.

**Comment by geerlingguy** [comment]
Closing in favor of https://github.com/geerlingguy/drupal-vm/issues/1012, just to keep notes and progress centralized in that issue.

**Comment by skippednote** [comment]
Quick update here, after changing type to `''` or `rsync` it still is throwing the same error for me.

**Comment by bits-of-static** [comment]
I use Mingw64(== git console), not WSL, but this issue on Windows seems rather rare so I am nothing it down over here: I experienced this after upgrading Vagrant to 2.2.14. I remembered I had this already with upgrade to 2.2.10.

Downgrading to 2.2.9 (= last Vagrant version which worked for me) resolved the issue. Have not found anything else helpful on the way.

My current system combination is Windows 10 (WSL2 enabled), VirtualBox 6.1.16.
