### ISSUE TITLE
Docker plus Drupal VM context use

### ISSUE THREAD

**Issue by visages** [geerlingguy/drupal-vm#1613]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 2.0.1
VirtualBox 5.2.0r118431
No Ansible
Docker Toolbox
Docker version 17.10.0-ce, build f4ffd25
docker-machine.exe version 0.13.0, build 9ba6da9
```

### Your OS

 - **Windows** (7 SP1 with WMF 5.1)

### Full console output
```
$ docker-machine create --driver virtualbox drupalvm
$ docker-machine env drupalvm
$ eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env drupalvm)
$ docker run -d -p 80:80 -p 443:443 --name=drupalvm --privileged -it geerlingguy/drupal-vm
$ docker exec drupalvm install-drupal 7.56
$ docker exec -it drupalvm sh
```
### Summary

As pasted above, I could create a machine and run  `geerlingguy/drupal-vm` as container, then install successfully a drupal site, ssh into the container...

This is a simple question for Docker newbie, trying that alternative. In which development context this should better be (or not) used ? 
What I see is at the moment : 
- Deploying is blazingly fast
- I couldn't visit the website on the default IP or hostname (192.168.89.89  drupalvm.test) (I did edited my hosts file)
- when I ssh into the container I see that this seems to be a very lightweight distro, for instance `vim `nor `nano `installed. Also typing anything but characters return unexpected chars, I'd have to fix them one by one with `stty erase`
- This workflow didn't download the box to an editable place, or I could't find it. Then no customization. I suppose I'd had to use pull method instead

Is there an approach who'd make use of docker + DrupalVM somehow similar to Vagrant method (customize your guest i.e with Varnish, Nginx..., define your shared directories )?

Thank you for your patience and amazing boxes.

**Comment by geerlingguy** [comment]
Haven't had time to fully digest this issue request, but one quick note—I don't like (and won't offer much support for) Docker Machine—it causes a lot of weird and annoying problems in real world use, and I avoided using Docker locally at all until Docker for Mac and Docker for Windows was introduced.

I'd heavily recommend using the official client if at all possible (though I'm not sure if it's even available for Windows 7...?), because a lot of issues go away when doing that—plus I've actually tested under Docker for Windows. Running Docker inside VirtualBox makes networking, shared filesystems, and other things break in ways that I'm not sure are easily fixable for a machine as complex as Drupal VM...

**Comment by visages** [comment]
Thanks a lot for your answer and these tips. Indeed there's a bunch of .exe utilities to install an run Docker in Win 7, shipped with [Docker Toolbox ](https://docs.docker.com/toolbox/overview/)... but as always in Windows, nothing is straight... 
I'll leave that for the moment and stick on Vagrant VM dev machines ;)
Greetings  and lots of good things for next year !
