### ISSUE TITLE
Install fails on Apache 2.9.4 due to a Key issue

### ISSUE THREAD

**Issue by chumkui** [geerlingguy/drupal-vm#1646]
### Issue Type

 - Bug Report / Support Request
 
### Your Environment

  - **Windows** (10 Pro 10.0.16299)
 
### Full console output

https://gist.github.com/chumkui/88f3b62c79ac00920078ac65da03f0b2

### Summary

Did a rebuild today and it failed when installing Apache 2.4 - it has previously been working fine.  I have not seen this error before.

**Comment by chumkui** [comment]
OK - I managed to get around this by manually installing the key first - I ssh'd into the machine and ran:
sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

The key installs fine, but does not using the DVM installer:
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

Not an area of expertise for me, but I am at least up and running again. As far as I am aware there are no firewall issues.

**Comment by geerlingguy** [comment]
I haven't seen this issue elsewhere and can't reproduce it locally, so I'm wondering if it might've also been a temporary issue with the upstream packages.

Since you have a workaround (manually adding the key), I think that should suffice if this happens again; if you have it happen again (same error(s)), please post another issue and we'll take a deeper look.
