### ISSUE TITLE
Minimum Ansible version is too low

### ISSUE THREAD

**Issue by marcaddeo** [geerlingguy/drupal-vm#1701]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.1.24r117012
ansible 2.2.2.0 (Already updated to `2.4.3.0` so I dont have the full output, sorry)
```

### Your OS

 - **macOS** (High Sierra)

### Full console output

Dont have the full output, this is the failing TASK though:
```
TASK [geerlingguy.git : Ensure git's dependencies are installed (RedHat).] *****
fatal: [default]: FAILED! => {"failed": true, "msg": "'git_install_from_source_dependencies' is undefined"}
```

### Summary

It seems that the `geerlingguy.git` role somehow has a requirement on Ansible `2.4.3.0` (or at least higher than `2.2.2.0`) in order to successfully process the variables used within the role.

Had some strange behavior:
1. We're running Ubuntu, and it's trying to run RedHat related tasks
2. `git_install_from_source` is not set, and per the role defaults to `false`

After upgrading, it worked perfectly. I've also given some feedback [here](https://github.com/geerlingguy/ansible-role-git/issues/34) where the issue is being reported.

I'd suggest incrementing the minimum Ansible version in the default config file, or maybe `geerlingguy.git` can be refactored to work with `2.2`+

**Comment by nathandentzau** [comment]
![24vliq](https://user-images.githubusercontent.com/15371196/36392163-0120b2aa-1578-11e8-8066-1074817d5a77.jpg)

**Comment by fubarhouse** [comment]
I actively use Ansible 2.4.0.0, there have been some regressions that break compatibility for some of the stuff I've layered on top. I wouldn't recommend using anything higher than 2.4.0.0.

I was the one who collaborated with @geerlingguy for that particular feature. If it isn't compatible with Ansible 2.2 - and I don't know if it is because I don't use it, I can however vouch for v2.4.0.0 as I use it daily.

By doing this, it would also provide an upgrade path to solve #1553.

**Comment by geerlingguy** [comment]
I'm using 2.4.3.0, with no issues—also 2.2 should still be the minimum compatible version for all of Drupal VM. So far I'm not updating all my roles to 2.4+ (I won't do that until 2.5 is released)...

**Comment by geerlingguy** [comment]
This file contains all the logic that defines the default vars: https://github.com/geerlingguy/ansible-role-git/blob/e00e714663ca482384c7980596705b7bf8ad9491/tasks/install-from-source.yml

Ah... but I wonder if this change may have caused issues in a few versions of Ansible: https://github.com/geerlingguy/ansible-role-git/commit/ead753560f51e9415c8aa1b19b818881dd4e1b88#diff-408b14fc5cdd582965ea5d0aa0379e12

I had to make the change because on 2.4+ there were multiple weird issues without using the `rc`. But the `rc` _should_ be set even on older Ansible versions :/

**Comment by geerlingguy** [comment]
I will be bumping the version to 2.4.0+ since I've now bumped the Git role to that requirement. Easier than spending many more hours trying to find a weird incantation that works with Ansible 2.2, 2.3, and 2.4 for the ever-changing return value of a command :)

**Comment by geerlingguy** [comment]
Commit incoming...
