### ISSUE TITLE
Vagrant hanging at "SSH auth method: private key"

### ISSUE THREAD

**Issue by justclint** [geerlingguy/drupal-vm#1713]
### Issue Type
- Support Request

### Your Environment
```
Vagrant 2.0.2
VirtualBox 5.2.8r121009
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

### Your OS
- Ubuntu 17.10

### Full console output
The following gist has results for both `blt vm` and `vagrant up`
https://gist.github.com/justclint/52203d73c4aa7af25c5df5c586e26708

### Summary
We're using BLT and when trying to create or run vm it hangs at ssh auth. We have this same project working on osx and other ubuntu 16. This is our first attempt setting up on ubuntu 17.

**Comment by geerlingguy** [comment]
There's a chance there might be some incompatibility with Ubuntu 17.x and the current version of Vagrant and/or VirtualBox. 99% of the time when using the latest non-LTS release of Ubuntu it seems there's something there, or it could also be a networking issue.

Is the 17.x box running through a proxy or firewall that the other ones aren't? Does it use a VPN?

I would suggest looking in the Vagrant issue queues on GitHub to see if there's an open issue for this, e.g. a quick search found at least https://github.com/hashicorp/vagrant/issues/9488; not sure if the box is the issue, but it could be.

As it is, I can only support the LTS releases as host OSes because there are frequently tons of issues with non-LTS releases and I only have so much time in the day :(

**Comment by justclint** [comment]
Thanks @geerlingguy ! Totally understandable. I was just giving this machine with 17 already installed but im just going to reinstall 16. Thanks!
