### ISSUE TITLE
Known issues with Beetbox?

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1746]
### Issue Type

 - Documentation Report

### Summary

Is there any place (such as a wiki page or in-line documentation) where we can see a list of known issues and/or discussion around Beetbox?

We've started to use it recently because it's marginally faster to provision than the standard Ubuntu base images, but we've also encountered some bugs such as https://github.com/beetboxvm/beetbox/issues/469

In general, it just feels somewhat less stable than the standard Ubuntu bases and it would be nice to quantify the issues and be able to reasonably guide new users on making the right choice for their project.

**Comment by geerlingguy** [comment]
> Is there any place (such as a wiki page or in-line documentation) where we can see a list of known issues and/or discussion around Beetbox?

I would direct any Beetbox feedback to the Beetbox issue queue: https://github.com/beetboxvm/beetbox

Note that it is built on top of Drupal VM but is technically not affiliated in any official manner. For my purposes, I maintain an extremely generic base box that has Ubuntu minimal server install, then I build fresh on top of it (Drupal VM, and hundreds of other Vagrant configs).

Beetbox takes almost the opposite approach of prebundling almost everything, and rebuilding the base box frequently with new stuff on top.

But due to the nature of software (everything changes all the time...) it's a lot harder to guarantee a less generic base box will work in all the complex situations you might have (e.g. with a BLT project).

Closing this issue as I don't want to provide Beetbox support in the Drupal VM issue queues or help docs.

**Comment by danepowell** [comment]
Yeah I totally get that you shouldn't have to provide support for something you don't own. I was just thinking it would be nice to have a central point of reference to help guide people in choosing a base box. "Here's what DrupalVM supports / recommends, things to consider when choosing a base box, and known issues for each"
