### ISSUE TITLE
Drush 9 alias confusion (and pantheon aliases)

### ISSUE THREAD

**Issue by RodenHirata** [geerlingguy/drupal-vm#1756]
### Issue Type
 - Bug Report / Support Request
### Your Environment
```
Vagrant 2.0.4
```
### Your OS
 - **Windows** 10

### Summary
I try to work things out myself most of the time, but a little confused so making my first issue here! Last year I used Drupal VM with Drush set to 8.1.10 in config.yml and as far as I can remember, I could use the pantheon aliases (which download automatically to /.drush in home after typing "terminus aliases") straight after typing drush cc drush. It seemed to work great! 

My old VM is gone now and I'm not having much luck with this new version. Only the Drupal VM aliases are displayed when I type "drush sa". I noticed the drush version on the Pantheon server by default is on 8.1.16 which might be an indicator of something... The alias file they provided looks like this:

  $aliases['site.dev'] = array(
    'uri' => 'dev-site.pantheonsite.io',
    'db-url' => 'mysql://<address here>$
    'db-allows-remote' => TRUE,
    'remote-host' => 'appserver.dev.<address here>',
    'remote-user' => 'dev.<stuff here>',
    'ssh-options' => '-p 2222 -o "AddressFamily inet"',
    'path-aliases' => array(
      '%files' => 'code/sites/default/files',
      '%drush-script' => 'drush',
     ),

I noticed in the /.drush folder there is a sites folder with a drupalvm,site.yml file in it - not sure I remember that last time. There is a 'root' setting but I don't know what that would be for a pantheon server. So basically, any idea on how to get these pantheon aliases working? 

Or (last resort) should I just put: drush_version: "8.1.16" in my config.yml and reprovision (or would I have to destroy the box?)?

I could of course just use "terminus drush" so it uses the remote version, but having drush in the local environment is handy for a lot of things too I imagine..

Note: I did read your informative blog post regarding Drush 9 changes (https://www.jeffgeerling.com/blog/2018/drupal-vm-48-and-drush-900-some-major-changes), as I wanted to use Drush globally, so I did the following:
`composer global require drush/drush:~8.0`
and added this to .profile:
`export DRUSH_LAUNCHER_FALLBACK=~/.composer/vendor/bin/drush`

Thanks!

**Comment by geerlingguy** [comment]
Yeah... Drush 9 and the default changes to make Drupal VM work with Drush 9 would definitely cause some of the issues you're seeing. It seems that Pantheon and Acquia hosting still currently default to using Drush 8.1.x, and the aliases are only compatible with older Drush versions.

There are a number of changes required if you want to be able to stick with an older version of Drush in Drupal VM, using changes as listed in the `geerlingguy.drush` role: https://github.com/geerlingguy/ansible-role-drush#role-variables

Basically, you'd want to add the following to your config.yml (or replace any of the existing settings), then destroy your VM and rebuild it so it has the older Drush version and settings:

```yaml
drush_launcher_install: no
drush_composer_global_install: yes
drush_composer_version: "~8.1"
```

You could also install via source using Git, but the composer install might be slightly more stable and easy to manage.

Anyways, once that's all done, it should work with the older style Pantheon aliases. It looks like Pantheon's support docs don't mention Drush 9 at all yet (https://pantheon.io/docs/drush-versions/), so I'd ask Pantheon support about when and if they'll start supporting it, so you can get the newer alias file format and use it in your Pantheon hosting infrastructure.

Please reopen this ticket if the above doesn't help. Thanks!

**Comment by RodenHirata** [comment]
Ah, brilliant, thank you. It works, but I just have one small issue. I did as you suggested with config.yml:

- After "vagrant up", I typed drush, and it said Drush wasn't installed. So I typed composer global require drush/drush:~8.0 - and that made it work.
- The pantheon aliases now appear when I'm outside the drupalvm site directory. They also work correctly. Great!
- The drupalvm site itself is still running 9.2.3 drush and has only the default VM aliases. Not 100% sure why, but I can live with it for now.. I guess I need to play around with installing a new local Drupal site without that drush component? Haven't actually tried this yet with DrupalVM (as I always relied on config.yml to build a Drupal site for me).

And yeah, it's a bit annoying Pantheon or Acquia haven't updated it yet, I'll have to check with them on that as I'd much rather just use the new version.

On the bright side, I'm getting quicker at configuring new VMs :)

**Comment by geerlingguy** [comment]
@RodenHirata - Ah, so a few notes:

  1. I'm guessing the composer global install by default installed it for the root user, and not the vagrant user, therefore you had to run the `composer global require drush/drush:~8.0` once more after you logged in. That should work well enough though, so you can keep things like that.
  2. The site built with Drupal VM via the [Drupal composer template](https://github.com/drupal-composer/drupal-project) defaults to using Drush 9, and there's no way to tell it to not do that. The simplest fix would be to do a `composer remove drush/drush` inside the generated Drupal project folder, and not use Drush local to the project. Otherwise you could downgrade by removing it then requiring it like `composer require drush/drush:~8.1`, and it should work similar to the global Drush inside Drupal VM.

**Comment by RodenHirata** [comment]
Thanks, that worked! For those following, make sure you delete the Drush folder inside the Drupal project folder as well after running "composer remove drush/drush" or it will cause some PHP error.

**Comment by Nick-Hope** [comment]
Apologies for using a closed issue but this is directly related. Pantheon are still not supporting Drush 9.

I could complete a build of Drupal VM (in Windows 10 Pro, in the "regular" way rather than the "fast" way that I documented on [this issue](https://github.com/geerlingguy/drupal-vm/issues/1853), and with `config.yml` the same as below but without the last 3 "drush" lines). But my Drush version went to 9 and I was no longer able to use the Pantheon aliases.

I could get back to Drush 8.1.17 by doing `composer remove drush/drush` inside the generated Drupal project folder then running `composer global require drush/drush:~8.1`. However I then didn't have the Drupal VM Drush aliases that I need.

So I destroyed that Drupal VM, and attempted to rebuild a new one with this `config.yml`:

```
---
drupalvm_webserver: nginx
installed_extras:
  - adminer
  - drush
php_version: "7.2"
drush_launcher_install: no
drush_composer_global_install: yes
drush_composer_version: "~8.1"

```
Now it hangs at `TASK [geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while).] ***` for hours and I'm guessing it doesn't like my `config.yml`.

Any suggestions? Are "yes"/"no" definitely correct rather than "true"/"false"? Or is there a way to manually generate the aliases for Drupal VM so that I can install the way that worked (with the shorter `config.yml`) and add the Drupal VM Drush aliases afterwards?

**Comment by Nick-Hope** [comment]
I tried this again today and it got past the hang and completed. I think yesterday's problems were down to both local and remote networking issues.

After the Drupal VM install I ran `composer remove drush/drush` again inside the generated Drupal project folder and deleted the `drupal/drush` folder [as advised by RodenHirata](https://github.com/geerlingguy/drupal-vm/issues/1756#issuecomment-384378317).

So I now still have Drush 8.1.17 working with my Pantheon aliases. I don't have any Drupal VM aliases (as far as I can see) and drush commands seem to be working on my Drupal VM site from anywhere on my system, without use of an alias. I guess that could be dangerous if I have more than one site in development. Any way to control that and limit it to this site (i.e. manually create an alias)?

**Comment by geerlingguy** [comment]
@Nick-Hope - Honestly after I finally moved all my sites off Drush 8.x I've kind of washed my hands of trying to continue supporting both 8 and 9, as my brain has already exploded enough times because of the array of differences 🤯

I would ask about that on Drupal Answers, in the Drupal/Drush Slack channels, or elsewhere; at this point I always store drush aliases per project in the project directory, and always make sure I change directories into that directory to run any Drush commands. Even if using Drush 8.x it is safer to do that than to use global aliases.

Global alias support in Drupal VM will likely be removed at some point in the future, maybe closer to Drupal 9's release, since it's not really helpful for new projects anymore.

Also, tell Pantheon to start supporting Drush 9... problem solved :D

**Comment by Nick-Hope** [comment]
Thanks @geerlingguy Actually I asked Pantheon about this and in fact [Drush 9.4.0 has been available on Pantheon for a couple of weeks as a "preview"](https://pantheon.io/blog/drush-940-release-available-pantheon). Unfortunately it appears to require Terminus for the time being, which is not an option on Windows (at least on my pre-WSL version, which I need for compatibility with another program).

As I believe Drush has to be installed globally to access Pantheon, it seems the solution may be to literally install it globally only when I need to use it remotely, then uninstall it. But leave it installed locally in Drupal VM for use there. Sounds daft but might be workable in the short term.

**Comment by RodenHirata** [comment]
I also wish to help but have since just moved onto WordPress, since it takes care of 90% of the responsive front-end with minimum effort.. Don't think Drupal is a great fit for small businesses anymore like D7/D6 was..

**Comment by Nick-Hope** [comment]
Unfortunately I'm still stuck with this. When I issue Drush 8.1.17 commands in `drupal-vm\drupal` or `drupal-vm\drupal\web` I get the following type of errors. I've tried global drush install and local drush install.
```
C:\Users\Nick\Sites\drupal-vm\drupal\web (master -> origin)
λ drush en admin_toolbar
$command_specific['dl'] = array('destination' => 'sites/all/modules/contrib');Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this      [error]
command.
The drush command 'en admin_toolbar' could not be executed.                                                                                        [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                       [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working
database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
 Drupal version         :  8.6.2
 Site URI               :  http://default
 Database driver        :  mysql
 Database hostname      :  localhost
 Database port          :
 Database username      :  drupal
 Database name          :  drupal
 PHP configuration      :  C:\PHP7\php.ini
 PHP OS                 :  WINNT
 Drush script           :  C:/Users/Nick/AppData/Roaming/Composer/vendor/drush/drush/drush.php
 Drush version          :  8.1.17
 Drush temp directory   :  C:\Users\Nick\AppData\Local\Temp
 Drush configuration    :
 Drush alias files      :  C:/Users/Nick/.drush/pantheon.aliases.drushrc.php
 Drupal root            :  C:\Users\Nick\Sites\drupal-vm\drupal\web
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
 Sync config path       :  ../config/sync
```
So I looked into using Drush 9 on Pantheon so I can just use it everywhere but unfortunately it seems to me that Terminus is a prerequisite for the time being because `terminus alpha:aliases` is necessary to download the Pantheon Drush 9 aliases. The dashboard method only offers aliases I already have for Drush 8.

Looks like my next option, unless I can talk Pantheon into literally emailing me my Drush 9 aliases, may be to set up Ubuntu in VirtualBox so I can run Terminus. I'm assuming the Ubuntu VirtualBox that Drupal VM installed is not featured enough to do that?

Not expecting you to follow up, Jeff (or RodenHirata). Just a note to self and for anyone who might be stumbling down my unconventional path.
