### ISSUE TITLE
Improving large Drupal Postgres performance by using pg_trgm

### ISSUE THREAD

**Issue by ferfebles** [geerlingguy/drupal-vm#1757]
- Feature Idea

We have about 110K comments and 278K nodes. Our Drupal instance was unbearably slow. It took about 30 seconds just to open the content admin interface. At some moment, the Drupal caches were disabled due to problems with our custom code, and as the Drupal instance grew the performance declined.

Finally, the solution was:

``` sql
CREATE EXTENSION pg_trgm;
CREATE INDEX url_alias__alias_trgm_gist_idx ON url_alias USING gist (alias gist_trgm_ops);
CREATE INDEX url_alias__source_trgm_gist_idx ON url_alias USING gist (source gist_trgm_ops);
ANALIZE url_alias;
```

All the information here: https://ferfebles.github.io/2018/04/16/Improving-large-Drupal-Postgres-performance-by-using-pg_trgm.html

**Comment by geerlingguy** [comment]
Thanks for posting this issue! It looks like it's more of a general 'Using Drupal with Postgres' suggestion, rather than something that could be implemented as a feature of Drupal VM itself, so I'm going to close this issue, but thanks for posting it nonetheless! Hopefully it will help others who run into the same idea.
