### ISSUE TITLE
Mojave + Drupal VM NFS Timeout

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#1828]
**Quick PSA.....**
It looks like Mojave doesn't just work with DrupalVM out of the box. It will hang on connecting to NFS. Mojave changed the security model for applications:

**Work Around**
In System Preferences -> . Security and Privacy -> Privacy -> Full Disk Access
you will need to add iterm or terminal.

See thread here for more information:
hashicorp/vagrant#10234 (comment)

Cross linking to BLT
https://github.com/acquia/blt/issues/3131

**Comment by geerlingguy** [comment]
Ah... reading through that linked issue on Vagrant's issue queue, it looks like the problem is specifically with _iTerm_, which I don't use.

For Terminal, the first time you build a VM and the export is created, the following prompt pops up. You click OK and everything works correctly:

<img width="532" alt="46012003-01bdac80-c0c8-11e8-87b5-79b2114e38b3" src="https://user-images.githubusercontent.com/481677/46743487-c649e300-cc6e-11e8-93f0-d9d7913ffbc3.png">

I'm guessing iTerm needs to be updated to work correctly with SIP and the new permissions model under 10.14+.

Since this isn't something I can fix in Drupal VM, and since it's something that isn't a problem with the stock Terminal app which most users tend to use, I'm going to close this issue and recommend the following:

  - If you use iTerm, follow the directions in OP to add iTerm to 'Full Disk Access'.
  - Follow this issue for updates on iTerm's support for the Mojave permissions model: https://gitlab.com/gnachman/iterm2/issues/7182

**Comment by epowelljr** [comment]
Can you help?

iMac:drupal-vm-master edgar$ vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-hostsupdater (= 1.0.2)'
iMac:drupal-vm-master edgar$ vagrant plugin expunge --reinstall

This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: y

All user installed plugins have been removed from this Vagrant environment!

Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-bindfs' plugin. This can take a few minutes...
Fetching: vagrant-bindfs-1.1.0.gem (100%)
Fetching: vagrant-hostmanager-1.8.9.gem (100%)
Fetching: vagrant-hostsupdater-1.1.1.160.gem (100%)
Fetching: micromachine-2.0.0.gem (100%)
Fetching: vagrant-vbguest-0.16.0.gem (100%)
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostsupdater (= 1.0.2)'
iMac:drupal-vm-master edgar$

**Comment by adriadrop** [comment]
I had the same problem with phpstorm terminal, things hung up until I gave permission to it.
