### ISSUE TITLE
Can we increase the filesystem on the VM

### ISSUE THREAD

**Issue by gregj0** [geerlingguy/drupal-vm#1844]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/gregj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS** (version) High Sierra 10.13.6

### Full console output

N/A

### Summary

We have a large production database and sometimes need to get it running locally.  It has recently gotten too big for the 80GB default filesystem will not hold it.   Note we are using 

base box 'geerlingguy/ubuntu1404'

 It looks like the filesystem is based on the initial packer-ubuntu-14.04 snapshot which I cannot increase.  I tried something like this https://tuhrig.de/resizing-vagrant-box-disk-space/ and could increase the filesystem on base but not on the any of the snapshots (which the VM is based upon).  I don't mind destroy everything is I could get that initial snapshot larger (like 100GB for now).

Anything advice you can offer?

**Comment by geerlingguy** [comment]
Three ways to work around this include:

  1. Use a shared folder to put the giant files into it (e.g. share `/var/lib/mysql`)... though this could make MySQL really slow.
  2. Create a separate disk and move the MySQL data dir there.
  3. Build a custom base box with Packer (my base box build is here: https://github.com/geerlingguy/packer-ubuntu-1604) with a much larger virtual disk image (see the `disk_size` parameter: https://github.com/geerlingguy/packer-ubuntu-1604/blob/master/ubuntu1604.json#L57).

Right now I don't have any plans to increase the default disk_size for my base boxes because 80 GB is already fairly substantial for 98% of sites I encounter. For sites with data sets that don't fit into that disk size, I generally recommend other DB solutions, or building a custom base box (as there are usually some other things you may want to tune for better performance).
