### ISSUE TITLE
Setup problem Windows 10

### ISSUE THREAD

**Issue by dupls** [geerlingguy/drupal-vm#1852]
Running Windows 10 Pro.
Followed video instructions, Download vagrant. Install VirtualBox. Install Ansible. 
Copy default.config.yml -> config.yml
example.drupal.make.yml -> drupal.make.yml
Install `vagrant plugin install vagrant-hostupdater`
`vagrant up`
no problems/errors
Visit site http://drupalvm.test/
This site can’t be reached drupalvm.test took too long to respond.

No documentation saying the hosts file needs to be edited as I thought `vagrant-hostupdater` handled that. I edit this file anyways including
`192.168.88.88  drupalvm.test`

Also tried changing `- local_path: ~/Sites/drupal-vm`

Also updated VirtualBox.

I have gone around and around `vagrant destroy` `vagrant up`. Seen some people changing drupalvm.dev to drupalvm.test then a comment by geerlingguy saying leave it to .dev

Run `vagrant provision` ==> drupalvm: VM not created. Moving on...
But when I do `vagrant destroy` it destroys the site. 

Is this a windows 10 issue?

**Comment by geerlingguy** [comment]
@dupls - Can you post a full log of what happens when you run `vagrant up`? It should have a _lot_ of output with hundreds of build steps, and at the end it should output a link to go to the dashboard (along with a link to view the dashboard even if your hosts file is not updated).

I'm guessing the build is not completing for some reason, but I wouldn't be able to help without a full build log.

Please consider closing this issue and opening a new one, and fill in all the different parts of the template so we have the information we need to help you.
