### ISSUE TITLE
Drupal VM unreachable when connected to Pulse Secure

### ISSUE THREAD

**Issue by arijitsdrush** [geerlingguy/drupal-vm#1864]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 2.2.1
Version 5.2.22 r126460 (Qt5.6.2)
ansible 2.7.2
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

### Your OS

 - **Windows 10 pro** (64 bit)

### Summary
My DrupalVM is working perfectly when I am not connected to organization's (Pulse secure) VPN. 

I can ping to 192.168.88.88 and web server and open website while not connected to VPN, but once I connect to pulse secure although I can do 'vagrant SSH' and log in to system but looks like 192.168.88.88 is unreachable.

I do understand VPN might doing something with IP, but unable to troubleshoot this problem.

**Comment by arijitsdrush** [comment]
So today I am able to solve the problem, but I think it might be a not proper solution.

I set up a forward port in vagrant  using following lines
`config.vm.network "forwarded_port", guest: 80, host: 8089, host_ip: "127.0.0.1"`

Then using Fidler, set up the host with a port address.

127.0.0.1:8089 dashboard.drupalvm.test
127.0.0.1:8089 drupalvm.test

Now I can work with website, both when connected to VPN and not connected in VPN.
I tried many other techniques by setting up a bridge network and others but none of those worked.

**Comment by geerlingguy** [comment]
@arijitsdrush - The way you mentioned is likely the only way I can think of to work around your issue.

The problem is some VPNs are extremely aggressive in taking control over local networking, to the point of also mapping all DNS queries and sometimes even the hosts file itself... I think Cisco AnyVPN or something like that does the same thing. So the only way to work around that is to switch the way your VirtualBox VM networking is configured (like you have).

Thanks for posting your solution here, though; I hope it will help someone else in a similar situation!
