### ISSUE TITLE
Vagrant VMWare - vmware_desktop.box 'not found'

### ISSUE THREAD

**Issue by BarryEdwards** [geerlingguy/drupal-vm#1870]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant: 2.2.2
VMWARE Fusion Professional Version:  11.0.2 (10952296)
Drupal VM: geerlingguy-drupal-vm-1b5014b

$vagrant plugin list
vagrant-hostsupdater (1.1.1.160, global)
vagrant-vbguest (0.16.0, global)
vagrant-vmware-desktop (2.0.1, global)

### Your OS

Macos High Sierra 10.13.6

### Full console output

$ vagrant up
Bringing machine 'drupalvm' up with 'vmware_fusion' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    drupalvm: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/ubuntu1604'
    drupalvm: URL: https://vagrantcloud.com/geerlingguy/ubuntu1604
==> drupalvm: Adding box 'geerlingguy/ubuntu1604' (v1.0.3) for provider: vmware_desktop
    drupalvm: Downloading: https://vagrantcloud.com/geerlingguy/boxes/ubuntu1604/versions/1.0.3/providers/vmware_desktop.box
    drupalvm: Download redirected to host: files.midwesternmac.com
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

### Summary

I have had a version of Vagrant/VMware with vagrant 'utility'  running on my old workstation for a long time.

Now have a new workstation , so am installing 'from scratch' again.

I notice that the Vagrant VMware plugin has changed name: was called .."something. utility", now goes by "vmware desktop plugin". Could this be the issue?

**Comment by geerlingguy** [comment]
@BarryEdwards - Sorry about that; I have not been maintaining a VMware version of any of my base boxes due to the fact that it was costing me around $200+/year to acquire the appropriate licenses. If you wish to use VMware Fusion instead of VirtualBox, you will need to override `vagrant_box` in your config.yml and use a base box that has a VMware build (you can search for one on https://app.vagrantup.com/boxes/search?utf8=✓&sort=downloads&provider=vmware&q=ubuntu+16.04).
