### ISSUE TITLE
Use DB name as a prefix for permissions

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#1888]
### Issue Type

 - Feature Idea

### Your Environment

N/A
```

```

### Your OS

 - **macOS** 10.13.6 (17G4015)

### Full console output
 N/A

### Summary

This is a change I always make to to DrupalVM. It allows me to switch branches and dbs easily, and keep old dbs. One benifit is that I can quickly switch to a prod db while keeping whatever I am working on currently. This is useful when I need to switch for security updates or urgent prod bugs.

I make the default user have access that has a like:

```
    priv: "{{ drupal_db_name }}%.*:ALL"
```

I had opened a PR for it, but it is way out of date now. #1575

I understand that this is a very specific request, which is why I am making it rather than just updating and creating a new PR.  I don't really think it is even required anymore, now that `default.config.yml` is overridden. This is more an interest gauge rather than a feature request.

**Comment by geerlingguy** [comment]
Hmm... I guess is the intent that you could create any database named like `{{ drupal_db_name }}-another-copy-of it` and have the Drupal user automatically get privileges on it as well?

For security purposes I'd rather keep the default the way it is, just because that seems slightly like a 'magic' user and could catch someone off guard if they create another database with the same prefix and the original site gets access to that new database.

That would be an exceedingly rare use case, but luck favors the cautious or something like that...

**Comment by frob** [comment]
This was an old PR that I thought I had opened an issue for, but I guess I never did. I think this is from back before the ability to overwrite the db creds. Eitherway, I cannot argue with secure by default.
