### ISSUE TITLE
DrupalVM 404 Not Found After Install

### ISSUE THREAD

**Issue by userraj** [geerlingguy/drupal-vm#1891]
### Issue Type
 - Bug Report 

### Your Environment

```
Vagrant 2.1.2
Virtualbox 5.2.16
```

### Your OS

- Windows 10

### Full console output (error message)

```
Not Found
The requested URL / was not found on this server.

Apache/2.4.18 (Ubuntu) Server at www.drupalvm.test3 Port 80
```

### Summary
We have an existing `Drupal codebase` on our Windows machine that sits in the `D:/Sites/local/d8` directory. We have downloaded the [drupal-vm repo](https://github.com/geerlingguy/drupal-vm) to `D:/drupal-vm/`. When we run the `vagrant up` command in `D:/drupal-vm/geerlingguy-drupal-vm-4fc4a3a`, we get no errors and command finishes. After opening a browser, we navigate to `http://dashboard.drupalvm.test3/` just fine, however we get the `404 Not Found` when we try to visit `http://drupalvm.text3`. 

### Steps to reproduce

1. Download [drupal-vm repo](https://github.com/geerlingguy/drupal-vm) into the `D:/drupal-vm`, which should result in `D:/drupal-vm/geerlingguy-drupal-vm-4fc4a3a` with Windows 10
2. Move `d8/` (which is a `.git` repository to the `D:/Sites/local` drive location, should result in `D:/Sites/local/d8`
3. Run `vagrant up` inside of `D:/drupal-vm/geerlingguy-drupal-vm-4fc4a3a`
4. Observe the console output with no error messages
5. Navigate to `http://dashboard.drupalvm.test3/` (observe no errors)
6. Navigate to `http://drupalvm.test3/` (observe 404 not found)

### config.yml file

- You can get [config.yml here](https://gist.github.com/userraj/81f39dad084cac603b02a5196d3657a0)

**Comment by geerlingguy** [comment]
One quick question: You are sharing `/Sites/devdesktop/d8` into `/var/www/drupalvm` using NFS, but you say you're running Windows.

It seems like maybe the directory is not being shared correctly because by default NFS won't work on Windows. See notes in the documentation here: http://docs.drupalvm.com/en/latest/getting-started/installation-windows/#troubleshooting-vagrant-synced-folders

But basically, try replacing `nfs` in the shared folders in config.yml with `''` (just two empty quotes) so it will use the default shared folder method.

Then do `vagrant halt` and then `vagrant up --provision` and see if it's working.

Also, I'm not 100% sure the local_path is correct. If you're on windows shouldn't it be like `c:/Sites/devdesktop/d8`? (Assuming that's the actual full path to the files...).

You can confirm what's being shared into the VM by running `vagrant ssh` to log in, then run `ls -lah /var/www/drupalvm`

If that folder is empty in the VM, then the synced folder setup is incorrect.

**Comment by userraj** [comment]
@geerlingguy Turns out, if i had followed directions properly I would have never had this issue. 

I updated my [config.yml](https://gist.github.com/userraj/81f39dad084cac603b02a5196d3657a0) file. 

Here is what I had to fix in order for it to work:

1. i have to use `vagrant_box: geerlingguy/ubuntu1804`
2. under `vagrant_synced_folders`, the `destination` needed to be set to `/var/www/drupalvm` (or equivalent) along with `type: nfs` and `create: true`
3. `drupal_composer_install_dir` variable had to set as the same as the `destination` under `vagrant_synced_folders` (also mentioned in the `Update drupal_core_path` of [Using a local Drupal codebase](http://docs.drupalvm.com/en/latest/deployment/local-codebase/)

When I did run `ls -lah /var/www/drupalvm` after `vagrant ssh`, I was able to see the files correctly and it was no longer empty. Your responses did eventually lead to my answers.
