### ISSUE TITLE
Best way to add a new site in Drupal VM

### ISSUE THREAD

**Issue by EdViva** [geerlingguy/drupal-vm#1912]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.4
VirtualBox 5.2.18r124319
```

### Your OS

  Host OS Mac 10.13.6

### Full console output

N/A

### Summary

what is the best way to add a new site. I provisioned the vm and the drupal site is not working 'The website encountered an unexpected error. Please try again later.' But I'd rather not spend time debugging an install I'm not going to use. I have pulled my files and db to the synced folder but I am not sure how to make a new site. I amended the vhost file in /nginx/sites-enabled and reloaded nginx but it failed with 'The provided host name is not valid for this server.' Do I need to just create a new host file for nginx or do i need to do something in config.yml and re-provision?

Thanks

**Comment by geerlingguy** [comment]
You shouldn't need to ever edit any files inside the VM to add sites. You need to add a server to the `nginx_hosts` list (https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L164) (use the first example there as a template for adding more drupal sites), then you need to add a database for the site to use in `mysql_databases` (https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L190). And probably a separate database user as well in `mysql_users` (https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L195).

Then run `vagrant provision` and Ansible will create the relevant configurations and restart all the services that need to be restarted to get the new site document root up and running.

If you want to share a local codebase into the VM in some place where the nginx server / host can pick it up, you can add more shares to the `vagrant_synced_folders` list. Otherwise you could log into the VM (`vagrant ssh`) and do whatever you need to inside too.
