### ISSUE TITLE
Code style of default.config.yml doesn't match Symfony Yaml

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1932]
### Issue Type

- Chore / task, I suppose

### Summary

The code style used by default.config.yml doesn't match the output format of the Symfony Yaml parser: https://symfony.com/doc/current/components/yaml.html

This is annoying for downstream projects like BLT that need to modify config.yml programmatically using the Yaml parser, because even just parsing and re-dumping the config.yml file with no changes produces a pretty large diff. For example:
```
-
-# Set drupal_site_name to the project's human-readable name.
-drupal_site_name: "BLTed 8"
+drupal_site_name: 'BLTed 8'
 
 # Provide the path to the project root to Vagrant.
 vagrant_synced_folders:
-  # Set the local_path for the first synced folder to `.`.
-  - local_path: .
+  -
+    local_path: .
     # Set the destination to the Acquia Cloud subscription machine name.
     destination: /var/www/blt-canary
     type: nfs
 
-drupal_composer_install_dir: "/var/www/blt-canary"
-drupal_core_path: "/var/www/blt-canary/docroot"
+drupal_composer_install_dir: /var/www/blt-canary
+drupal_core_path: /var/www/blt-canary/docroot
```

So I'm just curious if default.config.yml follows any particular code style standard, and whether you'd mind cleaning it up to match Symfony Yaml's. I'm happy to open a PR if you agree.

**Comment by geerlingguy** [comment]
I kinda hate their style for list items, you end up with lots of

```
  - 
    something: here
```

and that just looks terrible to my eye—no other project/language/standard I've seen does YAML list/dicts like that, they all do:

```
  - something: here
```

So for that, I'd really like to _not_ change it because outside of Symfony's strange standard, the rest of the YAML world (Ansible, Kubernetes, everything in Python-land) uses the 2nd form above.

For the strings, it doesn't matter to me if they're double or single quotes... that's a bit of a pedantic thing in YAML at least, and it just matters that they match and are somewhat consistent across my projects :D

**Comment by danepowell** [comment]
Fair enough. I didn't realize there were competing style standards, or just how bad Symfony's are 😄 

I guess if BLT wants to solve this, it'll just have to fork the config.yml for itself, although I'm not sure even that is worth it given how bad it looks.

**Comment by geerlingguy** [comment]
The problem overall is that YAML doesn't really have a universal default style—even the official spec uses different spacing / line examples (e.g. https://yaml.org/spec/1.2/spec.html) :(
