### ISSUE TITLE
Provision fails with "error setting ownership of `/var/www/html.dpkg-new': Operation not permitted"

### ISSUE THREAD

**Issue by dsnopek** [geerlingguy/drupal-vm#194]
I'm using the latest checkout of drupal-vm and when doing a fresh `vagrant up` I get the error:

```
TASK: [geerlingguy.apache | Ensure Apache is installed.] ********************** 
failed: [drupalvm] => (item=apache2,apache2-mpm-prefork,apache2-utils) => {"failed": true, "item": "apache2,apache2-mpm-prefork,apache2-utils"}
stderr: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Here's a gist with the full output: https://gist.github.com/dsnopek/7ed89998f4d3eb192949

I don't know Ansible, but I would have assumed that dpkg would be run sudo root, so I'm not sure how it can have trouble setting the ownership on that directory. :-/

Any help would be appreciated! Thanks!

**Comment by dsnopek** [comment]
This turned out to be an NFS issue! I got passed it by switching to the Virtualbox shared folder stuff. Now I'm on another file permission issue. :-/ But if I can't solve that I'll make a new issue.

**Comment by marcvangend** [comment]
Did you (or anyone) ever manage to solve this while using NFS? I'm getting the same error.

After reading many posts on different forums and blogs, I have been experimenting with the NFS settings trying to solve this. If I understand correctly, the problem is that the VM root user does not have permissions to perform a chown on files in the mounted share. I have tried to specify other mount options in config.yml, specifically the `no_root_squash` option as suggested in http://serverfault.com/questions/212178/chown-on-a-mounted-nfs-partition-gives-operation-not-permitted, but that didn't help: Vagrant didn't even get past the "Mounting NFS shared folders" phase.

@geerlingguy As far as I'm concerned, this issue should still be open.

**Comment by dsnopek** [comment]
Nope, I just gave up on NFS because I wanted to get started - at that point I hadn't even really tried drupal-vm yet and so evaluating it *at all* was a higher priority than making it performant. :-)

Maybe now that I've been using drupal-vm for a while and like it, I'll go back and try to get NFS working again...

**Comment by marcvangend** [comment]
Eventually I found https://github.com/geerlingguy/drupal-vm/issues/85. It turned out to be a simple trick: create a directory "html" inside the synced directory and the Apache installation works fine.

**Comment by carlos-mg89** [comment]
@marcvangend indeed, creating the 'html' directory works like a charm!

**Comment by mborek-elastique** [comment]
works with nginx-common similar problems too ;)

**Comment by swartzlib7** [comment]
I use an NFS share from host to client using Vagrant and adding "no_root_squash" handled this for me.
