### ISSUE TITLE
Generate config.yml apache_vhosts from sites.yml

### ISSUE THREAD

**Issue by Loganguy** [geerlingguy/drupal-vm#1975]
### Issue Type
Support Request

### Your Environment
drupal 7 multisite
vagrant 2.0.4
virtualbox 6.0.12
ansible 2.8.1
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]

### Your OS
macos 10.13.6

### Summary
We have 90 sites on a drupal multisite instance.  We would love to have a way to manually set sites.yml and then automatically update  config.yml apache_vhosts: and mysql_databases:. 
I mean it would be nice if vagrant could iterate through all the sites in sites.yml and either create the apache_vhosts and mysql_databases or use code which instructs vagrant to iterate sites.yml without even listing each site in config.yml
 Is this possible?
thanks

**Comment by geerlingguy** [comment]
Unfortunately, this is not something I think I'd be able to sanely support. It is a possibility, but you'd have to do something custom in a `pre_provision_script`, using `set_fact` to set the `apache_vhosts` and `mysql_databases` variables based on variables you read in during a previous task (via something like `{{ lookup('file', 'path/to/sites.yml') | from_yaml }}`).

Because of the complexity, though, and the fact that the majority of sites I see don't use a `sites.yml` file, I don't want to add official support in Drupal VM itself.
