### ISSUE TITLE
Windows- 503 Service Unavailable accessing local site hostname

### ISSUE THREAD

**Issue by D41103168** [geerlingguy/drupal-vm#1988]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.6
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

```

### Your OS
 - **Windows** (version)

### Full console output

https://github.com/D41103168/Vagrant-reports/blob/master/vagrant-up-report.txt
https://github.com/D41103168/Vagrant-reports/blob/master/2nd-vagrant-up.txt

### Summary
Hello, I have recently started to use Drupal VM. I have successful installed and using a Vanilla Drupal VM but run into a problem installing the Drupal VM a shared project. This works without problems on many of my team members but not for me.
 
After successful installation without any errors of all requirements for the Windows and running "vagrant up" without any error I can access the VM page on the browser by IP but **can not access the Local instance by hostname**.

Notes: 
- The installation ran without any error
- I can connect with vagrant ssh and run any scripts/Drush/composer commands from the project
- I can access the dashboard VM page by IP.
- The hosts file is edited by vagrant-hostsupdater without any error, manually edit shows the entries are here.
![local-vm](https://user-images.githubusercontent.com/57151089/68948078-c7c5d300-07bf-11ea-91ad-964ba43685a6.png)
![Service unavailable](https://user-images.githubusercontent.com/57151089/68948081-c98f9680-07bf-11ea-9631-b2a22cd7eba6.png)

If anyone has any clue about that please share your thoughts! Thank you!

**Comment by geerlingguy** [comment]
Note that using `.local` domains causes all kinds of headaches, and I usually recommend people use `.test` (like `mysite.test`) instead, because this prevents those headaches.

You need to make sure that vagrant hostsupdater is installed and working correctly, and also you can check in powershell or whatever shell you're using if `ping `[whatever the site is].local` is actually returning the IP address of Drupal VM. If not, your hosts file might be configured wrong, you might have a proxy intercepting the request, or your computer's DNS might otherwise be hijacked by some corporate VPN utility or something, taking over the `.local` requests.

**Comment by danepowell** [comment]
I see you are using `geerlingguy/ubuntu1604` as the base box. I was also using `geerlingguy/ubuntu1604` with DrupalVM 4.9.2 on Mac (not Windows) and out of nowhere started getting this error today. Even destroying / recreating the box didn't fix it.

I realized that both the base box and DrupalVM version were out of date. Updating to DrupalVM 5.1.0 and the `geerlingguy/drupal-vm` base box fixed it.
