### ISSUE TITLE
Use Docker for MariaDB

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#1989]
### Issue Type

 - Feature Idea

### Your OS

 - **macOS** (10.13)

### Summary

Use Docker image for MariaDB.

During the course of development and testing we reset our DB all the time. To make this quicker, I use adminer to keep a snapshot of the prod DB in a second DB on DrupalVM and just copy it over everytime I need to reset. This would be quicker if I could just reset a docker image on DrupalVM instead of having to constantly drop all tables and use adminer to sql copy all the data from one db to another. 

I was just thinking about how quick setup could be if we used a docker image with a preloaded DB. Something akin to what is described here https://www.lullabot.com/articles/rocket-ship-fast-jobs-circleci-preinstalling-database

I am putting it here for consideration.

**Comment by geerlingguy** [comment]
This would be a serious architecture change which I'd rather not do for Drupal VM. If some parts are Docker, that not only requires the Docker daemon running inside the VM (so like a weird hybrid of docker-machine and standard VM in one VM), it would also require rewriting the entire structure of the Drupal VM docker image.

Instead of that, I would recommend going straight to a full Docker setup if you require fast replacement of any of the running apps/data, or figure out a different way to load/reload the DB data (e.g. backing up the data directory for MySQL, and restoring and restarting the service).
