### ISSUE TITLE
Error with conflicting exports: NFS is reporting your exports file is invalid

### ISSUE THREAD

**Issue by nswitzer** [geerlingguy/drupal-vm#2019]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.7
VirtualBox 6.0.18r136238
ansible 2.9.0
```

### Your OS
 - **macOS** 10.15.3

### Full console output
```
➜ vagrant up
Bringing machine 'dcco' up with 'virtualbox' provider...
==> dcco: Checking if box 'geerlingguy/drupal-vm' version '2.0.2' is up to date...
==> dcco: Clearing any previously set forwarded ports...
==> dcco: Clearing any previously set network interfaces...
==> dcco: Preparing network interfaces based on configuration...
    dcco: Adapter 1: nat
    dcco: Adapter 2: hostonly
==> dcco: Forwarding ports...
    dcco: 22 (guest) => 2222 (host) (adapter 1)
==> dcco: Running 'pre-boot' VM customizations...
==> dcco: Booting VM...
==> dcco: Waiting for machine to boot. This may take a few minutes...
    dcco: SSH address: 127.0.0.1:2222
    dcco: SSH username: vagrant
    dcco: SSH auth method: private key
==> dcco: Machine booted and ready!
[dcco] GuestAdditions 6.0.18 running --- OK.
==> dcco: Checking for guest additions in VM...
==> dcco: [vagrant-hostsupdater] Checking for host entries
==> dcco: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> dcco: [vagrant-hostsupdater]   192.168.87.64  dcco.drupalvm  # VAGRANT: 8bba20849afdc7ac3a1e4a35b7c2d27c (dcco) / 6650cf0b-ebb4-4401-b588-5e88433444ad
==> dcco: [vagrant-hostsupdater]   192.168.87.64  www.dcco.drupalvm  # VAGRANT: 8bba20849afdc7ac3a1e4a35b7c2d27c (dcco) / 6650cf0b-ebb4-4401-b588-5e88433444ad
==> dcco: [vagrant-hostsupdater]   192.168.87.64  adminer.dcco.drupalvm  # VAGRANT: 8bba20849afdc7ac3a1e4a35b7c2d27c (dcco) / 6650cf0b-ebb4-4401-b588-5e88433444ad
==> dcco: [vagrant-hostsupdater]   192.168.87.64  xhprof.dcco.drupalvm  # VAGRANT: 8bba20849afdc7ac3a1e4a35b7c2d27c (dcco) / 6650cf0b-ebb4-4401-b588-5e88433444ad
==> dcco: [vagrant-hostsupdater]   192.168.87.64  pimpmylog.dcco.drupalvm  # VAGRANT: 8bba20849afdc7ac3a1e4a35b7c2d27c (dcco) / 6650cf0b-ebb4-4401-b588-5e88433444ad
==> dcco: [vagrant-hostsupdater]   192.168.87.64  dashboard.dcco.drupalvm  # VAGRANT: 8bba20849afdc7ac3a1e4a35b7c2d27c (dcco) / 6650cf0b-ebb4-4401-b588-5e88433444ad
==> dcco: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> dcco: Setting hostname...
==> dcco: Configuring and enabling network interfaces...
==> dcco: Exporting NFS shared folders...
NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:6: /System/Volumes/Data/Users/nickswitzer/Sites/frw/drupal-vm conflicts with existing export /System/Volumes/Data/Users/nickswitzer/Sites/frw
```

### Summary
My DrupalVM machines provision normally when there is nothing in `/etc/exports`, but as soon as I have one machine provisioned (`frw` in this example) and attempt to provision another (`dcco` in this example), I receive the reported error when attempting to provision the `dcco` machine. If I completely clear out `/etc/exports` or remove the path reported by the error as conflicting and run `vagrant reload`, the `dcco` machine provisions normally and works. However, if I go back to provision the `frw` machine that was originally working it throws the same error that I've reported until I remove the conflict from the exports file again.

**Comment by geerlingguy** [comment]
Could this be related to https://github.com/hashicorp/vagrant/issues/11144 and/or https://github.com/geerlingguy/drupal-vm/issues/1917?

Did this work before and you're now getting errors after upgrading macOS? Or is this something you've never tried before and it's not working?

**Comment by philip-elevated** [comment]
I can confirm the same error's here:

`NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:4: /System/Volumes/Data/Users/philipstier/Sites/alt/drupal-vm conflicts with existing export /System/Volumes/Data/Users/philipstier/Sites/alt`

This is something that has worked / this are vm's that were working previous to updating to Catalina, but now is giving me these errors.

The work-around right now is as described in @nswitzer 's summary.

**Comment by geerlingguy** [comment]
@philip-elevated - Have you looked into https://github.com/geerlingguy/drupal-vm/issues/1917 ? I'm guessing if this was working before Catalina and is now _not_ working, it's due to the new permissions system in Catalina and workarounds are documented in that linked issue.

**Comment by philip-elevated** [comment]
@geerlingguy - Yes, I've updated permissions as directed in #1917 

<img width="574" alt="Screen Shot 2020-03-02 at 12 48 26 PM" src="https://user-images.githubusercontent.com/45582891/75711740-1f5f5000-5c84-11ea-8200-9327aab34745.png">

**Comment by philip-elevated** [comment]
Hold on, I breezed over the Developer tools permissions. Testing that out now.

**Comment by nswitzer** [comment]
@geerlingguy - Thanks so much for the quick response. I was experiencing this issue on Mojave (10.14.6) as well. Over the weekend, I destroyed all of my VMs, upgraded to Catalina and then rebuilt, at which point I saw the same issue described in the summary. I've double-checked my permissions in the OS Security and Privacy section and everything seems to be in line with what is described in #1917. Let me know if there is any other relevant information I can provide.

**Comment by philip-elevated** [comment]
@geerlingguy -I've tested with correct permissions set and am still getting the same issue as @nswitzer. I have found, however, that if I alter my exports file a bit, then everything seems to work fine. Also - and I do not know if it makes a difference - I am using DrupalVM as a git submodule for each project that I'm working on.

/// Exports before manual alter
`# VAGRANT-BEGIN: 501 4c2632e5-8f25-4021-914f-241885982d99
/System/Volumes/Data/Users/[user]/Sites/wals -alldirs -mapall=501:20 192.168.88.88
/System/Volumes/Data/Users/[user]/Sites/wals/drupal-vm -alldirs -mapall=501:20 192.168.88.88
# VAGRANT-END: 501 4c2632e5-8f25-4021-914f-241885982d99`

/// Exports after manual alter
`# VAGRANT-BEGIN: 501 4c2632e5-8f25-4021-914f-241885982d99
/System/Volumes/Data/Users/[user]/Sites/wals /System/Volumes/Data/Users/[user]/Sites/wals/drupal-vm -alldirs -mapall=501:20 192.168.88.88
# VAGRANT-END: 501 4c2632e5-8f25-4021-914f-241885982d99`

I'm essentially rewriting each export as a one line expression, instead of two.

**Comment by dorian-e3** [comment]
It should be noted that the second export is only a problem if the drupal-vm directory is inside the "vagrant_synced_folders" "local_path".

**Comment by philip-elevated** [comment]
@geerlingguy - Any ideas here by chance? I'm having to edit my exports file before I spin up any DrupalVM site.

**Comment by geerlingguy** [comment]
I don't know of any reason this would still be happening. I haven't encountered this issue, but I've been on Catalina for months now, and I'm guessing if I did run into something at some point, I found a fix and don't remember doing it :O

**Comment by pheadeaux** [comment]
@geerlingguy Hi. Thank you for this amazing tool, we use it every day!

I experience on macOS Catalina (`v10.15.3`) a very slow drupalvm. We are talking 30sec+ for page loads! This is a common behavior around all the Drupal projects we maintain (10+). When working with XDEBUG it becomes even more slower.

I come here from the docs on performance using mixed folder types: http://docs.drupalvm.com/en/latest/other/performance/#mixing-synced-folder-types 

And I configured my vm like suggested:

```yaml
	vagrant_synced_folders:
	  - local_path: .
	    destination: /var/www/drupal
	    type: rsync
	    create: true
	    excluded_paths:
	      - private
	      - .git
	      - web/sites/default/files
	      - tmp
	      # Exclude the second synced folder.
	      - config/drupal
	  # Use a slower but two-way sync for configuration sync directory.
	  - local_path: config/drupal
	    destination: /var/www/drupal/config/drupal
	    type: "" # Or smb/nfs if available
	    create: true
```

This actually improves the performance of the vagrant, when using `rsync` for the root. `nfs` and `smb` do not improve much - even with excluded folders.

But when I tried to start up a second vagrant - with the same settings - in a different project, I get an error. I can not run two vagrants with this settings in parallel. The error basically says the same as reported by @nswitzer above:
	
	$ vagrant up
	...
	==> project_name: Exporting NFS shared folders...
	NFS is reporting that your exports file is invalid. Vagrant does
	this check before making any changes to the file. Please correct
	the issues below and execute "vagrant reload":
	
	exports:6: /System/Volumes/Data/Users/[user]/[project_name]/config/drupal conflicts with existing export /System/Volumes/Data/Users/[user]/[project_name]

So basically the subfolder `/config/drupal` is not supported here. And hasn't been before, as stated in this unrelated https://github.com/adlogix/docker-machine-nfs/issues/6
As stated in #1917 and https://stackoverflow.com/a/21497714 what helps for a single machine is:

```bash
	sudo rm /etc/exports
	sudo touch /etc/exports
	
	vagrant halt
	vagrant up --provision
```

This will create an entry in `/etc/exports` like this:

	# VAGRANT-BEGIN: 501 0e8d6925-45a9-4a50-b5da-1093c4a6e8e4
	/System/Volumes/Data/Users/[user]/.vagrant.d/cache/geerlingguy/ubuntu1804 -alldirs -mapall=501:20 192.168.88.201
	/System/Volumes/Data/Users/[user]/[project_name] -alldirs -mapall=501:20 192.168.88.201
	/System/Volumes/Data/Users/[user]/[project_name]/config/drupal -alldirs -mapall=501:20 192.168.88.201
	# VAGRANT-END: 501 0e8d6925-45a9-4a50-b5da-1093c4a6e8e4


BUT: only for the first run this will work. Since on every `vagrant up` a `nfsd checkexports` is called, which will in return throw again the error above.
I tried to update the file manually like @philip-elevated suggested, but no luck.

@geerlingguy your steps to reproduce would be:

A) setup a project with the rsync performance config, described in http://docs.drupalvm.com/en/latest/other/performance/#mixing-synced-folder-types and after successful `vagrant up` run `nfsd checkexports` to see the error.

Or 

B) Try to setup two DrupalVM Projects with the same multiple synced folder settings. The Second will fail.

Please keep digging into this. Since Catalina DrupalVM really became unbearably slow to work with, and we are running out of options to improve performance - except for switching to docker...

**Comment by nswitzer** [comment]
I've resolved this issue by installing DrupalVM with Composer on all of my projects, rather than using a git submodule and this has fixed the issue because DrupalVM is now only adding a single line to `/etc/exports`. I'm going to close this issue.

**Comment by asherry** [comment]
@nswitzer I'm not exactly sure what you mean by "installing DrupalVM with Composer", can you explain a little more how exactly you setup the folder structure so that it didn't create a duplicate entry?
I'm still confused by this issue, I have a project folder and then a `./drupalvm` sub folder where I installed the machine with composer.
I still have the duplicate issue

**Comment by nswitzer** [comment]
Hey @asherry - I followed the instructions outlined in the DrupalVM docs pretty closely: http://docs.drupalvm.com/en/latest/deployment/composer-dependency/. As a quick summary: I've installed as a dev dependency using Composer, added my config.yml file to a directory called `settings` in the project root and created a delegating `Vagrantfile` in the project root. My Drupal site is located at `docroot` and DrupalVM is installed in the `vendor` directory at the same location outlined in the docs.

**Comment by michfuer** [comment]
I came across this while porting a project to a new laptop. 

A couple of things to note is that on my new machine I'm running Vagrant 2.2.9 without ansible, and the old is running 2.2.7 and has ansible installed.

```
# config.yml old machine
vagrant_synced_folders:
  - local_path: ./project_name
    destination: /home/vagrant/docroot
    type: nfs
    create: true
```

exports has one line for my one synced folder. If I `vagrant reload` it still has just the one line.
```
# /etc/exports old machine
# VAGRANT-BEGIN: 501 4f7aeb06-63bf-462f-93d0-35c517b92818
/System/Volumes/Data/Users/username/sites/drupal_vm/project_name -alldirs -mapall=501:20 192.168.50.63
# VAGRANT-END: 501 4f7aeb06-63bf-462f-93d0-35c517b92818
```

Here I wanted to add another synced folder
```
# config.yml new machine
vagrant_synced_folders:
  - local_path: ./project_name
    destination: /home/vagrant/docroot
    type: nfs
    create: true
  - local_path: ~/sites/another_sync
    destination: /home/vagrant/another_sync
    type: nfs
    create: true
```

after `vagrant reload` expecting exports to have two lines for my two synced folder, but instead I'm seeing three
```
# /etc/exports new machine
# VAGRANT-BEGIN: 502 827eae1d-8d42-4b1a-a037-30705877a1f9
"/System/Volumes/Data/Users/username/sites/another_sync" -alldirs -mapall=502:20 192.168.50.63
"/System/Volumes/Data/Users/username/sites/drupal_vm" -alldirs -mapall=502:20 192.168.50.63
"/System/Volumes/Data/Users/username/sites/drupal_vm/project_name" -alldirs -mapall=502:20 192.168.50.63
# VAGRANT-END: 502 827eae1d-8d42-4b1a-a037-30705877a1f9
```
and `sudo nfsd checkexports` I get

```
exports:4: /System/Volumes/Data/Users/username/sites/drupal_vm/project_name conflicts with existing export /System/Volumes/Data/Users/username/sites/drupal_vm
```

Now if I comment out this block https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L87

on the new machine and reload, the exports contains only two entries.

I'm running Catalina on both, `10.15.4` on the old and `10.15.5` on the new.

No idea why my new machine is getting that extra entry, but the old one isn't?
