### ISSUE TITLE
Using debian 10 (Buster) ?

### ISSUE THREAD

**Issue by nicolas-san** [geerlingguy/drupal-vm#2020]
Hi, 
first, thanks a lot for the work :)

Question is: can I use Debian 10 as base OS (it is not in the doc) for my dev environment, and can I deploy to production to Debian 10 as well ?

Someone using it already ? Some plan to do so ?
(this PR is relevant https://github.com/geerlingguy/drupal-vm/pull/2018)

Thanks a lot !

(don't know if it's the right place to ask questions)

**Comment by geerlingguy** [comment]
@nicolas-san - Yikes, I just realized the docs site had been failing to build for the past couple months due to the GitHub integration needing to be reset on Read the Docs—now the page is updated: http://docs.drupalvm.com/en/latest/configurations/base-os/

Debian 10 is ... mostly supported. I haven't done too much testing but the basic roles should all work there now.

Note that you should be able to use whatever OS you need in production (depending on your hosting provider), but Drupal VM doesn't have any official support for running in production anymore, just for local development environments.

**Comment by geerlingguy** [comment]
And note that this _should_ be fixed by https://github.com/geerlingguy/ansible-role-php-pecl/commit/730d53c049188d0205fae25b185f0163b5cd1240 — I'll try to update that role in Drupal VM soon (it will be in master until the next Drupal VM release).

**Comment by nicolas-san** [comment]
thanks :)
