### ISSUE TITLE
Drush in Drupal VM is not working for Drupal 7, in 2 installation

### ISSUE THREAD

**Issue by manojbisht891** [geerlingguy/drupal-vm#2026]
I have cloned drupal vm repo, now I have 2 installation one of Drupal 7 and other of Drupal 8, so I have added entry in "vagrant_synced_folders" for 2 local path, and added 2 entry in "apache_vhosts", created 2 database also, modified settings.php for both Drupal 7 and 8. Issue is all working fine, but drush is not working in Drupal 7, while in Drupal 7 it is working fine.

Drush global version is 10.2

So I have installed drush locally, by downloading from drush git repo. and installing 8.3.2, It seems to be working in Drupal 7 setup.

Is this the correct approach, or I am missing something.

**Comment by geerlingguy** [comment]
Yes, unfortunately managing Drush with both Drupal 7 and Drupal 8 in the same instance and with the same version of Drush can be... tricky at best. The problem is I believe Drush 9 and 10 _only_ work with Drupal 8, whereas Drush 8 works with Drupal 7 and 8... but Drush 9 and 10 are required for some Drupal 8 use cases, and those versions are better off installed as a Composer dependency local to the project.

You can do that with Drupal 7 sites too, but it can get messy either way (globally or installed local to the codebase).

And unfortunately, due to that complexity I don't usually find that I can help too much in the Drupal VM issue queue; any further issues you encounter, I would consider asking on the Drupal stack exchange site or in the Drush support queues (e.g. on Slack).
