### ISSUE TITLE
Failed to check for local known_hosts file

### ISSUE THREAD

**Issue by fsnet** [geerlingguy/drupal-vm#2034]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.6
VirtualBox 6.1.0r135406
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/volka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/volka/.pyenv/versions/3.7.4/lib/python3.7/site-packages/ansible
  executable location = /Users/volka/.pyenv/versions/3.7.4/bin/ansible
  python version = 3.7.4 (default, Apr 15 2020, 10:44:03) [Clang 9.0.0 (clang-900.0.39.2)]
```

### Your OS

 - **macOS** (10.12.6)

### Full console output

```
TASK [Check if local known_hosts file is present.] *****************************
fatal: [agm]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /usr/bin/python3: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP *********************************************************************
agm                        : ok=166  changed=13   unreachable=0    failed=1    skipped=362  rescued=0    ignored=1
```

### Summary
With DrupalVM 5.2 provisioning fails with Ansible on host. Forcing use of ansible_local provisioner works.
The problem occurs with base box `geerlingguy/drupal-vm (virtualbox, 2.0.8)` as well as `geerlingguy/ubuntu1804 (virtualbox, 1.1.5)`.
Using DrupalVM 5.1 works fine.
Similar issue? #2030

**Comment by geerlingguy** [comment]
@fsnet - Drupal VM 5.2 started defaulting everything to `python3`, and I wonder if that could be the issue, since you're running a much older macOS release which may have a different/older version of `python3` than what Ansible would thrive on.

See also: https://github.com/geerlingguy/drupal-vm/issues/530 — there might be some good suggestions in there relating to the python environment.

**Comment by fsnet** [comment]
@geerlingguy: Thanks for pointing me in the right direction. 10.12 has no python3 in /usr/bin and I did not understand that the path set in ansible_python_interpreter is the same for VM and host.

As a workaround I have created a symlink in the VM
`sudo ln -s /usr/bin/python3 /usr/local/bin/python3`
and changed the variable in config.yml 
`ansible_python_interpreter: /usr/local/bin/python3`
before re-provisioning the VM.
On the host macOS /usr/local/bin/python3 is a symlink to my pyenv python3
`/usr/local/bin/python3 -> /Users/volka/.pyenv/shims/python3`

Another solution would be to create a symlink `/usr/bin/python3` on the host and let the VM and config.yml untouched. But this only works with Apple's SIP disabled.

I have tried to create the symlink in the VM with a pre-provision script but the TASK [Gathering Facts] fails.

**Comment by geerlingguy** [comment]
I wonder if you could add an inline shell provisioner in a `Vagrantfile.local` in your project that sets up the symlink (since it can't get to the pre-provision script since Gathering Facts fails...).

**Comment by geerlingguy** [comment]
```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "TODO_ADD_INLINE_COMMAND_TO_SYMLINK_HERE"
end

# The absolute path to the root directory of the project. Both Drupal VM and
# the config file need to be contained within this path.
ENV['DRUPALVM_PROJECT_ROOT'] = "#{__dir__}"
# The relative path from the project root to the config directory where you
# placed your config.yml file.
ENV['DRUPALVM_CONFIG_DIR'] = "config"
# The relative path from the project root to the directory where Drupal VM is located.
ENV['DRUPALVM_DIR'] = "vendor/geerlingguy/drupal-vm"

# Load the real Vagrantfile
load "#{__dir__}/#{ENV['DRUPALVM_DIR']}/Vagrantfile"
```

See: http://docs.drupalvm.com/en/latest/deployment/composer-dependency/#create-a-delegating-vagrantfile

**Comment by fsnet** [comment]
@geerlingguy Thanks - the inline shell provisioner does the trick!

**Comment by benjifisher** [comment]
@fsnet, @geerlingguy:

> I did not understand that the path set in ansible_python_interpreter is the same for VM and host.

IIUC, `ansible_python_interpreter` does not affect the control machine (or host, the one running `ansible`). It only affects the target machine. The reason it seems to affect the host machine is that this particular task (from `drupal-vm/provisioning/tasks/sshd.yml`) delegates to the `local` connection:

```yaml
- name: Check if local known_hosts file is present.
  stat: "path={{ known_hosts_path | default('~/.ssh/known_hosts') }}"
  register: known_hosts_file
  connection: local
  become: no
```

So in this case, the control machine is the same as the target machine.

The solution discussed in earlier comments is to force the host and the VM to have `python3` in the same location. You will have to re-fix it all when you upgrade macOS and find that the path has changed, or when you share the project with a coworker who has `/usr/bin/python3` instead of `/usr/local/bin/python3`.

I suggest one of the following alternatives:

1. Upgrade macOS to the current version.
2. Use `ansible_python_interpreter: auto` instead of hard-coding the path.
3. Set `ansible_python_interpreter` as a host variable instead of using the same (hard-coded) value for host and VM.

According to [Interpreter Discovery](https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html) in the Ansible docs, (2) is forward-compatible, since that will be the default in Ansible 2.12. That same page recommends setting `ansible_python_interpreter` "for individual hosts and groups" as in (3).

To implement (3), you would want to set the variable in an inventory, `host_vars` file, or `group_vars` file. I do not see any of these in Drupal VM. :-(

**Comment by geerlingguy** [comment]
@benjifisher - Could you maybe open a new issue and we can discuss what to do there? It seems like this may be causing some issues for other Mac users with older OSes as well.

**Comment by benjifisher** [comment]
@geerlingguy: Done. Issue #2072.
