### ISSUE TITLE
Idea for the vagrant_public_ip

### ISSUE THREAD

**Issue by INirandjan** [geerlingguy/drupal-vm#2043]
## Issue Type
 - Feature Idea

### Your Environment
```
Vagrant 2.2.5
VirtualBox 6.0.10r132072
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
ansible 2.8.4
  config file = None
  configured module search path = [u'/Users/Inirandjan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

### Your OS
 - **macOS** (Catalina 10.15.4)

### Summary
When I load vagrant up. Before the NFS part is loaded. I can go to 192.168.88.88 and see a webpage about Drupal. But when the NFS part is loaded its gone but I need to give permission to let this happen. So when I click 'No' the webpage about drupal on 192.168.88.88 is stil there. And when i click on 'Yes' It says 'File not found' on 192.168.88.88 and the NFS is loaded(So i need to use /etc/hosts/). 
The best part is, it doesnt need to be 192.168.88.88 it can also be the ip of 'vagrant_public_ip'.

So what if I can change the path of the Drupal Webpage to a website that I made. Then I can locally access the Website by the ip used by 'vagrant_public_ip'. So I can access it easily on my phone and test it with others.

Thanks a lot already for everything you made 👍

**Comment by geerlingguy** [comment]
Drupal VM is primarily intended to run sites on your local machine, not necessarily on other devices—though there are many ways to allow access through other services or through specialized Vagrant networking.

The easy custom hostname-based access is one of the things that makes Drupal VM easier to use for many people, so outside of someone manually creating a `Vagrantfile.local` to override the IP and hosts configuration (so they can install Drupal on the VM IP address instead of on the hostname), I do not want to add any features or support centered around the IP address versus the hostname.

Thanks for the suggestion though! You should be able to set something like that up by customizing/overriding the Vagrant configuration, and setting the drupal hostname to the IP address of the machine.
