### ISSUE TITLE
phpMyAdmin part of installed_extras?

### ISSUE THREAD

**Issue by sdemi** [geerlingguy/drupal-vm#2048]
Hi Jeff @geerlingguy ,

Why not make [phpMyAdmin](https://github.com/geerlingguy/ansible-role-phpmyadmin) as part of installed_extras? It's such a common utility and can be incorporated so easily... doesn't even have to be on by default if you dislike it over adminer.

In case I need to do it manually, I will just provide a local requirements.yml file correct? Or do I also need local playbook file to implement adding it?

Regards,
Sergey

**Comment by frob** [comment]
Why do you need phpmyadmin when adminer comes pre-installed?

**Comment by sdemi** [comment]
personal preference

**Comment by geerlingguy** [comment]
@sdemi - Mostly because I do not enjoy using/maintaining phpmyadmin much; for those who need a web UI, I much prefer and recommend adminer. It has caused a lot of breakage in my automation over the years due to greater complexity in installation versus the single-file adminer approach.

I understand that not everyone has the same preference, but it's not _too_ hard to add a post-tasks or pre-tasks file and do an `include_role` to include my `geerlingguy.phpmyadmin` role if desired.
