### ISSUE TITLE
A config.yml file for Drupal 9

### ISSUE THREAD

**Issue by tomo-dev-2018** [geerlingguy/drupal-vm#2057]
I have a question - I didn't know where to put it otherwise, so here goes:
Has anyone got a working solution for a config.yml file that enables for DrupalVM to provision a Drupal 9 site? -  I tried many options, but only got Composer to download a 8.9.1 version.

**Comment by jsidigital** [comment]
I got a Drupal 9 site working by creating a synced folder/site in config.yml that is empty.
After I logged in using SSH and created it there using the usual composer command to create it and set it up from there. After it was created, I backup the freshly created files and database so every time I create a new VM that needs D9 I simply create the site with those files already in it and import the database dump into that site (consider that your config settings would have to match the minimum requirements for a D9 site).

To have it automated as it does D8 sites will most likely come in the next Drupal-VM update. 
Note: I had been doing this method before the actual launch of D9 using the dev version. Have not used D9 since it was released so maybe there may be an easier way. Just sharing how I managed to get a working D9 site working on Drupal-VM.

**Comment by geerlingguy** [comment]
@tomo-dev-2018 - Please follow the progress on this issue: https://github.com/geerlingguy/drupal-vm/issues/2050 — the current defaults are set up in a way that only installs up to the latest Drupal 8 version currently, but that will be fixed soon, and it will be easy to switch between 7 8 and 9.
