### ISSUE TITLE
Add Meilisearch server in installed_extras 

### ISSUE THREAD

**Issue by rzabukovec** [geerlingguy/drupal-vm#2070]
- Feature Idea

### Summary
Hi. In my company, we are developing a new module implementing [Meilisearch](https://www.meilisearch.com/) which is an open-source search engine, similar to Solr or Elastic search.
https://www.drupal.org/project/search_api_meilisearch
- module: [Search API Meilisearch](https://www.drupal.org/project/search_api_meilisearch

I was wondering if there is a possibility and/or interest to include Meilisearch server in installed_extras like there are Solr and Elastic search. If so, how would I approach developing such an addition?

**Comment by geerlingguy** [comment]
@rzabukovec - Thanks for the suggestion! For now, mostly since I don't have any reason to test this new system, I know I would not be willing to put in the work or maintenance effort to maintain an integration in Drupal VM directly.

Instead, if someone wants to use it they could use a post install script or tasks file to install it separately (see http://docs.drupalvm.com/en/latest/extending/scripts/).

Long-term, if Meilisearch becomes a popular alternative to Solr and Elasticsearch, I may consider building an Ansible role for it, incorporating it into Drupal VM, etc. But for now, I would rather not add to the maintenance burden of this project.
