### ISSUE TITLE
issue with vagrant provision

### ISSUE THREAD

**Issue by nishantweb** [geerlingguy/drupal-vm#2071]
### Issue Type

 - Bug Report / Support Request

### Your Environment
vagrant --version -> Vagrant 2.2.9
vboxmanage --version -> 6.1.12r139181

### Your OS

 - **macOS**
MacOS Mojave
version 10.14.5
ansible --version : 
ansible 2.9.10
  config file = None
  configured module search path = [u'/Users/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]

### Full console output

```
admins-MacBook-Pro:drupal-vm admin$ vagrant provision
Installing plugin vagrant-vbguest
Vagrant failed to initialize at a very early stage:

Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  no such name (https://gems.hashicorp.com/specs.4.8.gz)
```

### Summary

I have installed all the required dependencies, but when I try to run "vagrant up" or "vagrant provision" I get this error.

**Comment by geerlingguy** [comment]
@nishantweb - I'm guessing you're running into an issue like this: https://github.com/hashicorp/vagrant/issues/8893

See also: https://github.com/hashicorp/vagrant/issues/8795

This is an issue that could be caused by your network or Internet connection and doesn't have to do with Drupal VM. I would suggest searching in Vagrant's issue queues for solutions or searching on Google to see if it might be related to one of the things on your own network that is blocking access.
