### ISSUE TITLE
How to install Audiowaveform

### ISSUE THREAD

**Issue by jsidigital** [geerlingguy/drupal-vm#2124]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.9
```

### Your OS
 - **Windows** (version 10)

### Full console output
Audiowaveform is not currently installed. Audiowaveform is used to pre-render waveform files for the Audiofield Wavesurfer module. See the Audiowaveform installation instructions: https://github.com/bbc/audiowaveform 

### Summary
I have the audiofield module and need to enable the Wavesurfer library. How does one install Audiowaveform on DrupalVM? Does the config.yml file need to be updated? If so, how?

Thank you.

**Comment by geerlingguy** [comment]
@jsidigital - If there's an apt package for it, you could add it to `extra_packages`: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L234

Otherwise if it requires source compilation, or something like that, you could install it via a post provision hook: http://docs.drupalvm.com/en/latest/extending/scripts/
