### ISSUE TITLE
Recommended version for Vagrant and VirtualBox on a Windows 10?

### ISSUE THREAD

**Issue by bbdata** [geerlingguy/drupal-vm#2152]
### Issue Type

- Bug Report / Support Request
- Documentation Report

### Your Environment

- Vagrant 2.2.14
- VirtualBox 6.1.18

### Your OS

- Windows 10 Pro, Version 1909, Build 18363.1379

### Summary

Is there a recommended version for Vagrant and VirtualBox on a Windows 10 environment?

The documentation just says to download Vagrant and VirtualBox and I often spend more time troubleshooting incompatibility issues than I'd like to.

If there was a way to check what last reported working versions were, I think that would be immensely helpful.

**Comment by geerlingguy** [comment]
Unfortunately I can't generate a 'supported and tested' matrix of versions, just because every version seems to have its own little quirks that affect some users and not others.

I always run the latest versions of both, and have only had to downgrade to an older version maybe twice, for brief periods, due to major bugs in Vagrant or VirtualBox.

**Comment by lexsoft00** [comment]
+1 for this. Maybe just add in the GIT Tag a reference like tested with on windows with:
Vagrant 2.2.14
VirtualBox 6.1.18

Every time I install DrupalVM on a new windows computer I spend half a day to get it working. Wish it was a package install that just works and has included also the VirtualBox with Vagrant.

**Comment by chumkui** [comment]
I have been using DrupalVm for about 5 years now on Windows 10, including debugging with xdebug.  It can be a challenge but less so nowadays.  I use Windws 10 Pro, the latest VirtualBox (currently 6.18) and Vagrant 2.2.10.  The issues relating to a 'clean' vagrant up for me normally relate to the file system.  It is not high performance, but I use `vitrualbox` instead of `nfs`, so:

vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ./your_local_windows_path
    destination: /var/www/drupalvm/your_site_path
    type: virtualbox
    create: true

vagrant_synced_folder_default_type: virtualbox

I have seen issues between Windows machines and the ndis bridge driver - as Jeff says, unlike Macs, there are so many variations of windows kit. 

It is worth creating your own Vagrant box once you do get it running.  This way, whenever, you need a dev box that will 'work', you just create a new project. This stoped the half day scenario lexsoft00 mentioned. 

I am now experimenting with Docker and WSL2.  Seemed really easy for the examples I have tried, is fast, and well integrated with Visual Code - all I need to do now is actually connect to the DrupalVm container i created in a browser...   If I get it all working, I'll post what I did.

**Comment by phizev** [comment]
I've had no issues with running DrupalVM on Windows for the latest 3 versions of Virtualbox, and Vagrant. This is using Virtualbox for shared folders. I've benchmarked SMB, and NFS shares on Windows, Virtualbox shares came out fastest for Drupal performance. It's not the fastest for mass file transfer, but this is irrelevant. Virtualbox shares also have no issues on Windows that I have run into barring symlinks.

I am presently using **VirtualBox 6.1.22**, and **Vagrant 2.2.16**.
