### ISSUE TITLE
Error running "vagrant up", M1 MacBook running Big Sur (NS_ERROR_FAILURE)

### ISSUE THREAD

**Issue by craigweb** [geerlingguy/drupal-vm#2157]
### Issue Type

 - Bug Report / Support Request

### Your Environment

`Vagrant 2.2.15`
`VirtualBox 6.1.18r142142`
`zsh: command not found: ansible`

### Your OS

 - **macOS** (11.2.3)

### Full console output

`There was an error while executing VBoxManage, a CLI used by Vagrant`
`for controlling VirtualBox. The command and stderr is shown below.`
`Command: ["hostonlyif", "create"]`
`Stderr: 0%...`
`Progress state: NS_ERROR_FAILURE`
`VBoxManage: error: Failed to create the host-only adapter`
`VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory`
`VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface`
`VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp`

### Summary

Hi Everyone,

I'm trying to get Drupal VM up and running on a new M1 MacBook running Big Sur and I'm running into an issue :( 

Googling the error I pasted above that I recieve when running `vagrant up` points me to a load of issues where people suggest navigating to "System Preferences > Security & Privacy" and granting VirualBox certain privileges on install, but I was not asked to grant any. 

Other suggestions I've seen talk about disabling SIP within MacOS, but I'm thinking that there surely must be a better way to get round this issue.

Any help with this is greatly appreciated!

**Comment by oxyc** [comment]
VirtualBox does unfortunately not work on the M1 chip and might never work https://forums.virtualbox.org/viewtopic.php?f=8&t=100839.

Parallels and VMWare might already have support but currently Drupal VM doesn't directly support those.

**Comment by oxyc** [comment]
Or @geerlingguy what's the status for using Parallels or VMware with Drupal VM?

**Comment by geerlingguy** [comment]
@oxyc - I used to build VMware fusion base boxes, but because the plugin for Vagrant cost money, along with the license required for VMware to run on my Mac, I found myself paying over $200/year for something I didn't use outside of 'trying to help other people who use it', so it was not worth it to me to keep maintaining/uploading two boxes in parallel.

I wouldn't do anything to hinder support for the other platforms, and most of the configuration would work just the same with another tool, but honestly I have been using Drupal VM a lot less these days (only one personal project is still running on it), and though I don't yet have an M1 Mac (still waiting to see what the 2nd iteration looks like), I've been leaning on native Docker-based environments more :(

**Comment by oxyc** [comment]
We're still heavily using Drupal VM for our WordPress sites (😄) and the few with M1 laptops use ddev for docker environments which works very well. Personally I'm patiently waiting for an invite to GitHub codespaces to see if we can get rid of local environments entirely :)

**Comment by craigweb** [comment]
> VirtualBox does unfortunately not work on the M1 chip and might never work https://forums.virtualbox.org/viewtopic.php?f=8&t=98742.
> 
> Parallels and VMware might already have support but currently Drupal VM doesn't directly support those.

Urgh! I hadn't even considered the CPU being the issue - I'd assumed it was yet another MacOS quirk. 

Thanks for your help anyway @oxyc & @geerlingguy
