### ISSUE TITLE
Why ubuntu

### ISSUE THREAD

**Issue by rpayanm** [geerlingguy/drupal-vm#243]
Hello:

Thank you for give us this awesome project. I wondering why select ubuntu instead debian? Debian I think is solid as a rock and very good choice for servers, IMHO Ubuntu is good for desktop, but is only my opinion, please give me yours considerations.

Greetings.

**Comment by geerlingguy** [comment]
> Debian I think is solid as a rock and very good choice for servers, IMHO Ubuntu is good for desktop, but is only my opinion.

I share the same opinion... in fact I'm much happier running CentOS than Debian or Ubuntu, as I like the overall RHEL approach to things more than Debian/Ubuntu/etc.

The reason Drupal VM defaults to Ubuntu instead of Debian or CentOS is developer popularity/familiarity (same reason why I'm defaulting to Apache for the webserver rather than Nginx—even though I run most of my servers with CentOS + Nginx + FPM). Due to some strange accident of history, most developers and shops seem to use Ubuntu rather than Debian for their base OS for servers. Now, Ubuntu server/minimal isn't bad at all, and is roughly equivalent a distro (in my mind to Debian 7/8) for typical LAMP/LEMP server use.

You can switch the box to any debian 7/8 box, and almost all of Drupal VM will work perfectly—and I'd be happy to fix any little problems that you find with such a setup (I've been considering building my own Debian base box, just haven't had the time yet). I use the exact same base roles on my http://www.pidramble.com/ setup, which runs Drupal 8 on a stack of 6 Raspberry Pis running Raspbian (eqivalent to Debian 7).

You can already switch out the ubuntu 12/14 box for a centos 6/7 box in config.yml, and everything should _just work_.

**Comment by rpayanm** [comment]
Thank you so much for take your time to answer me.
