### ISSUE TITLE
VNC Viewer?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#246]
What is the easiest way to install VNC tools on the VM so I can watch Behat going through its tests?

**Comment by geerlingguy** [comment]
@kevinquillen - By default, there is no window environment (X or otherwise) in Drupal VM, as it uses a headless minimal server install. VNC would be of limited use. Typically, you can run unit tests and headless browser tests (e.g. PhantomJS) inside the VM, but if you want to monitor test runs using a live browser, you'd be better off using Selenium and FireFox on your host machine.
