### ISSUE TITLE
Undefined variable error using example config.yml with nginx 

### ISSUE THREAD

**Issue by peterlavelle** [geerlingguy/drupal-vm#251]
When adminer is enabled, I'm getting the following error when provisioning nginx vhosts

config.yml is much the same as the example provided, apart from the changes below:

```
plavelle@xps:~/drupal-vm$ diff example.config.yml config.yml
34c34
< drupalvm_webserver: apache
---
> drupalvm_webserver: nginx
47c47
< drupal_major_version: 8
---
> drupal_major_version: 7
```

TASK: [geerlingguy.adminer | Set the proper Apache configuration directory (Debian).] *** 
fatal: [drupalvm] => One or more undefined variables: 'apache_vhosts_version' is undefined

FATAL: all hosts have already failed -- aborting

**Comment by geerlingguy** [comment]
@peterlavelle - To fix this, you'll need to set `adminer_add_apache_config: false` (it's currently set to `true` in the default config, I need to fix the config for it though).

**Comment by geerlingguy** [comment]
Apparently the GitHub 'Fixes' detection has changed... because I keep having to manually close these issues. Basically, I've fixed the Adminer role to allow setting of the Adminer filename, so please update your Ansible roles locally (with `sudo ansible-galaxy install -r provisioning/requirements.txt --force`), then make sure you update based on the changes in the example config.

This works better, imo, because now Adminer can be accessed at `adminer.drupalvm.dev` :)
