### ISSUE TITLE
Document how to set this up to use memcached

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#255]
memcached is setup on the server, however there is nothing in the docs about getting the site to use it. There is a page for varnish, why not memcache?

**Comment by oxyc** [comment]
The port would be the default one used, so you only need to add the cache backend settings in settings.php as described in the docs of either `memcache` or `memcache_storage`.

**Comment by frob** [comment]
I did that and the status report still says that memcache isn't running. I logged into vagrant and checked that it is responding with telnet, memcache is responding. This is running nginx.

**Comment by fubarhouse** [comment]
The organisation I work for uses memcache in conjunction with entitycache.
The memcache module for Drupal must be set via the settings.php file.
There's documentation on the Drupal project page if you're interested.

Nonetheless, there should be documentation telling you to visit the Drupal project page.

```
// Memcache configuration (https://docs.acquia.com/cloud/performance/memcached#config)
if (isset($conf['memcache_servers'])) {
  $conf['cache_backends'][] = './sites/all/modules/contrib/memcache/memcache.inc';
  $conf['cache_default_class'] = 'MemCacheDrupal';
  $conf['cache_class_cache_form'] = 'DrupalDatabaseCache';
}
```

Hope this helped :)

**Comment by geerlingguy** [comment]
@frob - I will definitely add a section for Memcached config—I'd like to also make sure to show how to use it with PHP 7 (when that becomes possible) and with Drupal 8 (I think the module's still not ready).

**Comment by geerlingguy** [comment]
Eh... I'd rather actually leave this out of the project documentation, since there are various things that should be more thoroughly documented for edge cases, since Redis is also supported, and since caching is something that needs more than a short, paragraph-long documentation blurb in Drupal VM.

If you're going to use memcached, you need to read through the module's docs and gain a decent understanding of how everything works together, and I don't think this project is the right place to document that.

**Comment by frob** [comment]
What about a blurb in the docs pointing the user to proper documentation on implementing memcache with drupal

**Comment by geerlingguy** [comment]
I think for Memcached, Varnish, Redis, etc.—if you want to use those caching layers, you will need to understand how they work with Drupal regardless, and I'd rather not add any documentation (or pointers) for them specifically, as the setup for Drupal VM is the same as general setup for any other platform/solution (since they're all on localhost).
