### ISSUE TITLE
Make ALL THE THINGS use vagrant_machine_name for the domain

### ISSUE THREAD

**Issue by robdecker** [geerlingguy/drupal-vm#257]
Most of the time I'm running more than one drupal-vm machine at a time since I have to bounce around quite a bit. So when I'm configuring the vm, I will alter the `vagrant_machine_name` to the name of my project, and then edit all the `apache_vhosts` domains (adminer, xhprof, pimpmylog) to match this new `vagrant_machine_name`.

I propose that all the `apache_vhosts` domain names and all the `nginx_hosts` domain names use `vagrant_machine_name` that is set on line 10.

**Comment by geerlingguy** [comment]
The main problem this causes (it was done in the past) is that for those using the Vagrant hostsupdater plugin, their hosts file doesn't get updated because there are Jinja2-style variables in the domain names. If someone can come up with a simple substitution system that will fill in the main domain inside the Vagrantfile so the auto hosts still work, that would be a good solution.

**Comment by robdecker** [comment]
There are six hosts plugins at https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Plugins#etchosts-approach but I do not know if any would work in this scenario.

**Comment by frob** [comment]
We could use gulp or npm scripts to generate the config from a simplified config.

**Comment by oxyc** [comment]
There's an open PR for this issue at https://github.com/geerlingguy/drupal-vm/pull/184.

**Comment by geerlingguy** [comment]
This is fixed in #410 - Thanks for all the great work on this!
