### ISSUE TITLE
Is there a way to add an "host ip"?

### ISSUE THREAD

**Issue by scottalan** [geerlingguy/drupal-vm#267]
I've been using [Kalastack](https://github.com/kalamuna/kalastack) for some time and decided to switch over and try this out. I love the .yaml configs and the ability to customize webserver, php, etc.. One thing I really liked to be able to do was point my install to a local database instance. I'm not really sure how this works, or I would just implement it myself, but they are adding an additional ip: https://github.com/kalamuna/kalastack/blob/3.x/default.config.json#L14
Is there a way to do this in *drupal-vm*?

**Comment by geerlingguy** [comment]
Do you mean you want to install Drupal on MySQL running on your host workstation (instead of inside the VM configured by Drupal VM), then point the Drupal site that's running inside the VM to the MySQL instance running on your host?

If so, as long as you have MySQL listening via TCP on your host, the IP address for it can be found by logging into the VM (`vagrant ssh`), then enter `ipconfig` to get the interfaces. The host is the gateway on the main eth interface (I think, would need to verify).

Then just tell Drupal in settings.php to point to _that_ IP address instead of 127.0.0.1.

If you're asking something wildly different (and I'm interpreting this way wrong), please let me know.

**Comment by geerlingguy** [comment]
Also, just to clarify, the whole premise of Drupal VM is that _everything_ is done inside the VM itself, to keep things nice and clean, and make completely portable, configurable, and re-deployable environments :)
