### ISSUE TITLE
Upgrading MySQL version?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#270]
Is it possible via config.yml to upgrade the version of MySQL?

I am looking to upgrade to at least 5.7.7.. which still appears to be listed as a dev release and not a GA release.

http://dev.mysql.com/downloads/mysql/

The reason I am asking is I want to explore possibilities of using JSON data types in Drupal 8, without having to install Postgres. I initially did some R&D with Postgres, but it is quite a behemoth compared to MySQL.

Ref: http://mysqlserverteam.com/json-labs-release-overview/

**Comment by geerlingguy** [comment]
Anything concerning upgrade / changing versions of MySQL should be addressed in upstream repos, like my `geerlingguy.mysql` role; otherwise, if there's a simple way to get later versions (e.g. adding a separate apt repository for the latest GA release), then that could be accepted—that's how I do PHP releases.

However, I don't plan on supporting non-stable versions of MySQL explicitly; PHP yes, MySQL probably not, unless there's some simple way.
