### ISSUE TITLE
Include Drupal Generator

### ISSUE THREAD

**Issue by nateswart** [geerlingguy/drupal-vm#288]
I'd love to see this project included as one of the tools available in DrupalVM:

http://drupalgenerator.com

@geerlingguy ... you can imagine what I want to leverage this for ;)

**Comment by geerlingguy** [comment]
Would this be more of an app that could be installed on top of Drupal VM? I don't see immediately how this would be better than that site itself...

**Comment by fubarhouse** [comment]
@nateswart I'm also quite curious about this one, I assume you're wanting this to be contained in a virtual host which ties results into a Drupal 8 install?

Seems like a fantastic idea, but I assume a Drupal module will eventually come to light from the functionality...

**Comment by geerlingguy** [comment]
Agreed with @fubarhouse and unless you can come up with some reasoning behind having Drupal Generator a base feature of Drupal VM instead of something that may just be wrapped up in a Drupal site running on top of Drupal VM, or running standalone as a docroot inside Drupal VM, I'm going to leave this ticket closed.

**Comment by fubarhouse** [comment]
I wanted to add that a GUI is in fact planned for the Drupal Console, so you won't have to wait too long for similar functionality.
