### ISSUE TITLE
[suggestion] Update GuestAdditions

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#295]
In the spirit of support, I'm finding myself annoyed by this message which comes up occasionally:

No biggie, I mean I would do this myself but honestly I don't know how to start with this process.... that may change...

````
GuestAdditions versions on your host (5.0.0) and guest (5.0.4) do not match.
````

Followed by a heap of packages downloading, excess information in my regard.

Feel free to ignore this, it is just a suggestion.

**Comment by geerlingguy** [comment]
Make sure you've upgraded to the most recent version of VirtualBox; it looks like you're running 5.0.0, but the guest additions inside Drupal VM's base box (geerlingguy/ubuntu1404) are currently for 5.0.4.

I need to update the base boxes again because the current VirtualBox version is 5.0.8 (IIRC), but the messages you're seeing are because the `vagrant-vbguest` plugin is seeing a version discrepancy between the base box and your version of VirtualBox.

**Comment by fubarhouse** [comment]
That must be it, I'm still using 12.04  as I've been told to, and unless I can find a way to forcibly disable the plugin I can't guarantee all the machines I look after will build without error.

Thanks anyway :)

**Comment by geerlingguy** [comment]
Sounds good, and sorry about that! The geerlingguy/12.04 box is also updated periodically, so it should be up to date sooner or later with 5.0.8 (or whatever is current at the time).

**Comment by fubarhouse** [comment]
Glad to hear, thanks!
