### ISSUE TITLE
What if port 80 is already in use?

### ISSUE THREAD

**Issue by dale-c-anderson** [geerlingguy/drupal-vm#304]
I have a lot of stuff going on with my development box. Port 80, 8080, 8081 etc are already in use by other services & vms. Where can I specify alternative ports to use for apache/nginx?

**Comment by opdavies** [comment]
There's an upstream `apache_listen_port` variable that can be used for Apache.

Nginx, I think, would be set as part of `nginx_vhosts`.

**Comment by geerlingguy** [comment]
@opdavies is correct; you can change the port in those respective areas of `config.yml` and then the VM will listen only on those ports.

However, if by 'development box' you mean your local workstation, then Drupal VM's defaults won't override anything on the `localhost` port 80, only on the VM/interfaces configured through Vagrant and VirtualBox.

I have a few services I run locally over port 80 for testing as well, but multiple Drupal VM instances don't interfere with those since each instances is on a separate virtual interface and has a separate private/local IP address.

**Comment by dale-c-anderson** [comment]
Mind. Blown.

**Comment by geerlingguy** [comment]
See how awesome VM-based development can be? :D

**Comment by opdavies** [comment]
:smile:
