### ISSUE TITLE
Why generate so many drush aliases

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#309]
From installing a single Drupal site onto a single Drupal VM instance, I count 5 Drush aliases are created. Why?

This is especially frusterating for me because I am duplicating the domain with the vm machine name so I end up with a drush alias that looks like this 

```
project-name.client-name
project-name.client-name.adminer.project-name.client-name.dev
project-name.client-name.pimpmylog.project-name.client-name.dev
project-name.client-name.project-name.client-name.dev
project-name.client-name.xhprof.project-name.client-name.dev
```

You could say, just don't do that. But thin I have to have three custom names to put into my scripts, when the problem is really that a bunch of non-drupal stuff gets aliased.

**Comment by geerlingguy** [comment]
It may be possible to change the way drush aliases are generated so it's not quite so verbose... but to be honest, I'm fairly used to having 50+ active alias files in my `~/.drush` folder with something like 200 active drush aliases when I run `drush sa`... depending on how many sites you develop, it's the name of the game :(

**Comment by geerlingguy** [comment]
@frob - Also, one other tip for any users who don't want Drupal VM managing alias files _at all_: you can set `configure_local_drush_aliases` to `false` inside `config.yml` and Drupal VM won't create any local drush alias files.

**Comment by frob** [comment]
Oh yeah, I get that. I have five other sites from drupalvm currently and all the others from before I started using drupalvm. My question is more of why do we need an alias for pimpmylog and xhprof? It looks like it is just making an alias for any vhost that is defined.

**Comment by kostajh** [comment]
@geerlingguy one potential way to address this would be to generate Drush aliases based on the `id` specified in the sync folders section. This would provide for more typeable aliases too, e.g. `@drupalvm.example` instead of `@drupalvm.local.example.com`. And it would solve @frob's problem because aliases would only get generated for any entry in the synced folders section where and `id` is specified.

**Comment by frob** [comment]
@kostajh, would that work for multisite installations?

**Comment by geerlingguy** [comment]
@kostajh - That wouldn't work for multisite, and it would also be extremely difficult (if not impossible) to map IDs to hostnames, which Drush needs in the alias file to make sure the commands run correctly with the right environment :(

I think this is an intractable problem with automated drush alias creation, because I have to key off something, and the most accurate key would be the list of hostnames. Going to close this issue for now... but if someone can think of a better solution, please let me know!

**Comment by oxyc** [comment]
For reference `xhprof`, `adminer`, `pimpmylog` no longer generate aliases https://github.com/geerlingguy/drupal-vm/pull/408

**Comment by geerlingguy** [comment]
@oxyc++
