### ISSUE TITLE
How to update drupal 8 on drupalvm box?

### ISSUE THREAD

**Issue by sprklinginfo** [geerlingguy/drupal-vm#324]
I just run 'vagrant up' to have http://drupalvm.dev/ up now. I want to update the drupal 8 to be newly released version. I did the following:
1) on my local terminal, issued "vagrant ssh"
2) then I issued 'drush up' uner '/var/www/drupalvm/drupal' on the vagrant box. Here is message I got:
Update information last refreshed: Thu, 11/26/2015 - 18:19
 Name    Installed Version  Proposed version  Message                
 Drupal  8.0.0-dev          8.0.0-dev         Unable to check status 

On "http://drupalvm.dev/admin/reports/updates" page it clearly says there is a new version released on 2015-nov-19. So how do I update drupal 8 to the latest version?

Thanks!

**Comment by geerlingguy** [comment]
In general, you will need to replace the Drupal 8 core files with new copies from the latest version: https://www.drupal.org/node/1494290

However, Drupal VM installs Drupal 8.0.x-dev by default (meaning you're installing the bleeding edge, or HEAD). This can cause update status (in the UI) and drush (via command line) to have trouble checking the update status, and you should typically only use HEAD/8.0.x-dev (the default) when doing testing, core debugging, or building modules for contrib work.

Otherwise, you should do a `vagrant destroy` to destroy the VM, then change the `drupal.make.yml` file to point to a specific version of Drupal 8 core, e.g. 8.0.0 or 8.0.1 (when it comes out), then `vagrant up` to build the VM with that specific point release.

In general, you can use a makefile-based workflow (every time you want to update, update all the versions inside the `drupal.make.yml` file, then rebuild the entire drupal docroot directory) with Drupal VM, but how you manage the building of the Drupal codebase is up to you.

Another option is to have a separate git repository for Drupal 8, and you manually download Drupal core every time there's a new version, then overwrite all the existing files with the new version, then commit that to your repository and run database updates.

There are dozens of other ways to manage and update a Drupal installation, but Drupal VM just gives some sane defaults and leaves the actual long-term site usage up to you.

**Comment by fubarhouse** [comment]
* `drush sa` to give a list of site aliases.
* `drush @alias pm-updatecode`
