### ISSUE TITLE
ansible-galaxy install timing out

### ISSUE THREAD

**Issue by steve65140** [geerlingguy/drupal-vm#339]
Hi,

I've just tried my first attempt to "Build the VM" as per your excellent documentation:

sudo ansible-galaxy install -r provisioning/requirements.yml --force

After successfully downloading a number of roles I got the error:

downloading role 'php', owned by geerlingguy
- sorry, geerlingguy.php was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.

This seems to be the same problem as issue #303 but I hadn't installed anything like the number of roles mentioned in the issue.

When I then tried:

sudo ansible-galaxy install -r provisioning/requirements.yml --force --ignore-errors

Five roles seem to be downloaded again then I get:

- downloading role 'drupal-console', owned by geerlingguy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()

Any thoughts on what I should try to restart the install?

Cheers,

Steve.

**Comment by geerlingguy** [comment]
I'm thinking this is an upstream issue. I'm going to try to do more testing on a fresh new Fedora install in a bit, and check out what's happening with the packets.

**Comment by geerlingguy** [comment]
This problem seems to have gone away in the past month or so, after Galaxy 2.0 was released. I'm thinking Galaxy itself must've been the problem, but it seems to no longer be an issue.

**Comment by luckyape** [comment]
For me this problem was being caused by a malformed url in 
/Library/Python/2.7/site-packages/ansible/galaxy/api.py

ln 185 
`                url = '%s%s' % (self.baseurl, data['next'])
`
output a url like:
"https://galaxy.ansible.com/api/v1https://galaxy.ansible.com/api/v1/roles/432/versions/?page=2&page_size=50"

The obvious fix for this instance being:

`                url = '%s' % ( data['next'])
`
I have no idea that that change breaks, but it allows the provisioning to finish.

**Comment by geerlingguy** [comment]
@luckyape - see #482
