### ISSUE TITLE
Add documentation for SSL support

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#349]
Did a quick search of the docs and couldn't find anything on https, is it possible to setup a VM with http/https support? I want to be able to use a self signed cert and something like securepages to test a local Drupal 7 installation with.

**Comment by geerlingguy** [comment]
See https://github.com/geerlingguy/drupal-vm/pull/162 for a quick example—I really need to add more info to the docs! Also, check out the documentation in the `geerlingguy.apache` role for more info on SSL config.

**Comment by tripper54** [comment]
Following #162 I have SSL enabled, but Apache is just serving php files as text rather than passing them to FPM. Can you give me any pointers as to what I'm doing wrong? Thanks!

**Comment by oxyc** [comment]
@tripper54 that's because Drupal VM recently made a switch to PHP-FPM which requires some changes in your configuration files. You can find instructions in the [release notes](https://github.com/geerlingguy/drupal-vm/releases/tag/2.2.1). If you prefer not switching you can also find instructions on how to continue using `mod_php` [here](https://github.com/geerlingguy/drupal-vm/blob/4da53e4a5794062c9aabe1cef3724c0ab3a80e3c/example.config.yml#L204:L207). Also #394, #393

**Comment by oxyc** [comment]
This can now be closed https://github.com/geerlingguy/drupal-vm/pull/438.
