### ISSUE TITLE
Use ansible_local provisioner

### ISSUE THREAD

**Issue by joshrickert** [geerlingguy/drupal-vm#355]
Vagrant's latest 1.8 release adds an [ansible_local](https://docs.vagrantup.com/v2/provisioning/ansible_local.html) provisioner which should be able to replace the functionality of the JJG-Ansible-Windows script.

**Comment by geerlingguy** [comment]
Most likely. That will save some maintenance effort for sure! I'm still trying to get some VMware licensing issues sorted out so I can try out Vagrant 1.8.0 without it blowing up my environments.

**Comment by geerlingguy** [comment]
Working on this now.

**Comment by geerlingguy** [comment]
Works great! Only issue—which is only _sort of_ an issue, because it has plusses and minuses—is that every time you run `vagrant provision`, all the ansible roles are updated via `ansible-galaxy install -r [roles file] --force`.

Meaning every provision (if you don't have Ansible installed locally) will take 1-2 extra minutes. But I guess it's even more motivation to install Ansible on your host if you're on Mac or Linux, or switch to Mac or Linux from Windows if not :P
