### ISSUE TITLE
`vagrant up` fails: Unable to restart webserver

### ISSUE THREAD

**Issue by dalin-** [geerlingguy/drupal-vm#377]
This all of a sudden started happening.  I rolled back to the code that I had yesterday and the problem still happens:

```sh
NOTIFIED: [geerlingguy.mysql | restart mysql] *********************************
changed: [annenberg]

NOTIFIED: [geerlingguy.php | restart webserver] *******************************
failed: [annenberg] => {"failed": true}
msg: no service or tool found for: apache2

FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart webserver] *******************************
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart webserver] *******************************
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dave/playbook.retry

annenberg                  : ok=141  changed=69   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
If I visit
http://[project url]/
I get a 502 Bad Gateway error
but
http://[project url]/CHANGELOG.txt
works just fine.

I'm running the latest stable of Drupal VM
[config.yml.txt](https://github.com/geerlingguy/drupal-vm/files/92272/config.yml.txt)

 (2.1.2)
Attached is my config.yml

**Comment by geerlingguy** [comment]
It looks like you're using `drupalvm_webserver: nginx` but it's trying to restart apache2 (`msg: no service or tool found for: apache2`).

For now, can you add the following to config.yml: `php_webserver_daemon: nginx` and see if that works for you?

**Comment by geerlingguy** [comment]
Or actually, you could instead add the variable `php_enable_webserver: false`.

**Comment by fubarhouse** [comment]
I've been having issues with apache2 on the system I maintain since a complete rebuild of the original system. I can't identify when the change happened but switching to nginx has fixed it - had some work to do to make the system compatible but that was fun...

Here's the code output of trying to start apache2, note that I haven't changed apache2 in any way on this system.

````
AH00557: apache2: apr_sockaddr_info_get() failed for 20151103075746
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
````

**Comment by geerlingguy** [comment]
Interesting... could be that the domain isn't in the hosts file; if you set the vagrant domain different than the main drupal site domain, then that can happen. But even so, Apache should still at least boot.

**Comment by dalin-** [comment]
I did a bunch of testing with nginx and apache and switching to HEAD resolved my problems.

**Comment by geerlingguy** [comment]
Great! Thanks for letting me know how you got it fixed.

**Comment by geerlingguy** [comment]
I'll be tagging a new release soon.

**Comment by cartick90** [comment]
![capture](https://cloud.githubusercontent.com/assets/26068984/24684328/368978b6-1973-11e7-87b6-f931057d17a2.PNG)
got stuck up can help me out

**Comment by fubarhouse** [comment]
@cartick90 What version of DrupalVM are you using?

That doesn't look like an implementation of DrupalVM or Geerlingguy's Apache role.
I suspect misconfiguration is the cause of what you're doing here...

It might be worth using this role, instead of custom tasks:
- https://github.com/geerlingguy/ansible-role-apache

The advantage of using an established role is configuration, what you're doing there is simply installing the package and expecting the defaults to work exactly as a working server... I'm afraid you'll never win there...

**Comment by cartick90** [comment]
Thanks for help @fubarhouse.
