### ISSUE TITLE
Client time and date out of sync

### ISSUE THREAD

**Issue by alesrebec** [geerlingguy/drupal-vm#382]
The problem happens when you put the host machine to sleep.
When you wake it up and check the date in Vagrant client machine the date continues from the date when you put it to sleep.  
I learned that the hard way because all my commits to git are actually weeks away now!
Any solution that we can put in vagrant configuration file that can do this time update once in a while?

**Comment by geerlingguy** [comment]
@alesrebec - It looks like there _is_ a way to change how often VirtualBox does a time sync within the guest, so this problem would clear up a little sooner (http://stackoverflow.com/a/19492466/100134), but since that solution isn't easy to apply across different providers (VirtualBox, VMware, and Parallels), and since it's a little arbitrary as to how often the ideal timesync would be, I'm going to leave it at the default (which I think is 20 minutes).

For most devs, the git work is done outside the VM itself, so this wouldn't be an issue... but one other workaround you could use is to add a cron job to `drupalvm_cron_jobs` to force a re-sync within the VM every minute, 5 minutes... something like that.

**Comment by alesrebec** [comment]
Thanks for the answer @geerlingguy.
You mentioned that there's a default time sync on 20 minutes? It doesn't work for me because my VM is behind for days! That solution in SO doesn't work for me. Tried it before posting an issue here. Is there something I'm missing out?

Cron job seems a good workaround.. You meant calling "ntpd restart"?

**Comment by geerlingguy** [comment]
@alesrebec - Yeah, something along those lines: http://superuser.com/a/123981/80658

**Comment by josephdpurcell** [comment]
Following https://github.com/geerlingguy/drupal-vm/issues/1097#issuecomment-271213478 I believe has solved the problem for me.
