### ISSUE TITLE
Add support for unison

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#389]
Adding support for [unison](http://www.cis.upenn.edu/~bcpierce/unison/) would be nice. 

I recently found myself in a spot where I couldn't use nfs and doing rsync in vagrant for drupal development is a mess (because its one way).

**Comment by geerlingguy** [comment]
I'm not sure I want to add unison support (see https://github.com/dmatora/vagrant-unison for a vagrant plugin to add it), as the few times I've used it, the entire experience was suboptimal, and using SMB on windows and NFS on Mac/Linux almost always is better for the DX.

I'm still holding out in hopes that https://github.com/mitchellh/vagrant/issues/3062 is someday resolved, so we get bidirectional rsync, because that would be the best of all worlds, but it's been a long time, and that doesn't seem to be a top priority :(

I'm going to close this, but if someone can think of a way to add unison support (e.g. if the plugin's installed, add a few lines to Vagrantfile iff a unison sync directory is specified in config.yml) without harming usability or making a bit more mess in the Vagrantfile, I'd be willing to think about it.

I would _not_ want to add it as a default in any way, and none of the config would go into the example config file—this would be more a 'power user' feature that we could document in the docs site somewhere.

**Comment by frob** [comment]
I agree that this would not be a default in anyway. I wouldn't want this unless all we would have to do is change the share from 'nfs' to 'unison' for a required DX. (That is if it is installed on your host allow it to be configured and used on the guest). This would likely also require a new ansible-role to install unison to happen before we could even start here. I am not going to do that any time soon.

I was thinking more of a [manual approach](https://keylocation.sg/blog/vagrant-and-unison-without-a-plugin/) and avoiding the vagrant plugin, for two reasons:

 - It hasn't been updated in a long time and there are pull requests just sitting there.
 - The README has a section about "When" the Unison DB get corrupted. As in not If but When.

I would rather use the rsync-pull that you linked to, but I doubt it will ever get into vagrant.

**Comment by miloskroulik** [comment]
There's a new version of the plugin at https://github.com/dcosson/vagrant-unison2. I did some light testing and it worked fine, but more would be needed.
