### ISSUE TITLE
Mark current release as not working

### ISSUE THREAD

**Issue by bergstar** [geerlingguy/drupal-vm#423]
After spending a few days on Windows 7 PC at home and Macbook Pro at work and working my way down the list of:
- drupal-vm-2.1.1
- drupal-vm-2.1.2
- drupal-vm-2.2.0
- drupal-vm-2.2.1
- _and_ drupal-vm-master

Running on:
- vagrant_1.7.4
- vagrant_1.8.1
- VirtualBox-4.3.36-105129-Win
- VirtualBox-5.0.12-104815-Win
- VirtualBox-5.0.14-105127-Win

All with stock config files with only _local_path_ edited.

With exiting reading form #160 #372 #361 etc

I have a pretty strong experience that drupal-vm is simply not working at this stage - especially on Windows and not nearly "out of the box" on OS X.

Maybe it should be temporary marked as such? Would also be great to point new users to working cocktail of drupalvm+vagrant+virtualbox versions

**Comment by geerlingguy** [comment]
@bergstar - I'm currently running master on three Macs - testing in both VMware and VirtualBox, tested with both Ansible 2.x and 1.x, and Vagrant 1.7.4 and 1.8.1—I can't get things to break in any situation there.

On Windows, right _after_ Vagrant 1.8.1 and Drupal VM 2.2.x were released, Ansible 2.0.0 was released, which then broke 1.8.1—but only on windows or in environments where you don't have Ansible installed locally (e.g. on Mac `brew install ansible`, or Mac/Linux `pip install ansible`, etc.).

Both Vagrant _and_ Ansible have fixes _already committed_, and they have been... for weeks... and I'm just waiting until Vagrant 1.8.2 and Ansible 2.0.1 are released to do any futher large changes to Drupal VM, just because the experience is broken right now.

These are the two hot issues:

  - https://github.com/mitchellh/vagrant/issues/6793
  - https://github.com/ansible/ansible-modules-core/issues/2473

And the latter issue doesn't affect 99% of Drupal VM users.

So really, once Vagrant 1.8.2 is released, this is a complete and total non-issue. This has happened in the past, and will happen again—when we build complex systems with many dependencies (a necessity in this day and age), some things break, they're totally out of our control, and all we can do is lobby for a new release.

For Vagrant at least, all the issues tagged '1.8.2' milestone are already fixed, so I have no clue why no new release has been tagged :(

**Comment by geerlingguy** [comment]
Also as a reminder—on Mac OS X/Linux, if you don't install Ansible locally, then it will have the same problem as on Windows: Vagrant will install Ansible but not recognize it's installed in the VM. So for Mac/Linux users, install Ansible locally. It's better/faster that way regardless :)
