### ISSUE TITLE
config.yml changes not taking effect after vagrant provision or vagrant reload --provision

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#432]
I'm running drupal-vm @ 2.2.1

I originally thought I wanted to keep XDebug on for all development VM's but now I'm thinking I want to have it off by default. 

I was surprised that to still see xdebug in my php -i after commenting out xdebug in the installed extras section, and setting all of the xdebug configuration values at the bottom to zero. I thought that running `vagrant provision` would apply the config changes and then I tried `vagrant reload --provision` and yet I'm still seeing xdebug as enabled after I ssh into the box. 

I'm hoping there is a better way to solve this other than running `vagrant destroy` and then `vagrant up` again. 

` php -i | grep xdebug`

```
xdebug
xdebug support => enabled
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => Off => Off
xdebug.default_enable => Off => Off
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.extended_info => On => On
xdebug.file_link_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.halt_level => 0 => 0
xdebug.idekey => PHPSTORM => PHPSTORM
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => On => On
xdebug.profiler_aggregate => Off => Off
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /tmp => /tmp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_autostart => Off => Off
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => Off => Off
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => localhost => localhost
xdebug.remote_log => /tmp/xdebug.log => /tmp/xdebug.log
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.scream => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3
```

```
installed_extras:
  - adminer
  - drupalconsole
  # - mailhog
  - memcached
  - nodejs
  - pimpmylog
  # - redis
  - ruby
  - selenium
  # - solr
  # - varnish
  # - xdebug
  - xhprof
```

And 

```
# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 0
php_xdebug_remote_connect_back: 0
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
```

**Comment by geerlingguy** [comment]
Unfortunately this _is_ something that requires a `vagrant destroy` and `vagrant up` to fix, at least for the time being.

The problem is that only certain platforms support things like a2enmod and easy php module enabling/disabling, and I don't want to get down so far into the weeds as to add tasks that undo installations (effectively), especially for things like development tools.

`php_xdebug_default_enable` set to `0` means that it's present and runs with PHP, but doesn't do anything, though I hear it can cause issues with XHProf if you have both installed at the same time. My answer at this time is to either rebuild the VM (I do this myself sometimes 10+ times per day when doing intensive debugging/profiling), or to log in and manually delete the symlink in the PHP config folder.

I've considered even commenting xdebug from the default `installed_extras` list before just because it's the only PHP extension that seems to annoy developers frequently, and it could be an opt-in rather than opt-out that way.

Maybe I should just do that. It wouldn't solve the issue you're mentioning (needing to rebuild the VM, or log in and delete the symlink then bounce PHP), but it would at least make it so the devs who use xdebug do so intentionally.
