### ISSUE TITLE
More PHP versions

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#437]
Drupal 7 works with all PHP versions but it seems best to stick with php 5.3 because of some modules. Is it possible to add PHP 5.3 and 5.4 to the list of versions in the VM?

**Comment by geerlingguy** [comment]
@mooru - Since those versions are [no longer supported by the wider PHP community](http://php.net/supported-versions.php), I've decided to not maintain support for them either. You can modify Drupal VM's configuration to not use one of the repositories to get an updated PHP version, though, and use either Ubuntu 12.04 or CentOS 6 to get a PHP 5.2 or 5.3 version... but I don't recommend it.

I would recommend instead finding out which modules don't work with modern PHP versions and getting those modules updated or at least posting an issue on Drupal.org requesting they be fixed.
