### ISSUE TITLE
stdin: is not a tty

### ISSUE THREAD

**Issue by sinasalek** [geerlingguy/drupal-vm#467]
I encountered this error during vagrant up "stdin: is not a tty"
I didn't cause any detectable problem but just for the record i'm adding two of the solutions i found :
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/517
https://coderwall.com/p/qtbi5a/prevent-stdin-is-not-a-tty-error-in-vagrant

**Comment by geerlingguy** [comment]
Since this only shows up on Windows / when Ansible isn't installed, I hadn't seen it in a very long time. It is slightly jarring to see a red message before all the green starts showing up, but since there are a lot of other red messages (warnings, nothing's breaking during the provisioning), I'm not worried about it, and would rather not add any additional shell provisioner just to fix a warning.

Thanks for referencing the upstream changes—the main issue highlights all the details (and why it's not a big deal) here: https://github.com/mitchellh/vagrant/issues/1673
