### ISSUE TITLE
Ubuntu login

### ISSUE THREAD

**Issue by alisonjo2786** [geerlingguy/drupal-vm#477]
I've just finished the Quick Start Guide, and I'm attempting to start up my new VM from VirtualBox, but I don't know what the Ubuntu login is :(

![virtualbox_packer-ubuntu-14 04-amd64_1456524383969_49308_26_02_2016_18_27_56](https://cloud.githubusercontent.com/assets/2660348/13368246/b64f5a2a-dcb6-11e5-9229-68733d828fce.png)

**Comment by geerlingguy** [comment]
It looks like you may have used VirtualBox and installed a new Ubuntu virtual machine.

Drupal VM builds its own fresh VM, so all you need to do (after shutting down the VM that you had built with VirtualBox) is, inside your terminal (or Cygwin/Cmder on Windows, or even PowerShell or Git Bash/Git Shell), cd into the Drupal VM download directory, then run `vagrant up`.

You shouldn't ever need to use VirtualBox directly for anything.

Also, if you're still having any trouble, please post what OS you're using, what happened to get you to the point where you are, etc.—it's hard to diagnose any issues just from a screenshot.

**Comment by oxyc** [comment]
If you want to open a shell on the VM you can SSH into it using `vagrant ssh`. As @geerlingguy said there's no need to use VirtualBox, everything is done through Vagrant.

Ofc there is still a way you could access it through the VirtualBox GUI but that's probably not what you're actually look for. If you for some reason really _do want_ to, the username is `vagrant` and there should be a private key generated in `~/.vagrant.d/insecure_private_key` (I'm not sure the path is the same on Windows).

Unfortunately I'm not sure how Windows users generally use the VM, but personally I never even SSH into my VMs. After having run `vagrant up` the first time everything is already configured so the only thing I do 95% of the time is let my code be transfered through the shared folder. I guess front-end tooling might be more difficult on Windows though so that might be a reason for you to SSH into it.

**Comment by geerlingguy** [comment]
Please open a new issue if you're finding any other issues with the setup process; thanks!

**Comment by alisonjo2786** [comment]
Thank you both for your help!  I will do better with providing key details when I submit issues in the future.

I have used VB in the past for Drupal development, and I did everything inside my VMs, so I imagined this as the same concept, but with everything set up for me so I don't have to configure my LAMP environment, etc., on my own.  In other words, I imagined that after getting myself set up with Drupal VM, I would be in the same sort of position as if I manually created a VM in Virtual Box and set up LAMP and everything, and then just carried on with my normal Drupal stuff, inside the VM -- with the additional functionality of portability/repeatability of the environment.  I hope I'm making some sense :)

I probably misunderstood the intended use of this tool and was trying to make it do things it wasn't meant to do -- but I'm going to keep at it at least a little while longer.  Again, thank you so much for your prompt and patient support!

**Comment by alisonjo2786** [comment]
For future readers, I found insecure_private_key in `C:\Users\alison\.vagrant.d\`.

**Comment by oxyc** [comment]
@alisonjo2786 you could still use it with your old workflow. To enable GUI mode for the VM you can create a `Vagrantfile.local` next to the regular `Vagrantfile` with this content:
```ruby
config.vm.provider :virtualbox do |v|
  v.gui = true
end
```

If you have that and run `vagrant up`, the VirtualBox GUI should open.

**Comment by alisonjo2786** [comment]
That's awesome, thank you so much, @oxyc !

Question about the insecure_private_key -- I have used RSA keys for authentication when connecting via SSH, but I'm not sure how to do it in my Ubuntu Login situation, or is that not what you meant?

**Comment by oxyc** [comment]
I've never tried it but I assume if you create the `Vagrantfile.local` once you run `vagrant up` it will open a session with the user already signed it.

I'm not sure how to do this through VirtualBox directly.

**Comment by alisonjo2786** [comment]
As far as I could tell it did not start a session, but, I did find that the Ubuntu login is simply vagrant / vagrant, so that's something.

Now I have been welcomed and presented with a simple Ubuntu prompt:
`vagrant@ubuntu:~$`
so that's something!
