### ISSUE TITLE
Launch VM after Login

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#502]
This is pretty much a documentation issue but I could see other people wanting to do the same thing. This can be done on mac creating a launchd plist file and dropping it into your /Library/LaunchAgents folder.

Put together a blog post here:
http://justinlevi.github.io/blog/2016/03/06/vagrant-virtualbox-mac

I'm also using Transmit with an Applescript (app) to mount the vm as a drive. I couldn't figure out how to get this to fire after the vm is provisioned though...

**Comment by geerlingguy** [comment]
I like the idea; however, I'm not sure having the VM start up on system boot is an 80% use case; I typically leave my Mac up (either asleep or sitting idle) for days, sometimes weeks at a time, and I only bring up the VM when I'm doing active development work (since it takes just 20s or so to bring it up, it's not a huge deal to me).

I will definitely point people to your blog post; it outlines a few really nice ideas; especially auto mounting the disk on a Mac; some people would probably like to do that but don't know how.

Also, if you aren't already, you should look into getting your Drupal-specific blog posts aggregated on Drupal Planet so they're automatically shared with the wider community: https://www.drupal.org/planet/guidelines

**Comment by justinlevi** [comment]
Yeah, I can definitely see my solution being an edge use case. This was basically me just obsessing about automating something and figuring out how to use launchd correctly. Total A.D.D. distraction while trying to figure something else out ;) 

As a side note, I'm working on my windows box today and wanted to see if there was a way to map an SFTP server as a network drive and came across this free software
https://www.eldos.com/sftp-net-drive/download-release.php

Seems to work really well.
