### ISSUE TITLE
PHP 7 + memcached

### ISSUE THREAD

**Issue by damienmckenna** [geerlingguy/drupal-vm#512]
An article for installing memcached with PHP 7 was updated to say that packages are available that should take the pain out of it:

* https://serversforhackers.com/video/installing-php-7-with-memcached

Maybe it's time to update the default to PHP 7? :)

**Comment by geerlingguy** [comment]
To expand, it looks like at least in Ondrej's repo for PHP 7, there's a `php-memcached` package... I'll have to test. And also see what the status/support is on the RHEL side before officially moving over to PHP 7.

I'm doing some more benchmarking this week, and for Drupal 8, PHP 5.6 is literally 2-2.5x slower than PHP 7. There is no reason any new stuff should be built on 5.6 anymore, and anyone and everyone should upgrade as soon as possible. I've never seen a software upgrade make such a dramatic improvement!

**Comment by geerlingguy** [comment]
I think I'm going to close out this issue for now... the time isn't quite right to _default_ to 7.0, mostly because there are still enough edge cases that are hit where I don't think 80+% of Drupal VM users would have as seamless an experience.

The performance boost is amazing (discovering new tidbits on that every day), and type hinting, etc. are such huge reasons for me to push for 7 adaption ASAP... but until Ubuntu 16.04 stabilizes (hopefully defaulting to 7), and until a few more libraries stabilize (I'm looking at you, not-quite-finished-memcached, xhprof/alts, xdebug, new relic, etc.), I'm going to hold off and let people refer to the docs.
