### ISSUE TITLE
Suggestions for handling collisions of drush aliases with Acquia

### ISSUE THREAD

**Issue by dalin-** [geerlingguy/drupal-vm#534]
Let's say the machine name for my Acquia site is _poets_.  Logically I'd use the same machine name for my Vagrant box.  But If I do that there's a collision with `~/.drush/poets.aliases.drushrc.php` and whoever's written to it last (DrupalVM or `drush acquia-update`) wins.  

Any recommendation on how to deal with this?

**Comment by geerlingguy** [comment]
What I usually do is either set `configure_local_drush_aliases` to `false` (and then manage the aliases myself, since I can just add a site to the acquia-provided alias file so I can type in `drush @acquiasubname.local [command]`), or set the box name to something different than the actual subscription machine ID.

**Comment by geerlingguy** [comment]
I'll leave this open in case anyone has a better idea, but that's what I typically see others do as well.

**Comment by dalin-** [comment]
For those who are interested, all I needed to do was change `vagrant_machine_name` which AFAICT doesn't affect really anything else.

**Comment by geerlingguy** [comment]
Sounds like a good solution! I'll close this issue but refer people back to it if similar questions are asked.
