### ISSUE TITLE
Turning the drupalvm share inside out

### ISSUE THREAD

**Issue by akhaef** [geerlingguy/drupal-vm#553]
Hi.
I just started using this project, and wow is it cool!

This might be bold since I'm new to this vagrant stuff, but it looks to me like vagrant's "synced folders" business isn't really the right idea for anything but the /vagrant mount.

Wouldn't it make more sense to do it inside out and install and configure samba on the guest, put it on its own workgroup with a set username and password, and share the folder from within?

This would have lots of benefits:
- speed: http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines
- we're doing all the other services this way (i.e. leave-the-host-alone), so why should this be different?
- samba is super simple to configure compared to the tons of fancy stuff you've already done, and every OS can access it as an underprivileged user, so things become simpler in that respect.
- windows... poor windows users are left with only less-than-ideal options: a) get some NFS service working on windows, b) deal with the slow fallback (it's REALLY slow), c) do all vagrant stuff as an administrative user with mucking around with sharing so development can be done as the ordinary user.  Windows users are people too ;-)

What do you think?  Is it worth exploring?  Is there something about the typical use case I'm completely missing?

Thanks!

**Comment by geerlingguy** [comment]
If there is a way to make it so the default works effortlessly, it would be nice, for sure, especially on the performance side of things.

However, one of the most common use cases is to have the entire project (drupal codebase, etc.) managed on the host machine, and this codebase is then synced into the VM; if you do it the other way around, this requires developers either automatically clone and set up the entire codebase inside the VM, or have a task to copy things inside the VM then delete the files from the host.

Since the idea of the VM itself is to be easily destroyable without causing harm to the developer's project or host machine, if you store the code that's being worked on inside the VM, and accidentally do a `vagrant destroy` or otherwise ruin the VM in the middle of some work, then you'll end up losing your work in progress too :/

Vagrant uses synced folders and recommends them for most projects by default, because it fits the development workflow most people are used to. But for those who do need that extra performance, there's nothing stopping you from (currently) setting things up via a `post_provision_scripts` script, which can do the codebase setup within the VM.

But I don't think I'll be supporting this as a default/standard option on Drupal VM.
