### ISSUE TITLE
DrupalCon NOLA 2016 - Battle Plan for 3.0.0

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#604]
I'm hosting a BoF on Drupal VM and local development at DrupalCon NOLA, and I want to work on the agenda, main topics for discussion, notes, etc. in this issue.

I've already been tagging issues and PRs with the 3.0.0 and drupalcon milestones. Some things I'd like to have resolved by the end of sprinting Friday, and other issues I want to try to get in by 3.0.0 (maybe not 100% working, but at least work_able_ so people can offer feedback).

Some of the main things I want to discuss, though:

- [x] What are the biggest pain points using Drupal VM now? (Esp. for teams)
- [x] What are the features people miss most?
- [x] Should we do a major backwards-incompatible push towards defaulting to PHP 7? Now? Later? (Note that people could still use 5.x, but all the docs would assume PHP 7, and 5.x support would require tweaking... the inverse of the current situation).
- [x] What are some awesome things happening in [other local Drupal dev environment tools](https://www.drupal.org/node/2256789)? [Other](https://github.com/Varying-Vagrant-Vagrants/VVV) [non-Drupal](https://laravel.com/docs/4.2/homestead) [development environments](http://phansible.com/)?

For reference, the BoF is happening tomorrow, Wed. May 11, at 10:45 CST (15:45 UTC), in room 289: https://events.drupal.org/neworleans2016/bofs/drupal-vm-and-local-drupal-development-teams

**Comment by oxyc** [comment]
Also worth noting is the Beetbox environment @thom8 is working on 
https://github.com/geerlingguy/drupal-vm/issues/305#issuecomment-213006171. They have some awesome ideas. https://github.com/beetboxvm/beetbox

**Comment by thom8** [comment]
Thanks @oxyc, unfortunately couldn't make it to DC due to family commitments.

@Decipher a co maintainer is there and can explain how we've addressed some of the pain points specifically working with teams.

**Comment by Decipher** [comment]
I will be attending this BoF, and also wish to discuss an additional topic on the selection criteria and process of picking a replacement stack for the First Time / Mentored Sprint in future cons.

**Comment by geerlingguy** [comment]
@Decipher - Note that I'm not particularly involved in that particular process (I haven't done a lot of work with mentoring, though I've been tangentially involved). My goal with Drupal VM is to target the 'mainstream' Drupal dev, not necessarily beginners... though I would like to continue helping make the first-time experience for anyone better!

For reference: [Get Vagrant D8 VM ready for Drupal 8 mentoring at DrupalCon](https://www.drupal.org/node/2232049)

**Comment by Decipher** [comment]
@geerlingguy There's no requirement about targeting beginners in what I wish to discuss, rather than ensure that there is a viable solution that can be standardised on in this, and possibly other, event.

My personal criteria based on my knowledge of the event would be the ability to have a stack that is quick and requires little to no internet connection to get up and running so as to ensure that it doesn't have an adverse effect on the conference internet.

I am aware of said issue, which is the catalyst of wanting to have a discussion with some people related to key offerings in the arena so that some sort of un-biased selection criteria can be determined rather than everyone throwing their offerings into the ring and wondering why we are still stuck using Acquia Dev Desktop at the sprint.

**Comment by geerlingguy** [comment]
> requires little to no internet connection

Paired up with a few Raspberry Pi zeros hosting boxes that are rebuilt via Packer the week/night before the sprints (so the Drupal 8 git clone is recent and only requires a few deltas to load over the Internet), we could probably figure something good out!

> Everyone throwing their offerings into the ring and wondering why we are still stuck using Acquia Dev Desktop at the sprint.

Haha, yep. And ADD2 is ~120 MB, so even though it's smaller in size than most of the other projects, it's not lightweight on the bandwidth!

**Comment by a-fro** [comment]
I wish I were there with you at DCon to participate. However, I'd love to chime in on the topic from a distance. I played with Drude last week, and was pretty blown away by the performance. After using DrupalVM for a couple of years now, I've gotten used to a slower pace of local development. Here's a [link to the post](https://ffwagency.com/blog/simplify-local-development-drude) announcing it, as well as my comment:
        
>Thanks David and team FFW! After installing the test site, I was pretty blown away by how snappy it >felt. So I brought a large, existing client project up on Drude and compared it to our current DrupalVM >setup and ran through a list of common development/management tasks (content creation and >editing of various content types, as well as feature rebuilds). The result was pretty shocking: 2mins 20 >seconds on Drude vs. 5mins 20 seconds on DrupalVM. Impressive!
>
>I'd be very interested to hear from you and/or @geerlingguy on the topic, possibly with more precise >benchmarking. Do you think this is largely because of Docker, or other enhancements that come with >Drude out of the box? Thanks!

A few of the differences I can note out of the box: Drude uses NFS2 by default, and also has a comment about using 1 core to improve Vagrant performance. Also, I'm using VirtualBox with Drude, but VMWare Fusion with DrupalVM because VMWare was a much more performant virtual environment. Personally, I prefer the configuration granularity, general toolchain and patterns you've created for DrupalVM. But I have to admit that the performance differences noted in the quote above are significant enough to question whether it's the best approach for our team. Thoughts?

**Comment by oxyc** [comment]
@a-fro is the measured time the provisioning step? For me that's not really an issue as it's re-provisioned very rarely.

**Comment by geerlingguy** [comment]
> Personally, I prefer the configuration granularity, general toolchain and patterns you've created for DrupalVM.

This, and subtle differences between how Docker runs through the VM stack on Mac/Windows (vs. native on most Linux flavors), are the two major reasons I'm holding off on adding anything Docker-related to my current recommended workflow.

Once Docker for Mac and Windows exit beta and are real, supported products, I think dev environments and Docker might start to have real uptake.

Anyways, that aside, I don't seem to have any slowdowns using either VirtualBox or VMware with Drupal VM... most pages (uncached admin logged in) load within 100-300ms, and cached loads are within 10-30ms. I wonder if maybe the default MySQL, PHP, etc. configs in Drude are more generously apportioned for a large Drupal site—are you testing with a fresh/empty D8 install, or an existing/large D7 or D8 site/codebase?

**Comment by oxyc** [comment]
@a-fro I saw your edits. For faster performance I can recommend `rsync`, for us the load time decrease was significant (I made the switch so long ago I unfortunately dont remember the numbers though). 

This comes with some DX issues unfortunately. Specifically the time it takes for files to be synced after being saved locally has increased. To get around this we use [`vagrant-gatling-rsync`](https://github.com/smerrill/vagrant-gatling-rsync) and in our front-end toolchain now includes an rsync task which is synchronous to make sure the files are present before `BrowerSync` reloads them.

**Comment by geerlingguy** [comment]
For more notes from a couple years ago, when I first investigated NFS, rsync, native synced folders, etc.: http://www.jeffgeerling.com/blogs/jeff-geerling/nfs-rsync-and-shared-folder

I really, really, really wish Vagrant had two-way rsync—it would solve a zillion issues and make for a much faster experience for most any PHP project (not just Drupal) with hundreds or thousands of files.

See: https://github.com/mitchellh/vagrant/issues/3062

**Comment by oxyc** [comment]
Two-way rsync would be awesome! But for our current setup we don't really need it anymore. We to use a separate synced NFS folder for `CONFIG_SYNC_DIRECTORY`, and all coders run the front-end toolchain locally. It's a bit advanced I admit, two-way sync would be amazing for people getting started with Drupal VM. I also assume windows users might want to code within the VM :/

**Comment by oxyc** [comment]
@geerlingguy more on topic, will you have a hangout or something similar open? I would be interested in at least partially listening in https://github.com/geerlingguy/drupal-vm/issues/305#issuecomment-207467503

**Comment by a-fro** [comment]
@oxyc the measured time was a series of developer and content management tasks: creating and editing nodes of various types, feature rebuilds, etc. In other words, it was the day-to-day nuts and bolts of how our team spends time working in Drupal.

**Comment by thom8** [comment]
@a-fro the performance gains can be quickly eroded if you have a production bug that can't be easily replicated on a non-prod environment.

We keep our non-prod environments (dev/CI/UAT) in sync with PROD so configuration granularity is far more important than performance. If anything we want performance issues to be replicated everywhere so improvements made apply to all environments including PROD.

**Comment by thom8** [comment]
> Once Docker for Mac and Windows exit beta and are real, supported products, I think dev environments and Docker might start to have real uptake.

@geerlingguy would be interested in your thoughts on LXD -- http://www.ubuntu.com/cloud/lxd.
A VM could be replaced with a system container or at least a VM that could provision and manage system containers (similar to boot2docker). Could be a good stepping stone towards docker/containers & it supports docker -- https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/

**Comment by geerlingguy** [comment]
@oxyc @thom8 et all; we're doing a Hangout On Air: https://plus.google.com/events/cbu2f05tj5ma3h9l56otpsjkrqk

**Comment by geerlingguy** [comment]
New link: https://plus.google.com/events/cn7lh9igp7toarjsgtimj1ako0c

**Comment by a-fro** [comment]
@geerlingguy the first link is working; not the 2nd. I'm watching now.

**Comment by geerlingguy** [comment]
Some notes:

  - One of the biggest challenges of VMs: one site per VM, or a bunch of sites in one VM. VMs take lots of memory, want to keep it down to one or two VMs at a time.
  - `vagrant reload --provision` fails on something, usually something upstream (e.g. a repo is down or something)
  - One person provisions, then they store a box on Atlas; but that's a hard thing to do, have to change config files, updates are hard.
  - Time to provision fresh project.
  - [Beetbox](https://github.com/beetboxvm/beetbox) is basically Drupal VM, pre-provisioned; box on Atlas.

**Comment by geerlingguy** [comment]
New hangout: https://hangouts.google.com/call/a6bnqjymanhlvp74ebo3r3f56ae

**Comment by thom8** [comment]
Is this the spreadsheet mentioned in the BoF? -- https://docs.google.com/spreadsheets/d/1EWmxQMMekc0fMoMl16HyLt0i8yCRBT5wAVuy66Bi4kI/edit#gid=0 

/cc @theodorosploumis

**Comment by oxyc** [comment]
You mentioned some sprints, when and what time would that be?

**Comment by geerlingguy** [comment]
@oxyc - Friday, starting at around 8-9 a.m. CST (so 13:00 UTC).

And @thom8 - Yes, that's the one, thanks!

**Comment by mathieuhelie** [comment]
The way I saw the discussion going, there are two competing use cases trying to be integrated in Drupal VM and probably the cause of many of the headaches. On the one hand there is the need to have a fully-provisioned dev machine, similar to the MAMP/DevDesktops but fully virtualized so that we can have a whole dev team running on the same environment, that we can clone and share quickly at code sprints and so on. The other hand is the need to define a custom virtual machine for a specific project over the lifetime of that project, which @geerlingguy admits he does outside the drupal-vm codebase.

I'm probably halfway between an end-user and a devops guy. At Floe we inherited a bundle of custom VMs provisioned with Ansible for different projects in the project repos under /provision, and ended up creating a repository for our production servers with a custom branch per project (ugly, but necessary, since different projects need different dependencies and integrations). I'm not a devops guy, I just want to get right away to building my project, but I need to get my teammates running on the same environment fast. I never felt much of a sense of control over our patchwork of VMs (too improvised over too long a time), so I found that Drupal VM's documentation and declarative configuration gave me that control. The only problem is we can never get it working right, there is always some role breaking down. Just last Friday it was the Apache role failing on some task about RHEL having incorrect syntax. Nowhere in my config did I even need Apache or RHEL, so that leaves me debugging the provisioning instead of launching my project. Then I have to make the choice between starting from scratch or hunting down the quirks of Drupal VM.

I think Drupal VM is going to be more successful if it becomes a framework for quickly developing a VM, but for this it needs to be stripped down and stabilized. The Drupal Console/Symfony Console code generation tools might provide an inspiration for the kind of toolkit we want to have. You run a tool that spits out your vagrantfile, playbook and narrow selection of roles. From that point on the project evolves on its own and Drupal VM is no longer that much use. 

The intermediate step would be turning off almost every feature by default in Drupal VM, and creating a config structure that gives control to the user to enable features one at a time.

We could then have multiple projects serving up different flavors of fully-provisioned machines, leveraging Drupal VM as their starting point and maintained using Drupal VM.

**Comment by geerlingguy** [comment]
> You run a tool that spits out your vagrantfile, playbook and narrow selection of roles.

Something like [Phansible](http://phansible.com/) :)

**Comment by thom8** [comment]
@mathieuhelie it comes down to a balance of convenience vs customisation.

A similar balance exists when comparing something like Drupal with Symphony and unfortunately there's no right or wrong approach, it comes down to your specific requirements.

A fully custom Ansible build would provide you with the most flexible solution however you need to have available resources to manage and support it.

After going through some major upgrades to custom builds there's a lot to be gained from using a community supported "project/framework" so development and support are shared.

> From that point on the project evolves on its own and Drupal VM is no longer that much use.

Some projects choose to do this now by forking Drupal VM eg. https://github.com/srowlands/govcms-devkit

However you still need to manage you own updates.

**Comment by geerlingguy** [comment]
I'm going to write up a blog post on Drupal VM 3.0.0, and probably a separate one on something like 'the state of local dev environments for Drupal' touching on some of the discussion we had in the BoF and in this thread.
