### ISSUE TITLE
Add extra software task

### ISSUE THREAD

**Issue by camoatech** [geerlingguy/drupal-vm#62]
Add ways to install bower, nodejs, grunt, htop. Maybe a role that calls apt to install these packages and another for npm packages?

**Comment by geerlingguy** [comment]
I could maybe add an optional `extra-packages` variable in `config.yml`, and if anything's configured in that list, it would be installed via `apt`. I tend to shy away from adding extra installations that rely on node, ruby, etc., because usually people want to use them for build tools, and that should usually be done on the host machine (imo). But if there's a valid use case, I'm open to most anything.

**Comment by geerlingguy** [comment]
Others have also requested something like this. I'm thinking I could use `geerlingguy.nodejs` along with a custom variable (if empty, Node is not installed), and `geerlingguy.ruby` along with another custom variable (again, if empty, Ruby is not installed).

This way, people like me who hate having a huge kludge of non-PHP stuff installed on the VM can do so, but I still keep my lean, mean, Drupal machine :)

**Comment by geerlingguy** [comment]
I've added the ability to add extra apt packages with the new `extra_apt_packages` variable.
