### ISSUE TITLE
Link to latest release zipball on drupalvm.com

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#626]
Unfortunately there's no alias for this, so we have to use some JavaScript for getting the latest release.

I think it could be worth fixing as we now direct complete beginners to a zipball of the master branch on http://www.drupalvm.com/. 

Based on http://stackoverflow.com/a/26454035/319855 we could add this script to the footer of the site.

```js
jQuery.getJSON('https://api.github.com/repos/geerlingguy/drupal-vm/releases/latest').done(function (release) {
  jQuery('a[href$="master.zip"]').attr('href', release.zipball_url);
});
```

**Comment by oxyc** [comment]
I'm assuming it's just a static site.

**Comment by opdavies** [comment]
I do this on drupalvmgenerator.com with a custom controller in a D8 module, the same way as drupalconsole.com.

See https://github.com/opdavies/drupalvmgenerator.com/tree/master/web/modules/custom/github_data.

**Comment by geerlingguy** [comment]
@oxyc - Yeah, just a static site, I've been meaning to move it to GitHub pages so you could just submit a PR for something like this... but for now, I'll just include the JS snippet.

**Comment by geerlingguy** [comment]
Created https://github.com/geerlingguy/drupalvm.github.io — though the site is currently managed on static.midwesternmac.com; I don't know when I'll work on making the full switch to GitHub pages (or if I'll just set up my static site to pull from GitHub instead, since that may be simpler than dealing with a couple of GH Pages' oddities.

Your JS worked perfectly!
