### ISSUE TITLE
Drupal VM needs better upgrade path support 

### ISSUE THREAD

**Issue by xaviemirmon** [geerlingguy/drupal-vm#640]
Hi @geerlingguy,

There needs to be a better upgrade path for minor versions e.g. 2.4.x to 2.5.x.  We have the Drupal VM setup as a git submodule so that we can add it to our projects.   However, the most minor recent release broke a lot of things because it relies on new dependencies.  The biggest changes for our setup were:

- Vagrant needed to be upgraded to 1.8.1
- As a result vagrant auto-network had to be updated `vagrant plugin install vagrant-auto_network`
- Perms reapplied to the galaxy file `sudo chown {USER}:staff /Users/{USER}/.ansible_galaxy`
- PHP 5.6 requires additional packages to be added now (packages which have been mis-documented #639)

Whilst these issues were solved in the documentation or as a GitHub issue, I suggest adding a changelog.txt or something to the https://github.com/geerlingguy/drupal-vm/releases page which outlines any new requirements and any breaking changes so that in future it's clear what steps will need to be carried out when performing minor upgrades on existing Drupal VM setups.  

Anything I could help to contribute with this?

**Comment by geerlingguy** [comment]
@xaviemirmon - Actually, up until 2.5.1, there really was _no_ official/supported/anything upgrade path. We just recently added an [Updating Drupal VM](https://github.com/geerlingguy/drupal-vm#updating-drupal-vm) section in the main README, and for the past 10 or so releases, I've added extremely detailed release notes for each tag (including every changed variable file).

#639 is only an issue if you're using the bleeding-edge (and 'break all the things', currently) master branch. The Drupal VM website links to the latest tag, currently 2.5.1, so nothing should be broken there.

The reasons why things are currently breaking (and likely will again) on the master branch is we're rearchitecting _a lot_ of Drupal VM, changing _a lot_ of defaults, and we still haven't completed manual tests of things not covered by automated tests (e.g. I am still running a gauntlet of tests on my Windows laptop).

We've also added a new [System Requirements](https://github.com/geerlingguy/drupal-vm#system-requirements) section to the README, as well as a [note on all the required Versions](https://github.com/geerlingguy/drupal-vm#1---install-vagrant) for the current release of Drupal VM.

I'm not saying we're perfect—far from it. But maintaining detailed/thorough release notes, thorough manual and automated tests, a detailed procedure in the README, as well as a detailed CHANGELOG (which would likely be a slightly cleaned up version of the release notes/git log)... that's a lot to maintain, and I'm not sure I'd want to require everything be documented in CHANGELOG.

Going back to the specific points:

> Vagrant needed to be upgraded to 1.8.1

VirtualBox should also be kept reasonably up-to-date—but the specific version requirements are always documented in the README that ships with Drupal VM.

> As a result vagrant auto-network had to be updated vagrant plugin install vagrant-auto_network

I don't personally use auto-network, and this integration is one of the features that is supported, but only nominally.

> Perms reapplied to the galaxy file sudo chown {USER}:staff /Users/{USER}/.ansible_galaxy

I've never seen this issue before, but I'm assuming this is something caused if someone has only ever run the `ansible-galaxy` command with `sudo`.

As I stated earlier, we never really had any kind of upgrade path prior to 2.5.1. Moving forward, you no longer need to use `sudo` for galaxy (this will unbreak a lot of things), and in addition, all roles are installed local to each Drupal VM instance (this makes Drupal VM way more stable version-to-version, especially if you have multiple VMs on one computer for different projects).

> PHP 5.6 requires additional packages to be added now (packages which have been mis-documented #639)

This is because master is currently in a state of "break all the things" and now we're fixing some of those broken things :)

I **highly** recommend sticking with the latest tagged release (2.5.1 currently), as that is the most stable. 3.0.0 should also be stable, but I imagine there will be a few small bugs lurking that might put people favoring stability > features off, so 3.0.1 or 3.0.2 could be a better option.

**Comment by geerlingguy** [comment]
(Sorry if the above comes off more as a rant... not my intention at all!)

**Comment by geerlingguy** [comment]
Main point: Stick to the stable release, and I'm sorry about breaking things... we had to break at some point, so I decided to release 2.5.1 stable which still uses all the old role versions and PHP 5.x defaults before working on the 3.x release. Some things had to break just because we didn't have any good upgrade path prior to 2.5.1 :(

**Comment by xaviemirmon** [comment]
Hi @geerlingguy,

Thanks for explaining.  I had presumed that you were working with GitFlow ([GitFlow Branching Model](http://nvie.com/posts/a-successful-git-branching-model/)) or a similar branching workflow and by that token master was the latest most stable version with any potential hotfixes.   On this basis, perhaps it would be useful to add to the documentation to checkout to the git tag for the version you wish to install.   I am sure there are other people like myself who have cloned the latest version on master under a similar impression so may be worth mentioning you need to checkout the version you require.  I will revert and let you know how I get on.

**Comment by geerlingguy** [comment]
@xaviemirmon - No problem! I've considered switching the branching model at some point... but not sure if I want to add the overhead involved (I had a '7.x' branch a while, but I always forgot to keep it in sync because so few people used it, and I never did).

The main thing is—master always works _if you build a new VM from master_, but it's not always guaranteed to work with a previous release if you're updating, unless you make any changes required as mentioned in release notes...

When I'm using Drupal VM, I'm usually destroying and rebuilding the VM quite often—sometimes dozens of times a day—so it's hard for me to remember that many people build a VM once and then keep using it for many versions of Drupal VM / a long time :)

**Comment by slimatic** [comment]
@geerlingguy I usually add my own customized tasks to the playbook.yml file but this makes upgrading a bit of a hustle. With version 3.0 I was trying to find a way to introduce local.playbook.yml file using Vagrantfile.local to run the local.playbook.yml after the playbook.yml runs. Any recommendations on how to go about this?

**Comment by oxyc** [comment]
@slimatic you can use a similar hack as I use to disable the galaxy install command (well hidden as an example in the [docs](http://docs.drupalvm.com/en/latest/other/overriding-configurations/#extending-the-vagrantfile-with-vagrantfilelocal)).

```rb
# Disable the galaxy role re-installation during provisions.
config.vm.provisioners[0].config.galaxy_role_file = nil
```

WIth that as an example I think you could do:

```rb
config.vm.provisioners[0].config.playbook = "#{host_config_dir}/local.playbook.yml"
```

And place the `local.playbook.yml` in the same directory as your `config.yml`.

**Comment by oxyc** [comment]
Actually now that i think about it that might break something... the paths within the playbook will probably be incorrect.

Any chance the `pre_provisioning_tasks_dir`/`post_provisioning_tasks_dir` are enough? http://docs.drupalvm.com/en/latest/extras/scripts/#ansible-task-files

**Comment by oxyc** [comment]
@slimatic https://github.com/geerlingguy/drupal-vm/pull/688

**Comment by geerlingguy** [comment]
Going to mark this as closed now; I think we have as good an upgrade path as we can at this point—once people get over the hurdle of moving to 2.5.1 or 3.x, upgrades will be a lot less painful in the future.
