### ISSUE TITLE
Drupal VM Quickstart Guide Incomplete, Drupal VM for Windows Users Using Default Configuration Non-Usable

### ISSUE THREAD

**Issue by amstaker** [geerlingguy/drupal-vm#729]
I really hate to be critical here but it is my belief that out of the box Drupal VM does not work for Windows users using the default configuration and settings, even with the recommendations in the documentation related to the latest windows notes.

I've tried this on multiple configurations with the default config.yml file as well as a variety of permutations of Win7 and Win10.  We've done this across multiple users and multiple machines and in the vast majority of cases on a clean vanilla windows box with the default config.yml and the instructions provided Drupal VM will not load a site.  

I'd like to see the detailed documentation listed in the quick start guide reflect an accurate and consistent process to bring a site up.

This is meant as a placeholder ticket to address what I'd consider an elephant in the closet.  Additionally, if after you get a box up and running the Synced Folders documentation is also problematic at best and confusing, you provide multiple solutions which may or may not work (I've tried and had multiple members of my team have trouble with this).  There really should be one solution and/or it should be clearly documented as to the pros and/or cons of each solution.  

If you'd like to have a brief conversation on this I'd love to chat and discuss in more detail what our team is seeing, I'd also like to contribute a bit here and help iron some of these issues out.  

When it does work the product is pretty spectacular, I'd just like to see more people be able to use it (especially the neglected Windows folks)...

**Comment by geerlingguy** [comment]
@amstaker - Please see (as reference):

  - [Developing with VirtualBox and Vagrant on Windows](http://www.jeffgeerling.com/blog/2016/developing-virtualbox-and-vagrant-on-windows)
  - And generally, some of my many ramblings on the topic: http://www.jeffgeerling.com/search/windows%20vagrant

This is a massively difficult issue to address in any reasonable manner, and there's a good reason why many projects simply refuse to add official Windows support (e.g. https://github.com/acquia/blt/blob/8.x/template/readme/local-development.md, "We highly recommend that you _do not use Windows directly_ for development. Many development tools are not built or tested for Windows compatibility.").

I don't mean to be inflammatory at all, just to say that I provide 'best effort' Windows support. I don't use Windows as my daily OS, and rarely boot my Windows 10 laptop (and don't have access to Windows 7 or 8 anymore, since that laptop was upgraded courtesy of Microsoft :P and it's a royal pain to try to reinstall/reprovision Windows because of licensing insanity).

I test each major Drupal VM release on Windows 10 on my Lenovo T420, and have supported many dev teams who insist on using Windows for their Drupal dev, and all the notes in the windows section of my guide (and many blog posts on different topics like rsync) reflect the (likely hundreds of) hours of testing I've done on Windows with VirtualBox and Vagrant. But since the times I work with a Windows environment are limited and scattered, I think that's reflected in the current state of docs for Windows.

I welcome wholeheartedly any suggestions for improving the Windows documentation and experience, so please offer any further notes/PRs for improvement!

**Comment by sarahjean** [comment]
@amstaker I have set up projects using DrupalVM and Windows a few times (Both Win7 and Win10). I won't say it's 'easy' compared to OSX but it's definitely doable and pretty usable.

Highly recommend using this for shell support in the Windows host: http://cmder.net/

Even things like https://github.com/cogitatio/vagrant-hostsupdater work on Windows 10.

After initial setup, I always `vagrant ssh` into the machine and manage things like composer or npm modules inside the vm, rather than on the Windows side. This does have some drawbacks with synced folders depending on the tool.

For instance, I found some issues with running `npm install` even inside the VM, but in my case I was able to get around these by opening a tab in Cmder with 'run as administrator' and doing the `vagrant up' and `vagrant ssh` from there, so vagrant is running as administrator and is more able to write files in the synced directory.

Perhaps if you have some specifics on trouble areas you are running into we can find some specific areas where docs can be improved.

**Comment by sarahjean** [comment]
@amstaker I am offering to help troubleshoot, as I have experience getting DrupalVM running on several projects on both Win7 and WIn10 machines. I'm not doing anything special outside of using Cmder instead of cmd. The default config definitely works on Windows. You may have other things going on specific to your IT situation but it's very likely that those can be worked through.

**Comment by amstaker** [comment]
@sarahjean - That's interesting in my testing we worked with both the straight windows terminal as well as cygwin and babun which all suffered from similar issues.  Also of note, no where in the documentation is there any indication of a Cmder dependency or requirement.  This seems like a pretty big oversight and/or assumption and leads me to believe that my intiial premise is not wrong.  We'll go ahead and test with Cmder.

**Comment by geerlingguy** [comment]
@amstaker - Can you please post any details as to what's failing, where you're having trouble, vagrant command output logs, etc.? Because often that can be helpful in finding out if there's some root underlying cause (e.g. network proxy, Windows laptop hardware (e.g. VT-x support), other OS restrictions...).

I'm running `vagrant up` using Cmder and Cygwin64 right now, will report back any weird results (the 'Generate Drupal project with composer package' step takes a very long time because of the shared folder).

**Comment by sarahjean** [comment]
@amstaker Just listing what worked for me, I have never installed Cygwin. I've also successfully run with git-bash.

**Comment by geerlingguy** [comment]
After fixing #733, I have successfully built Drupal VM on a Windows 10 laptop with VirtualBox using both Composer with drupal-project, Composer with a composer.json, and a Make file... there are still the caveats and issues mentioned elsewhere in the documentation (e.g. the [Windows notes](http://docs.drupalvm.com/en/latest/other/windows/)), but I'm going to close this issue and recommend opening any specific follow-ups so we can focus more on particular problems instead of the broader issue (which will never be fully resolved).

**Comment by geerlingguy** [comment]
(And I'll be posting some videos on 'Drupal VM in windows' on my [YouTube channel](https://www.youtube.com/user/geerlingguy) in the coming weeks, to try to help guide users new to Drupal VM and Vagrant development in a Windows environment.)
