### ISSUE TITLE
Run apache task on debian/wheezy

### ISSUE THREAD

**Issue by girod** [geerlingguy/drupal-vm#751]
Hi,

When I try to install drupal on debian/wheezy, I have this error when I launch provision :

TASK [geerlingguy.apache : Enable Apache mods.] ********************************
changed: [drupalvmdeb] => (item=expires.load)
changed: [drupalvmdeb] => (item=ssl.load)
changed: [drupalvmdeb] => (item=rewrite.load)
changed: [drupalvmdeb] => (item=proxy.load)
failed: [drupalvmdeb] (item=proxy_fcgi.load) => {"failed": true, "item": "proxy_fcgi.load", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /etc/apache2/mods-available/proxy_fcgi.load", "path": "/etc/apache2/mods-enabled/proxy_fcgi.load", "src": "/etc/apache2/mods-available/proxy_fcgi.load", "state": "absent"}

Note : in config, I have php_enable_php_fpm: true
I don't use apache mod_php

Cheers,

Franck

**Comment by geerlingguy** [comment]
Is this as part of your own playbook, or as part of Drupal VM (https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L125-L130)?

The [role's default settings](https://github.com/geerlingguy/ansible-role-apache/blob/master/defaults/main.yml#L38-L40) don't include `proxy_fcgi.load`, so the way to fix this would be to, in your own playbook's variables, just remove any mods that you don't want/need. And for older versions of Debian/Ubuntu, proxy_fcgi isn't available because they have a really old Apache 2.2 version (this role assumes Apache 2.4 by default, but still works with 2.2).
