### ISSUE TITLE
tmpfs for /tmp for performance

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#758]
We are using tmpfs for /tmp in production, which makes quite fast as it's in memory and with the filecache module you get some pretty nice improvements.  (Think like memcache without the dependencies)

http://linoxide.com/file-system/use-tmpfs-rhel-centos-7-0/

Wondering if maybe you'd consider adding that into the build?

**Comment by geerlingguy** [comment]
I'll consider the possibility. A few things that would need to happen to get support included:

  1. I'd want to add support via a cross-platform, configurable Ansible role (that works minimally on Ubuntu 12/14/16 and CentOS 6/7).
  2. It would need to have verifiable/reproducible performance gains for some baseline of Drupal site/operations (even if it's just setup/building operations).

I'd rather not add the complexity of varying the default Linux filesystem layout for a marginal performance gain, and only if it impacts a majority of Drupal use cases—otherwise it's a particular optimization I'd rather leave to downstream consumers via a shell script or ansible task file.

**Comment by joelpittet** [comment]
That is fair, this is just a conversation starter. 
Regarding 1) Ubuntu should be possible too:
http://askubuntu.com/questions/173094/how-can-i-use-ram-storage-for-the-tmp-directory-and-how-to-set-a-maximum-amount

May have to bump the VM memory to accommodate this but that will come with testing.

I see it being useful for filecache, but it should be quicker at dealing with anything in the /tmp folder, like downloading modules, unzipping them for example.  And that may be a decent performance test to gauge it's general use viability.

If it can't do something common like that faster, totally we can "close won't fix" this issue:)

Thanks for considering it!

**Comment by geerlingguy** [comment]
I'm going to close as won't fix for now, but if anyone can do some benchmarks with common Drupal operations and prove a significant (e.g. 5%+) performance increase for things like drush operations etc., then I'd definitely be willing to look into it further.
