### ISSUE TITLE
Drupal VM - Ancillary Components 

### ISSUE THREAD

**Issue by amstaker** [geerlingguy/drupal-vm#763]
On a clean windows 7 box.... 

I'm using the standard dummy box with an unaltered config.yml.

Installed Drupal VM (working now, thank you).  Following the instructions to configure using vagrant-hostsupdater and auto_network does not bring the site.  I can manually set host information which does work.  Here's what I see in my hosts, I commented out the auto settings.  I validated that I set the ip to 0.0.0.0 in the config.yml.  I also reprovisioned the box with the config.yml updated.  Probably something to look at when you have time.  A documentation update in the meantime likely also will help.

192.168.88.88  drupalvm.dev
192.168.88.88  www.drupalvm.dev
192.168.88.88  adminer.drupalvm.dev
192.168.88.88  xhprof.drupalvm.dev
192.168.88.88  pimpmylog.drupalvm.dev
192.168.88.88  dashboard.drupalvm.dev

`# 10.20.1.2  drupalvm.dev  # VAGRANT: 3651d50cdd878aac28949459d270af2c (drupalvm) `
`# 10.20.1.2  www.drupalvm.dev  # VAGRANT: 3651d50cdd878aac28949459d270af2c (drupalvm)`
`# 10.20.1.2  adminer.drupalvm.dev  # VAGRANT: 3651d50cdd878aac28949459d270af2c (drupalvm)`
`# 10.20.1.2  xhprof.drupalvm.dev  # VAGRANT: 3651d50cdd878aac28949459d270af2c (drupalvm) `
`# 10.20.1.2  pimpmylog.drupalvm.dev  # VAGRANT: 3651d50cdd878aac28949459d270af2c (drupalvm) `
`# 10.20.1.2  dashboard.drupalvm.dev  # VAGRANT: 3651d50cdd878aac28949459d270af2c (drupalvm)`

**Comment by geerlingguy** [comment]
This worked fine for me just a couple days ago, when I recorded this video: https://youtu.be/mNio_aXMLos?t=241

I don't particularly like the auto_network plugin, and never use it personally... if you use it, a lot of different little things can break, especially depending on what you're running inside the VM and how your local network is set up.

My guess is that the auto_network plugin is the source of the strangeness, and it's known to make other things break—if you remove it and/or set an IP manually, does everything work?

**Comment by amstaker** [comment]
Yes setting manual works like a charm, I submitted a pr with a
documentation change on how to address this (and get the goodies that come
with drupal vm) I think this is a pretty common pain point.

**Comment by amstaker** [comment]
Ok so you closed out the documentation update... anyway by default with a fairly standard configuration this is not coming up on Win7 boxes.  Manually setting does work but the documentation should reflect that you should set this manually and avoid the problems that come with the auto network approach.  This is a pain point that alot of folks might run into and may not be able to solve.  Also if you do manually set this up the documentation should give a sample host configuration, in particular so you can get to the drupal dashboard which you expect to see...

**Comment by geerlingguy** [comment]
We already have this in the quick start guide:

```
### 3 - Configure your host machine to access the VM.

  1. [Edit your hosts file](http://www.rackspace.com/knowledge_center/article/how-do-i-modify-my-hosts-file), adding the line `192.168.88.88  drupalvm.dev` so you can connect to the VM.
    - You can have Vagrant automatically configure your hosts file if you install the `hostsupdater` plugin (`vagrant plugin install vagrant-hostsupdater`). All hosts defined in `apache_vhosts` or `nginx_hosts` will be automatically managed. `vagrant-hostmanager` is also supported.
    - The `auto_network` plugin (`vagrant plugin install vagrant-auto_network`) can help with IP address management if you set `vagrant_ip` to `0.0.0.0` inside `config.yml`.
  2. Open your browser and access [http://drupalvm.dev/](http://drupalvm.dev/). The default login for the admin account is `admin` for both the username and password.
```

That should be adequate—and if you want to add aliases for everything, you can visit the dashboard at the VM's IP address to get the copy/pasteable set of aliases to add to your hosts file.

I don't want to add the same documentation again twice in the same quick start guide, and would rather direct people towards not using auto_network unless they are willing to deal with the consequences.

If the hostsupdater plugin isn't working on Windows 7, then that's something else that would need to be filed as an upstream issue; since I don't have a Windows 7 or Windows 8 environment that I can use to test with (Windows licensing is a HUGE pain, and I only have one PC laptop—and I have upgrade licenses for Windows Vista, 7, 8, and 10... but apparently I can't downgrade or clean install with any of those because reasons :P), I can't (and am not at this time willing to) support anything explicitly below Windows 10 besides 'best effort'.
