### ISSUE TITLE
Change default.config.yml "drupal/devel:8.*" to "drupal/devel:1.0.0-alpha1"

### ISSUE THREAD

**Issue by illepic** [geerlingguy/drupal-vm#767]
This line in `default.config.yml`:

````yaml
drupal_composer_dependencies:
  - "drupal/devel:8.*"
````

Can probably be changed to:

````yaml
drupal_composer_dependencies:
  - "drupal/devel:1.0.0-alpha1"
````

Or something equivalent. As a default, many people will probably leave this enabled and I've never been able to get the `8.*` versioning scheme to work for Composer installs, instead relying on the semver-ish `1.0.0-blah` format.

PR: https://github.com/geerlingguy/drupal-vm/pull/768

**Comment by geerlingguy** [comment]
@illepic - In the example composer.json, I have `"drupal/devel": "1.0.x-dev"` (see https://github.com/geerlingguy/drupal-vm/blob/407b94c7c9a09c3ea740e456abb0fa4f0e82ec18/example.drupal.composer.json#L22).

However, for the `drupal_composer_dependencies` variable, that's used only when using the drupal composer project install method—and since that still uses the old (soon to be deprecated) non-drupal.org packagist, the version numbers need to be in the 8.* format, right? Or am I missing something?

I just want to make sure the latest 8.x version is used, so whatever works for that is best. I definitely don't want to lock it down to a specific point release/tag (e.g. `alpha1`) as it's really mostly a demonstration of how you can pop a module into the dependencies list, and it's a dev module that most developers could/should use.

**Comment by illepic** [comment]
@geerlingguy: quick PR here to just line these all up in case people use the defaults to test out from scratch: https://github.com/geerlingguy/drupal-vm/pull/768

I totally get not locking this to `alpha1` and can update the PR to `1.0.x-dev` in both places if that works for you better.

**Comment by illepic** [comment]
@geerlingguy: I've updated the PR to version `1.x-dev` of devel since that seems to work in Composer (as opposed to `8.*`).

**Comment by geerlingguy** [comment]
Closing this issue for now (as with PR), because I want to leave things be until the drupal-project completes its transition and the drupal.org endpoints leave 'beta-ish' status.
