### ISSUE TITLE
Xdebug PHP .ini files are in the wrong place

### ISSUE THREAD

**Issue by mikecrittenden** [geerlingguy/drupal-vm#77]
Xdebug wasn't working for me immediately after install. Turns out that xdebug.ini was in /etc/php5/conf.d but Apache only cared about /etc/php5/apache2/conf.d (screenshot showing that: https://www.dropbox.com/s/3zgzpbrevy8f035/Screenshot%202015-04-17%2012.38.36.png?dl=0). Moving xdebug.ini into that directory and restarting apache fixed it.

I noticed that xhprof.ini and 20-apc.ini were also in the first directory, but not sure if those were broken as well.

**Comment by geerlingguy** [comment]
Ugh, Debian/Ubuntu Apache installation--

If everyone just used a saner Linux distro, this would just be a moot point :P

Yep—that's an issue that will need to be filed upstream in [`geerlingguy.xdebug`](https://github.com/geerlingguy/ansible-role-php-xdebug). Could you file an issue there and references this issue?

**Comment by mikecrittenden** [comment]
Sure thing. https://github.com/geerlingguy/ansible-role-php-xdebug/issues/9 -- should we close this ticket now?

Which distro do you tend to use with drupal-vm? I'm only on ubuntu since it seems to be the default in the Vagrantfile, but if there's something you recommend over it, then I'd be happy to switch.

**Comment by geerlingguy** [comment]
I've standardized on Ubuntu 14.04 (was originally on 10.04, then 12.04), since following the LTS releases seems to be simpler for long-term stability, plus for some strange reason the majority of devs I know prefer Ubuntu over most other distros (probably because it's the most unified/holistic desktop experience—though that says nothing of the server side).

Almost all the roles I built are compatible with RedHat/CentOS 6/7, Debian 6/7, and Ubuntu 12.04/14.04, so technically you could switch this VM to use `geerlingguy/centos6` or `geerlingguy/centos7` as the base box and most things would _Just Work™_; but there are a few steps in the Drupal VM playbooks that would need to be changed to work on a non-Debian-based distro.

Regardless, I'll end up fixing the paths in the xdebug role.

**Comment by scottalan** [comment]
Couldn't get it to work with Nginx out of the box. Needed to add the `xdebug.ini` to `/etc/php5/mods-available` and then add the symlink in `/etc/php5/fpm/conf.d`

**Comment by geerlingguy** [comment]
I've also released `geerlingguy.php-xdebug` 1.1.4, which includes fixes related to this issue, so that along with the updates to `example.config.yml` should guarantee that Xdebug will work great out of the box with PHP CLI, FPM, through mod_php/Apache2, etc.

**Comment by scottalan** [comment]
Thanks! Just ran into this issue again when building a new box so came back here to see what I had done before and this helped.

**Comment by scottalan** [comment]
@geerlingguy Question:

What actually creates: `/etc/php5/fpm/pool.d/www.conf`?

Can this easily be edited? I want to change something that persists when running `vagrant provision`.
