### ISSUE TITLE
The proposal to set up the Drupal Code Sniffer

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#779]
https://www.drupal.org/project/coder
https://www.drupal.org/node/1419988

I believe it will increase the worth of this product for developers.
Regards, Artu.

**Comment by geerlingguy** [comment]
Since Composer is included, I think it's best to leave CS setup to individual projects—they can include coder sniffer in their composer.json, configure the sniffs per-project (every project is usually different), and then run the sniffs as part of the project's own build process.

See Acquia's BLT for an example: https://github.com/acquia/blt

Also, a different CI/CD project I maintain (minimally) also has an example of separately installing Coder Sniffer and integrating with Jenkins and SonarQube: https://github.com/geerlingguy/drupalci-sonar-jenkins

**Comment by cdmo** [comment]
For those interested, setup is pretty easy. In your `config.yml` add the following to `composer_global_packages:`: 

```
  - { name: drupal/coder, release: '*' }
  - { name: dealerdirect/phpcodesniffer-composer-installer, release: '*' }
```

I like relying on the VM to provide this rather than my local machine (the host). Makes switching workstations more seamless.
