### ISSUE TITLE
Sync local codebase results in 404 error

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#784]
I carefully followed instructions at http://docs.drupalvm.com/en/latest/deployment/local-codebase/ to sync my local codebase, but I got a 404 error after "vagrant provision". 
[config.zip](https://github.com/geerlingguy/drupal-vm/files/353251/config.zip). Please see attached config.yml file.

Obviously I made a mistake somewhere, but being a newbie, I don't know what to do to fix it.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Can you set:

```
drupal_core_path: "/var/www/cb/web/cb"
```

I'm assuming your Drupal VM directory itself contains a folder called `web` which contains the a Drupal site/docroot inside `cb`?

Otherwise, you need to update the `local_path` under `vagrant_synced_folders` to point to your local site path (e.g. one example would be `/Users/geerlingguy/Sites/cb`), then update the `drupal_core_path` variable to point to the docroot as shared into the `destination` under `vagrant_synced_folders`.

**Comment by ColumbiaBlooms** [comment]
Where can I find a tutorial for the config.yml file contents? I'm struggling with context here and I'm sure I'm asking dumb questions.

In my config.yml file I find 

drupal_core_path: "{{ drupal_composer_install_dir }}/web/cb"

Please explain (or tell me where I can find an explanation of) what the "{{ drupal_composer_install_dir }}" part of drupal_core_path: "{{ drupal_composer_install_dir }}/web/cb" means.

I assume I have to run "vagrant up" and/or "vagrant provision" each time I make changes to config.yml?

I copied all my local files that were in the cb folder to C:\Users\samst\Desktop\Drupal\DrupalVM\web, but still get the 404 error in my browser. My site is D7 by the way.

After running "vagrant up" and "vagrant provision" the Virtual Box GUI shows drupalvm.dev powered off, but "vagrant status" shows it's running. What's the deal?

Sorry for so many questions in one post, but I'm trying learn.

**Comment by geerlingguy** [comment]
`{{ something }}` is simply a reference to another variable; just like with Twig in Drupal 8, Jinja (a Python templating language) is used by Ansible, and the double-brackets means 'print the variable here'.

So when Ansible runs the Drupal VM install playbook, the setting:

```yaml
drupal_core_path: "{{ drupal_composer_install_dir }}/web/cb"
```

...is expanded into the actual string:

```yaml
drupal_core_path: "/var/www/drupalvm/drupal/web/cb"
```

So in your case, you may be syncing a local codebase into the VM at a path like `/var/www/cb`—this is the path you set for the `vagrant_synced_folders` `destination`. If you do that, then you need to override either the `drupal_core_path` (preferred, for simplicity's sake, since you're not going to use Composer to install your site), or `drupal_composer_install_dir` so the resulting `drupal_core_path` is correct and points to your installation.
