### ISSUE TITLE
Document SSH key capabilities

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#785]
I am unclear on what options DrupalVM supports with the host SSH keys and was hoping for some documentation to explain functionality and configuration.

**Comment by geerlingguy** [comment]
@nerdstein - Drupal VM supports the same set of options as are supported by Vagrant itself (https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html)—and explicitly adds support for SSH agent forwarding (so you can log into the VM and use your keys/config that you have set up in your SSH agent on the host).

You can set any of the other options via a `Vagrantfile.local` if you'd like; since this is a more advanced usage of Drupal VM, and since it's covered in depth in Vagrant's documentation (for those who need to go deeper than simple agent forwarding), I don't think it's necessary to cover anything extra explicitly in Drupal VM's documentation.
