### ISSUE TITLE
zip archive extension missing

### ISSUE THREAD

**Issue by jamesrward** [geerlingguy/drupal-vm#804]
Received the following error when attempting to run update.php on a site using latest master.
```
PHP does not have the zip archive extension available
```

Running `sudo apt-get install php7.0-zip` and rebooting the vm fixed the issue.

Not sure if this is a documented requirement for D7 but webform module seems to require it.

**Comment by geerlingguy** [comment]
Hmm... that might just be a Webform requirement; I only use Webform on a couple of my sites so I haven't run into this particular issue.

The best option would probably be to add the following into your own `config.yml` so the installation is automated:

```
extra_packages:
  - sqlite
  - php7.0-zip
```

**Comment by geerlingguy** [comment]
Otherwise, Drupal VM just uses the defaults from the `geerlingguy.php` role, which is designed to give the normal/basic PHP defaults used by most PHP apps/Drupal sites. There are certain PHP extensions required by certain modules, but I'd rather not add the zip package if it's not needed by Drupal core specifically.
