### ISSUE TITLE
php soap extension seems not present for php 7

### ISSUE THREAD

**Issue by JeroenHoutmeyers** [geerlingguy/drupal-vm#871]
I have a Drupal site which contains a module taking care of a Soap webservice integration.
I recently moved the site on a new drupal-vm, but now my code trows an error Fatal error: Class 'SoapClient' not found. I inspected the php configuration using phpinfo(); and the soap extention is nowhere to be found.

How can I solve this issue?

**Comment by thom8** [comment]
You'll need to add php soap package to your `php_packages` list -- https://github.com/geerlingguy/ansible-role-php/blob/master/vars/Debian.yml#L2-L16

Note
- The package name will depend on the OS flavour and version.
- When overriding this var you need to include all the defaults + your additional as it overrides rather than merges.

**Comment by geerlingguy** [comment]
@thom8 is correct - please add the soap package to the `php_packages` list, then run `vagrant provision`, and it will get installed. For Ubuntu 16.04, it would be [`php7.0-soap`](http://packages.ubuntu.com/xenial/php7.0-soap).
