### ISSUE TITLE
Cannot write to file via post_provision_scripts

### ISSUE THREAD

**Issue by reekris** [geerlingguy/drupal-vm#880]
After provisioning my box I want to add the path of my composer vendor/bin dir which contains local versions of Drupal Console and Drush downloaded via composer. 

To do this I have the following in my config.yml:
```
post_provision_scripts:
  - "{{ config_dir }}/../scripts/vagrant-post-provision.sh"
```

My vagrant-post-provision.sh looks like this:

```
#!/bin/bash

# Add local Drush and Drupal Console to PATH
if ! grep -q /var/www/site/vendor/bin "$HOME/.profile" ; then
  sudo echo "export PATH=/var/www/site/vendor/bin:$PATH" >> $HOME/.profile
else
  exit 0
fi
```
I don't get any errors while provisioning and it runs the task according to the console output.
However my ~/.profile file does not change.

If I manually do `vagrant ssh` and run the command
 `sh /var/www/site/scripts/vagrant-post-provision.sh`

It adds a row to my ~/.profile as expected. 

Any idea what I might be doing wrong?

**Comment by thom8** [comment]
@reekris this will likely be running with sudo using the `root` user so would create `/root/.profile` rather than `/home/vagrant/.profile`.

You could add it to `/etc/profile.d` which is loaded for all users -- example - https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/global-require.yml#L12-L16

However, I prefer to use a `.drush-use` file in the root of the project -- example - https://github.com/acquia/blt/blob/8.x/template/.drush-use

This way you can tell drush to always use the local version, I'm not sure if drupal console has a similar option.

**Comment by reekris** [comment]
@thom8 Changing the target path in my script to `/etc/profile.d` fixed the issue, thanks a lot!

`.drush-use` seems like a nice alternative for Drush, but I'm not aware of any similar solution for Drupal Console.

**Comment by reekris** [comment]
@thom8 Thanks for the help!

Not sure how I would go about adding my script to /etc/profile.d? Can that be done during provisioning somehow?

Changing my script to point to `/home/vagrant/.profile` made it work anyway. Not as nice since the vagrant user is hardcoded, but it works.

.drush-use seems like a nice alternative for Drush, but I'm not aware of any similar solution for Drupal Console.

**Comment by thom8** [comment]
Good to hear you've got it working, if you're familiar with anisble you could also use a custom ansible task -- http://docs.drupalvm.com/en/latest/extras/scripts/#ansible-task-files

just include a `become: no` so it would run without sudo.

BTW - I've got a PR open on the composer role which could solve this too ;) -- https://github.com/geerlingguy/ansible-role-composer/pull/26

**Comment by reekris** [comment]
Nice! Hopefully it gets merged then 👍
