### ISSUE TITLE
changing permissions issue

### ISSUE THREAD

**Issue by valery-kuzmenko** [geerlingguy/drupal-vm#882]
Hello. I use windows and smb for synced folders, and I can't change permissions on vagrant machine and it cause errors during work of Drupal 8 . It always throws errors that some operations are not permitted. Just FYI - I have 775 permissions for dir and 664 for files. But I can't change them under vagrant user or even root. Is there a way how to fix it? Thanks.

**Comment by jesrig** [comment]
I am having the same exact issue. When I try to to chown or chmod nothing happens. I don't even get any errors in the terminal.

**Comment by fubarhouse** [comment]
Have you got a sample of the console output, and have you also tried chgrp to the 'vagrant' group?

**Comment by jesrig** [comment]
@fubarhouse 
Here is my console output:
![image](https://cloud.githubusercontent.com/assets/9934291/18587323/66adc5dc-7bef-11e6-8879-2410932b5d98.png)

**Comment by fubarhouse** [comment]
@jesrig Everything should be working, have you got a copy of the error message from the watchdog?
Also, could you check/submit the file system form to make sure everything is as expected?

**Comment by jesrig** [comment]
@fubarhouse The issue I had was this: I loaded my site and found that all styling etc was broken. I looked at the javascript console and found the error 'Drupal is not defined'. I figured this might have to do with file permissions, tried to set them and ran into this issue. The watchdog log is full of file permissions errors:

![image](https://cloud.githubusercontent.com/assets/9934291/18612287/e6f0be5e-7d23-11e6-97b6-02a880186255.png)


I tried resubmitting the file system form (admin/config/media/file-system) and still nothing.

**Comment by fubarhouse** [comment]
I might try to replicate this tonight, are you using a stock standard instance of Drupal VM?

**Comment by jesrig** [comment]
@fubarhouse I did make some changes to the config.yml (which I store in config/config.yml) See attached (changed to txt so I could upload)
[Vagrantfile.txt](https://github.com/geerlingguy/drupal-vm/files/479992/Vagrantfile.txt)

. The changes made here worked fine with other sites.
[config.txt](https://github.com/geerlingguy/drupal-vm/files/479990/config.txt)

**Comment by fubarhouse** [comment]
@jesrig I'll use these files when testing.

You've said this is only a problem on one site, is there anything of note on that site which could help diagnose it?

**Comment by fubarhouse** [comment]
So I'm having no luck getting this replicated on Windows.
I have seen the problem before, but usually resubmitting the form, clearing caches, rebuilding registry and running a cron are among the tasks which fix it.

I in fact had a situation where I couldn't fix this but my database import script linked to my organisations Acquia account fixed it at the very end before taking me back to the menu.

One of the last commands to run are drush rr.

````
drush dl registry_rebuild
drush @site rr
````

Because I can't properly replicate it I can't offer any additional help, but I feel strongly that the above advice should fit it up as I have experienced this before.

**Comment by geerlingguy** [comment]
Going to close this for now, as much time has passed—one solution could also just be to run `drush @site cc all` (D7) or `drush @site cr` to rebuild caches. Sometimes that's all that's needed.

Otherwise, maybe try using a different synced folder type (try '' (empty string), 'smb' (Samba), or 'rsync'), and see if that makes a difference.

**Comment by jesrig** [comment]
@geerlingguy I gave up and did a vagrant destroy, and of course that did work.

**Comment by geerlingguy** [comment]
@jesrig - Great!

**Comment by therobyouknow** [comment]
My comment here may also be of help to folks if unsuccessful with the above: https://github.com/drupal-composer/drupal-project/issues/199#issuecomment-423741155
