### ISSUE TITLE
Node.js support is outdated and doesn't work at all

### ISSUE THREAD

**Issue by odrzutowiec** [geerlingguy/drupal-vm#884]
The last supported version is 0.12 but should be at least 4.5. I couldn't get it to work without modifying the ansible roles which are not supposed to be modified at all. Imho it's very important in modern development where node.js plays major role in building front-end assets and generally front-end plays major role in web development. ;)

**Comment by thom8** [comment]
@odrzutowiec ansible role variable are meant to be modified to get your environment the way "you" want it.

If you want to update the defaults, post a PR to -- https://github.com/geerlingguy/ansible-role-nodejs

The issue is @geerlingguy would need to update this all the time, when this is easily configurable to your requirements :)

**Comment by odrzutowiec** [comment]
the variable doesn't work unfortunately, Node.js guys changed the debian repo. Ok, I'll try to find some time and create a PR. :)

**Comment by thom8** [comment]
Really - I'm using it ATM with the latest LTS version without issues (as of yesterday..)

Take a look here to see what the issue might be - https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/setup-Debian.yml#L15-L16

**Comment by odrzutowiec** [comment]
On deb.nodresource.com they are using now "setup_" instead of "node_". I will recheck that if I find a way to fixing you guys have a PR guaranteed ;)

**Comment by thom8** [comment]
Awesome! 

There looks to be a semi offical role - https://github.com/nodesource/ansible-nodejs-role

but no CentOS/RHEL support ...

**Comment by geerlingguy** [comment]
@odrzutowiec - Note that, due to various reasons (my sanity and security being the top two), the Node.js role performs the installation in a more secure way than the default 'sudo curl | bash' method in the Nodesource readme (https://github.com/nodesource/distributions/blob/f5e9a5d5f6caea3cac910fb1bc907bb51a6a9ec7/deb/setup_4.x#L11 - `curl -sL https://deb.nodesource.com/setup_4.x | bash -`).

The repo for 4.x is `NODEREPO="node_4.x"` in that shell script that is in the nodesource repo, so in the setup task, you just need to make sure the version is set to `4.x` and you will get the latest stable 4.x release (see: https://deb.nodesource.com/node_4.x/)

Same thing for other supported versions.

So for my use case, I want Node.js 5.x, so I set `nodejs_version: 5.x`. For other examples, read through the role's documentation:

https://github.com/geerlingguy/ansible-role-nodejs#role-variables

**Comment by geerlingguy** [comment]
(Note that someday I'll bump the default version... but many of the projects I interact with were locked in at 0.12 a while back, so it's mostly a matter of me being lazy and not breaking any of the 'old stable' stuff 💃 

Also, for some reason, Nodesource doesn't necessarily support all the newer versions on all the OSes I provide support for (e.g. CentOS 6, Ubuntu 12.04, etc... which will still see support for a while longer), so I have to be careful when I carpetbomb my role's users with new defaults :)

**Comment by RobLoach** [comment]
For those following along, [nvm](https://github.com/creationix/nvm) is a good one. While Node.js 0.12 is installed, you can use nvm to switch to a newer version of Node.js.

**Comment by joestewart** [comment]
We use https://github.com/fubarhouse/ansible-role-nodejs for nvm in DrupalVM.

**Comment by geerlingguy** [comment]
I typically use nvm if I need to switch versions in a particular environment, but if at all possible, I recommend using one version of Node.js inside a VM as that version should be shared among the entire team, and also should be updated in lockstep with your other theme/other resources. I frequently see devs waste an hour or more wondering why little things are breaking when they've forgotten that they switched from 4.x to 6.x, then 0.12, then back to 4.x, and suddenly node-sass and other deps start going haywire.

**Comment by RobLoach** [comment]
> suddenly node-sass and other deps start going haywire.

:+1: node-sass has a tendency to do this.
