### ISSUE TITLE
Add possibility to use NGINX

### ISSUE THREAD

**Issue by BR0kEN-** [geerlingguy/drupal-vm#89]
Would be great if usage of NGINX will be possible. And even better - have an ability to install both web-servers.

**Comment by geerlingguy** [comment]
I knew someone would open this ticket :)

I already have a `geerlingguy.nginx` role that I'm using on most of my production servers, so I'm interested in this too. The main thing I may need to do is abstract virtualhost configuration a bit so the same `config.yml` settings will work with either Apache or Nginx.

**Comment by geerlingguy** [comment]
Also, there are now a few other Apache-specific configuration bits (like adding the `www-data` user to the `dialout` group so permissions are better-configured for Drupal 8/Apache 2) that I'll need to take into account.

**Comment by ivanjaros** [comment]
+1 for nginx.

**Comment by nolfranklin** [comment]
+1 for nginx.

**Comment by geerlingguy** [comment]
Also see related config for the drupal-pi project (for those wishing to see an example of Ansible + Nginx with Drupal): https://github.com/geerlingguy/drupal-pi/blob/master/templates/drupal.conf.j2

**Comment by geerlingguy** [comment]
So... this is a whole lot easier than I originally thought it would be. Testing out some other things now.

**Comment by geerlingguy** [comment]
Also, to @BR0kEN- — I'd rather not support both servers running simultaneously because of the slight additional complexity that may add. While it's perfectly valid to see someone use something like Nginx for a balancer, Varnish for reverse proxy, and Apache for webserver, I don't want to support that kind of configuration.

For 99% of sites, it's better to standardize on either Apache or Nginx for as much of the stack as possible. And with Nginx, if you configure caching, you might not need some of the extra features of Varnish either, which makes your stack that much simpler (that's how I'm running most of my Drupal infrastructure nowadays—Nginx == load balancer + Nginx == reverse proxy and general webserver. Makes configuration so much simpler.
