### ISSUE TITLE
Preserve git repo information for cloned Drupal repository

### ISSUE THREAD

**Issue by YesCT** [geerlingguy/drupal-vm#90]
Maybe wont fix for reasons similar to those discussed in https://github.com/geerlingguy/drupal-vm/issues/3 

But, for my use case, of wanting to work on core, I end up having to remove the drupal html root, and copy over one from a git clone that has git information. This is nice because then, I can also pull to get the latest changes.

What would be the downside of including the git repo info in drupal-vm?

What is a work around?
1) Just git init the dir so can start tracking changes? (lets me make patches, but not pull to keep up with head)
2) When I would normally pull throughout the day, just vagrant destroy, and then vagrant up?
3) Copy .git folder from a local git clone repo, to the sync'd local folder, and then do: git reset --hard HEAD (and then can pull like usual).

**Comment by geerlingguy** [comment]
@YesCT - Excellent question, but maybe not a wontfix... I'll have to think on this a little more, since this workflow (doing D8 HEAD work and tracking via Git) is one of the main uses I have for Drupal VM.

The main workaround for now (which is what I'm doing currently) is to:

  1. Clone D8 locally (e.g. in `~/Sites/drupal-8`).
  2. Set up a synced folder from that local path into a location inside the VM, e.g. `/var/www/drupal`
  3. Set `build_from_makefile` to `false` (so you can install Drupal yourself).
  4. Update `drupal_core_path` to the synced folder location inside the VM (from step 1).
  5. Once the VM is built, you will have a `drupal` database and `drupal`/`drupal` user that you can use to install the Drupal site at `drupaltest.dev` (or whatever you have set as the `drupal_domain`.

I would definitely consider building an alternate workflow for Drupal core contributions, with a custom `example.config.yml` (maybe `corecontrib.config.yml`?), which configures Drupal VM to do the git clone into the local folder automatically, and installs the site as a normal barebones Drupal site instead of via makefile.

**Comment by geerlingguy** [comment]
So, this was much simpler than I originally anticipated. Just requires two changes—first, the addition of `--no-gitinfofile` to the `drush make` command inside `provisioning/tasks/drupal.yml`, and second, the use of the `working-copy` parameter for the Drupal core definition in the make file:

```
projects:

  drupal:
    type: core
    version: 8.0.x
    download:
      working-copy: true
```

This preserves the `.git` directory in the cloned Git repository, so you can patch away—either from within Drupal VM (logged in via `vagrant ssh`), or from your host machine (which is a tad faster, since it doesn't require the ~20% overhead for file access that NFS requires).
