### ISSUE TITLE
60 second timeout while debugging with xdebug

### ISSUE THREAD

**Issue by jayusa123** [geerlingguy/drupal-vm#903]
(I'm using PhpStorm, Safari (& Chrome), CentOS 7, Apache 2.4.6, PHP 5.6.26, xdebug 2.4)

When I am actively debugging (execution is paused in PhpStorm) I receive a 503 Service Unavailable error in the browser after 60 seconds. Does anyone know where the setting lives for this 1-minute timeout?

Thanks,
Jay

**Comment by geerlingguy** [comment]
@jayusa123 - It's likely `php_max_execution_time: "60"` (that's the default, you can override it though in config.yml).

**Comment by jayusa123** [comment]
Hmm, no. That doesn't seem to be it. I tried changing the max execution time to 120 but the page still times out after 60 seconds.

**Comment by geerlingguy** [comment]
@jayusa123 - Did you do a `vagrant --provision` afterwards? That's necessary to get the change to apply. And if it's still timing out after 60s after that, there must be some other timeout happening in the chain...

**Comment by jayusa123** [comment]
Yes, I re-provisioned the box. I had originally tried just modifying the value in php.ini and reloading php-fpm, but the change didn't make any difference. So, I tried setting php_max_execution_time in config.yml and re-provisioning. The config change appears in phpinfo(), but the page load still times out after 60 seconds of waiting for the paused debugger.

**Comment by jayusa123** [comment]
As a shot in the dark, I also tried changing php_max_input_time to 120, but received the same results.

**Comment by jayusa123** [comment]
Could we reopen this issue. Perhaps someone else has come across a solution to this issue...

**Comment by geerlingguy** [comment]
Sure thing!

**Comment by i813380** [comment]
I have a similar problem but it's not on a vm.  I'm running drupal on an ubuntu server with PHPStorm on a Macbook.  I lose my debug connection after 60 sec.  Can't debug long-running tasks because of this, what a pain.  Using the following params in php.ini to remotely debug.  Would love insight as to the fix.

;XDEBUG
; zend_extension tells the Zend PHP interpreter that we're using Xdebug instead of Zend's own debugger
  zend_extension="/usr/local/lib/php/extensions/no-debug-zts-20131226/xdebug.so"
; Xdebug configuration options:
  xdebug.remote_enable=1
  xdebug.remote_handler=dbgp
  xdebug.remote_mode=req
;remote_host is where PHPStorm is running, so replace xx.xx.xxx.xxx with IP address of your Windows client
  xdebug.remote_host=10.10.10.10
;remote_port is where Windows client is listening for calls from XDebug
  xdebug.remote_port=9999
;remote_connect_back overrides remote_host, telling Xdebug to connect to whichever IP address initiated the http request to the target server
  xdebug.remote_connect_back=1
;remote_autostart allows us to start debugging even if the required cookie is missing (workaround ...)
  xdebug.remote_autostart=1
;idekey is the value of the XDEBUG_SESSION cookie sent in the windows client's http request and expected by the XDebug engine
  xdebug.idekey=PHPSTORM

**Comment by oxyc** [comment]
Found this and thought it might be worth a shot: https://bugzilla.mozilla.org/show_bug.cgi?id=979268

Could you try with firefox and changing the `network.http.response.timeout` value as described in the last comment.

**Comment by jayusa123** [comment]
Thanks for the suggestion, @oxyc. I just tried this; unfortunately, it did make any difference. The page load still timed out 60 seconds after the debugger paused the execution.

**Comment by oxyc** [comment]
Another issue that sounds like it could be related http://stackoverflow.com/a/4613189/319855

**Comment by geerlingguy** [comment]
This sounds like some sort of upstream issue/configuration value, and I'm not sure if I can be much help here—I'd suggest asking on Drupal Answers, Stack Overflow, etc. and see if you can get a better response.

If someone can find any evidence there's a setting in Drupal VM that could be causing the 60 second timeout (we've already looked at the general PHP settings), then we can reopen the issue and go from there (maybe try testing on MAMP or a local LAMP stack too?).

**Comment by klaasvw** [comment]
We had a similar issue. The server returned a 503 after 5 minutes of inactivity during an xdebug session.

In our case we were able to fix it by modifying the Timeout apache setting in the vhost. By default it was set to 300.

**Comment by gauravsharma** [comment]
Thought the thread is quite old, but may be it could be of use of someone else.

Try this:

`sudo vi /etc/haproxy/haproxy.cfg`
Search for variable `"timeout server"` 
increase its value from `30s` to your desired value. 
save the file 
restart haproxy service
`sudo service haproxy restart`

**Comment by augustocosta** [comment]
You should try:

/etc/php/7.0/fpm/php-fpm.conf
request_terminate_timeout = 120s (desired value)
sudo service php-fpm restart

**Comment by pau1m** [comment]
There's also `keepalive_timeout` in `/etc/nginx/nginx.conf` that may affect

**Comment by salvis** [comment]
I've had a similar problem: 500 Internal Server Error after 64 seconds.
Eugene of JetBrains support pointed me here for additional ideas and this thread came up pretty quickly in further searches, too, so I'll add my solution here.  :-)

The culprit was the

> FcgidIOTimeout 64

setting in MAMP PRO's **Apache httpd.conf** file!

**Comment by michaellenahan** [comment]
On my local centos7 vm, I found that these steps were needed to fix this problem of the xdebug 60 second timeout.

(1) Add timeout=300 to ProxyPassMatch in /etc/httpd/conf.d/vhosts.conf
```
cat /etc/httpd/conf.d/vhosts.conf | grep ProxyPassMatch
  ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/dkrweb.local/docroot" timeout=300
```
(2)
https://stackoverflow.com/questions/4139794/why-does-my-netbeans-xdebug-session-timeout-after-period-of-inactivity/4613189#4613189
```
vi /etc/php.d/xdebug.ini
```
```
xdebug.remote_cookie_expire_time = 3600
```

**Comment by huaweichen** [comment]
> You should try:
> 
> /etc/php/7.0/fpm/php-fpm.conf
> request_terminate_timeout = 120s (desired value)
> sudo /etc/init.d/php7.0-fpm restart

This works for me. Thanks.
