### ISSUE TITLE
Swap Drupal make with Pantheon

### ISSUE THREAD

**Issue by ivanjaros** [geerlingguy/drupal-vm#92]
Hi.
I am a looking to "migrate" from XAMP to Vagrant so I am looking for ready-to-use solutions and I like the idea of this project but I am working with Pantheon so I would need Vagrant to fetch the configured environment instead of Drupal. Would it be possible to add support for Pantheon?

**Comment by geerlingguy** [comment]
@ivanjaros - At this point, I would like to make Drupal VM flexible enough to emulate most any environment via `config.yml`, but I don't want to add specific platform support to fetch configurations (e.g. Patheon, Acquia Cloud, Platform.sh, etc.) since that would be unmaintainable in the long run (especially considering I don't even use any of those platforms for my own projects).

However, if you or someone else can come up with a shell script or something similar to help with pulling down Pantheon configs, I would gladly link to them in the wiki.
