### ISSUE TITLE
Drush bash/sh errors

### ISSUE THREAD

**Issue by paulsheldrake** [geerlingguy/drupal-vm#962]
Getting this error when running drush

```
[vagrant@ico web]$ drush cc all
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
 [success] 'all' cache was cleared.
```

Running centos7 on box 1.1.3

**Comment by geerlingguy** [comment]
Looks like it's this issue: https://github.com/drush-ops/drush/issues/2065

I've just merged a fix in the PHP role which will allow you to fix this by adding the following to your `config.yml` (if you run in to this error):

```
php_disable_functions:
  - pcntl_exec
```

Then run `vagrant provision` to add that into the PHP configuration. Note that it won't be merged/ready in Drupal VM `master` until after this issue is closed out (I'm still running some tests).
